
var g;g||(g=typeof Module !== 'undefined' ? Module : {});g.Tf||(g.Tf=0);g.Tf++;
(function(a){function b(m,r,t){var u=new XMLHttpRequest;u.open("GET",m,!0);u.responseType="arraybuffer";u.onprogress=function(w){var y=r;w.total&&(y=w.total);if(w.loaded){u.hf?g.tf[m].loaded=w.loaded:(u.hf=!0,g.tf||(g.tf={}),g.tf[m]={loaded:w.loaded,total:y});var B=y=w=0,D;for(D in g.tf){var H=g.tf[D];w+=H.total;y+=H.loaded;B++}w=Math.ceil(w*g.Tf/B);g.setStatus&&g.setStatus("Downloading data... ("+y+"/"+w+")")}else!g.tf&&g.setStatus&&g.setStatus("Downloading data...")};u.onerror=function(){throw Error("NetworkError for: "+
m);};u.onload=function(){if(200==u.status||304==u.status||206==u.status||0==u.status&&u.response)t(u.response);else throw Error(u.statusText+" : "+u.responseURL);};u.send(null)}function c(m){console.error("package error:",m)}function d(){function m(w,y,B){this.start=w;this.Of=y;this.audio=B}function r(w){if(!w)throw"Loading data file failed."+Error().stack;if(!(w instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;w=new Uint8Array(w);m.prototype.Bg=w;w=a.files;for(var y=0;y<
w.length;++y)m.prototype.hf[w[y].filename].onload();g.removeRunDependency("datafile_build/web/index.data")}g.FS_createPath("/","assets",!0,!0);m.prototype={hf:{},open:function(w,y){this.name=y;this.hf[y]=this;g.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.Ag(this.Bg.subarray(this.start,this.Of))},Ag:function(w){g.FS_createDataFile(this.name,null,w,!0,!0,!0);g.removeRunDependency("fp "+this.name);this.hf[this.name]=null}};for(var t=a.files,u=0;u<t.length;++u)(new m(t[u].start,
t[u].end,t[u].audio)).open("GET",t[u].filename);g.addRunDependency("datafile_build/web/index.data");g.og||(g.og={});g.og["build/web/index.data"]={Zg:!1};l?(r(l),l=null):k=r}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";
"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,h("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("index.data",""):"index.data",f=a.remote_package_size,k=null,l=g.getPreloadedPackage?g.getPreloadedPackage(e,f):null;l||b(e,f,function(m){k?(k(m),k=null):l=m},c);g.calledRun?d():(g.preRun||(g.preRun=[]),g.preRun.push(d))})({files:[{filename:"/assets/atlas.dat",
start:0,end:376,audio:0},{filename:"/assets/atlas.png",start:376,end:4234,audio:0}],remote_package_size:4234,package_uuid:"16e7ca8a-371a-483e-bc7f-cd8c5a53d7c5"});var aa={},ba;for(ba in g)g.hasOwnProperty(ba)&&(aa[ba]=g[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;ha="function"===typeof importScripts;ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ja=!fa&&!ia&&!ha;
var n="",ka,la,ma,na,oa;
if(ia)n=ha?require("path").dirname(n)+"/":__dirname+"/",ka=function(a,b){na||(na=require("fs"));oa||(oa=require("path"));a=oa.normalize(a);return na.readFileSync(a,b?null:"utf8")},ma=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof pa))throw a;}),process.on("unhandledRejection",
p),ea=function(a){process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ja)"undefined"!=typeof read&&(ka=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||ha)ha?n=self.location.href:"undefined"!==typeof document&&document.currentScript&&(n=document.currentScript.src),n=0!==n.indexOf("blob:")?n.substr(0,n.lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
la=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var qa=g.print||console.log.bind(console),h=g.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(g[ba]=aa[ba]);aa=null;g.arguments&&(ca=g.arguments);g.thisProgram&&(da=g.thisProgram);g.quit&&(ea=g.quit);function ra(a){sa||(sa={});sa[a]||(sa[a]=1,h(a))}var sa,ta;g.wasmBinary&&(ta=g.wasmBinary);
var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&p("no native wasm support detected");
function ua(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":q[a>>0]=b;break;case "i8":q[a>>0]=b;break;case "i16":va[a>>1]=b;break;case "i32":v[a>>2]=b;break;case "i64":wa=[b>>>0,(x=b,1<=+Math.abs(x)?0<x?(Math.min(+Math.floor(x/4294967296),4294967295)|0)>>>0:~~+Math.ceil((x-+(~~x>>>0))/4294967296)>>>0:0)];v[a>>2]=wa[0];v[a+4>>2]=wa[1];break;case "float":z[a>>2]=b;break;case "double":xa[a>>3]=b;break;default:p("invalid type for setValue: "+c)}}var ya,za=!1,Aa;
function assert(a,b){a||p("Assertion failed: "+b)}function Ba(a){var b=Ca(a.length);a.subarray||a.slice?A.set(a,b):A.set(new Uint8Array(a),b);return b}var Ea="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Fa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ea)return Ea.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function C(a,b){return a?Fa(A,a,b):""}
function E(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var l=a.charCodeAt(++f);k=65536+((k&1023)<<10)|l&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function Ga(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ha(a){var b=Ga(a)+1,c=Ia(b);E(a,q,c,b);return c}var Ja,q,A,va,Ka,v,F,z,xa;
function La(){var a=ya.buffer;Ja=a;g.HEAP8=q=new Int8Array(a);g.HEAP16=va=new Int16Array(a);g.HEAP32=v=new Int32Array(a);g.HEAPU8=A=new Uint8Array(a);g.HEAPU16=Ka=new Uint16Array(a);g.HEAPU32=F=new Uint32Array(a);g.HEAPF32=z=new Float32Array(a);g.HEAPF64=xa=new Float64Array(a)}var G,Ma=[],Na=[],Oa=[],Pa=[];function Qa(){var a=g.preRun.shift();Ma.unshift(a)}var Ra=0,Sa=null,Ta=null;function Ua(){Ra++;g.monitorRunDependencies&&g.monitorRunDependencies(Ra)}
function Va(){Ra--;g.monitorRunDependencies&&g.monitorRunDependencies(Ra);if(0==Ra&&(null!==Sa&&(clearInterval(Sa),Sa=null),Ta)){var a=Ta;Ta=null;a()}}g.preloadedImages={};g.preloadedAudios={};function p(a){if(g.onAbort)g.onAbort(a);h(a);za=!0;Aa=1;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Wa(a){var b=Xa;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}
function Ya(){return Wa("data:application/octet-stream;base64,")}var Xa="index.wasm";if(!Ya()){var Za=Xa;Xa=g.locateFile?g.locateFile(Za,n):n+Za}function $a(){var a=Xa;try{if(a==Xa&&ta)return new Uint8Array(ta);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}catch(b){p(b)}}
function ab(){if(!ta&&(fa||ha)){if("function"===typeof fetch&&!Wa("file://"))return fetch(Xa,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Xa+"'";return a.arrayBuffer()}).catch(function(){return $a()});if(la)return new Promise(function(a,b){la(Xa,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return $a()})}
var x,wa,cb={23592:function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?1:0},23729:function(){return"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?1:0},23953:function(a){var b=g.SDL2;if(a){void 0!==b.capture.zf&&clearTimeout(b.capture.zf);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.gf&&(b.capture.gf.onaudioprocess=function(){},b.capture.gf.disconnect(),b.capture.gf=void 0);void 0!==b.capture.Ff&&(b.capture.Ff.disconnect(),b.capture.Ff=void 0);void 0!==b.capture.Lf&&(b.capture.Lf=void 0);b.capture=void 0}else void 0!=b.audio.gf&&(b.audio.gf.disconnect(),b.audio.gf=void 0),b.audio=void 0;void 0!==b.ff&&void 0===b.audio&&void 0===b.capture&&(b.ff.close(),b.ff=void 0)},25125:function(a){"undefined"===typeof g.SDL2&&(g.SDL2={});var b=g.SDL2;
a?b.capture={}:b.audio={};b.ff||("undefined"!==typeof AudioContext?b.ff=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.ff=new webkitAudioContext),b.ff&&bb(b.ff));return void 0===b.ff?-1:0},25618:function(){return g.SDL2.ff.sampleRate},25686:function(a,b,c,d){function e(){}function f(l){void 0!==k.capture.zf&&(clearTimeout(k.capture.zf),k.capture.zf=void 0);k.capture.Ff=k.ff.createMediaStreamSource(l);k.capture.gf=k.ff.createScriptProcessor(b,a,1);k.capture.gf.onaudioprocess=function(m){void 0!==
k&&void 0!==k.capture&&(m.outputBuffer.getChannelData(0).fill(0),k.capture.Pf=m.inputBuffer,m=[d],G.get(c).apply(null,m))};k.capture.Ff.connect(k.capture.gf);k.capture.gf.connect(k.ff.destination);k.capture.stream=l}var k=g.SDL2;k.capture.Lf=k.ff.createBuffer(a,b,k.ff.sampleRate);k.capture.Lf.getChannelData(0).fill(0);k.capture.zf=setTimeout(function(){k.capture.Pf=k.capture.Lf;var l=[d];G.get(c).apply(null,l)},b/k.ff.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?
navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},27338:function(a,b,c,d){var e=g.SDL2;e.audio.gf=e.ff.createScriptProcessor(b,0,a);e.audio.gf.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.eg=f.outputBuffer,f=[d],G.get(c).apply(null,f))};e.audio.gf.connect(e.ff.destination)},27748:function(a,b){for(var c=g.SDL2,d=c.audio.eg.numberOfChannels,e=0;e<d;++e){var f=c.audio.eg.getChannelData(e);
if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var k=0;k<b;++k)f[k]=z[a+(k*d+e<<2)>>2]}},28228:function(a,b){for(var c=g.SDL2,d=c.capture.Pf.numberOfChannels,e=0;e<d;++e){var f=c.capture.Pf.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var k=0;k<b;++k)ua(a+4*k,f[k],"float");else for(k=0;k<b;++k)ua(a+
4*(k*d+e),f[k],"float")}}};function db(a,b,c){a.addEventListener(b,c,{once:!0})}function bb(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&db(d,c,function(){"suspended"===a.state&&a.resume()})})})}function fb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Dg;"number"===typeof c?void 0===b.Af?G.get(c)():G.get(c)(b.Af):c(void 0===b.Af?null:b.Af)}}}
function gb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function hb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=gb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function ib(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function jb(a){if("/"===a)return"/";a=hb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function kb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){p("randomDevice")}}
function lb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=gb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var mb=[];function nb(a,b){mb[a]={input:[],output:[],vf:b};ob(a,pb)}
var pb={open:function(a){var b=mb[a.node.rdev];if(!b)throw new I(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.vf.flush(a.tty)},flush:function(a){a.tty.vf.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.vf.ig)throw new I(60);for(var e=0,f=0;f<d;f++){try{var k=a.tty.vf.ig(a.tty)}catch(l){throw new I(29);}if(void 0===k&&0===e)throw new I(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.vf.Zf)throw new I(60);
try{for(var e=0;e<d;e++)a.tty.vf.Zf(a.tty,b[c+e])}catch(f){throw new I(29);}d&&(a.node.timestamp=Date.now());return e}},rb={ig:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.hf?Buffer.hf(256):new Buffer(256),d=0;try{d=na.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=qb(b,!0)}return a.input.shift()},Zf:function(a,b){null===b||10===b?(qa(Fa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(qa(Fa(a.output,0)),a.output=[])}},sb={Zf:function(a,b){null===b||10===b?(h(Fa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(h(Fa(a.output,0)),a.output=[])}},J={nf:null,pf:function(){return J.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new I(63);J.nf||(J.nf={dir:{node:{qf:J.df.qf,kf:J.df.kf,lookup:J.df.lookup,Gf:J.df.Gf,rename:J.df.rename,unlink:J.df.unlink,rmdir:J.df.rmdir,readdir:J.df.readdir,symlink:J.df.symlink},stream:{rf:J.cf.rf}},file:{node:{qf:J.df.qf,kf:J.df.kf},stream:{rf:J.cf.rf,read:J.cf.read,write:J.cf.write,ag:J.cf.ag,Hf:J.cf.Hf,Jf:J.cf.Jf}},link:{node:{qf:J.df.qf,kf:J.df.kf,readlink:J.df.readlink},stream:{}},dg:{node:{qf:J.df.qf,
kf:J.df.kf},stream:tb}});c=ub(a,b,c,d);16384===(c.mode&61440)?(c.df=J.nf.dir.node,c.cf=J.nf.dir.stream,c.bf={}):32768===(c.mode&61440)?(c.df=J.nf.file.node,c.cf=J.nf.file.stream,c.ef=0,c.bf=null):40960===(c.mode&61440)?(c.df=J.nf.link.node,c.cf=J.nf.link.stream):8192===(c.mode&61440)&&(c.df=J.nf.dg.node,c.cf=J.nf.dg.stream);c.timestamp=Date.now();a&&(a.bf[b]=c,a.timestamp=c.timestamp);return c},$g:function(a){return a.bf?a.bf.subarray?a.bf.subarray(0,a.ef):new Uint8Array(a.bf):new Uint8Array(0)},
fg:function(a,b){var c=a.bf?a.bf.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.bf,a.bf=new Uint8Array(b),0<a.ef&&a.bf.set(c.subarray(0,a.ef),0))},Pg:function(a,b){if(a.ef!=b)if(0==b)a.bf=null,a.ef=0;else{var c=a.bf;a.bf=new Uint8Array(b);c&&a.bf.set(c.subarray(0,Math.min(b,a.ef)));a.ef=b}},df:{qf:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===
(a.mode&61440)?b.size=a.ef:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.yg=4096;b.blocks=Math.ceil(b.size/b.yg);return b},kf:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&J.Pg(a,b.size)},lookup:function(){throw vb[44];},Gf:function(a,b,c,d){return J.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=wb(b,
c)}catch(f){}if(d)for(var e in d.bf)throw new I(55);}delete a.parent.bf[a.name];a.parent.timestamp=Date.now();a.name=c;b.bf[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.bf[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=wb(a,b),d;for(d in c.bf)throw new I(55);delete a.bf[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.bf)a.bf.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=J.createNode(a,b,41471,0);a.link=c;return a},
readlink:function(a){if(40960!==(a.mode&61440))throw new I(28);return a.link}},cf:{read:function(a,b,c,d,e){var f=a.node.bf;if(e>=a.node.ef)return 0;a=Math.min(a.node.ef-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===q.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.bf||a.bf.subarray)){if(f)return a.bf=b.subarray(c,c+d),a.ef=d;if(0===a.ef&&0===e)return a.bf=b.slice(c,c+d),a.ef=
d;if(e+d<=a.ef)return a.bf.set(b.subarray(c,c+d),e),d}J.fg(a,e+d);if(a.bf.subarray&&b.subarray)a.bf.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.bf[e+f]=b[c+f];a.ef=Math.max(a.ef,e+d);return d},rf:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ef);if(0>b)throw new I(28);return b},ag:function(a,b,c){J.fg(a.node,b+c);a.node.ef=Math.max(a.node.ef,b+c)},Hf:function(a,b,c,d,e,f){if(0!==b)throw new I(28);if(32768!==(a.node.mode&61440))throw new I(43);a=a.node.bf;if(f&
2||a.buffer!==Ja){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=Ca(f);c<f;)q[b+c++]=0;c=b;if(!c)throw new I(48);q.set(a,c)}else d=!1,c=a.byteOffset;return{Ng:c,Nf:d}},Jf:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new I(43);if(e&2)return 0;J.cf.write(a,b,0,d,c,!1);return 0}}},xb=null,yb={},zb=[],Ab=1,Bb=null,Cb=!0,Db={},I=null,vb={};
function Eb(a,b){a=lb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={gg:!0,$f:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.$f)throw new I(32);a=gb(a.split("/").filter(function(k){return!!k}),!1);var e=xb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=wb(e,a[d]);c=hb(c+"/"+a[d]);e.yf&&(!f||f&&b.gg)&&(e=e.yf.root);if(!f||b.Uf)for(f=0;40960===(e.mode&61440);)if(e=Fb(c),c=lb(ib(c),e),e=Eb(c,{$f:b.$f}).node,40<f++)throw new I(32);}return{path:c,node:e}}
function Gb(a){for(var b;;){if(a===a.parent)return a=a.pf.mg,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Hb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Bb.length}function wb(a,b){var c;if(c=(c=Ib(a,"x"))?c:a.df.lookup?0:2)throw new I(c,a);for(c=Bb[Hb(a.id,b)];c;c=c.uf){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.df.lookup(a,b)}
function ub(a,b,c,d){a=new Jb(a,b,c,d);b=Hb(a.parent.id,a.name);a.uf=Bb[b];return Bb[b]=a}var Kb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Lb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ib(a,b){if(Cb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Mb(a,b){try{return wb(a,b),20}catch(c){}return Ib(a,"wx")}
function Nb(a){var b=4096;for(a=a||0;a<=b;a++)if(!zb[a])return a;throw new I(33);}function Ob(a,b){Pb||(Pb=function(){},Pb.prototype={});var c=new Pb,d;for(d in a)c[d]=a[d];a=c;b=Nb(b);a.fd=b;return zb[b]=a}var tb={open:function(a){a.cf=yb[a.node.rdev].cf;a.cf.open&&a.cf.open(a)},rf:function(){throw new I(70);}};function ob(a,b){yb[a]={cf:b}}
function Qb(a,b){var c="/"===b,d=!b;if(c&&xb)throw new I(10);if(!c&&!d){var e=Eb(b,{gg:!1});b=e.path;e=e.node;if(e.yf)throw new I(10);if(16384!==(e.mode&61440))throw new I(54);}b={type:a,hh:{},mg:b,Lg:[]};a=a.pf(b);a.pf=b;b.root=a;c?xb=a:e&&(e.yf=b,e.pf&&e.pf.Lg.push(b))}function Rb(a,b,c){var d=Eb(a,{parent:!0}).node;a=jb(a);if(!a||"."===a||".."===a)throw new I(28);var e=Mb(d,a);if(e)throw new I(e);if(!d.df.Gf)throw new I(63);return d.df.Gf(d,a,b,c)}function K(a){return Rb(a,16895,0)}
function Sb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Rb(a,b|8192,c)}function Tb(a,b){if(!lb(a))throw new I(44);var c=Eb(b,{parent:!0}).node;if(!c)throw new I(44);b=jb(b);var d=Mb(c,b);if(d)throw new I(d);if(!c.df.symlink)throw new I(63);c.df.symlink(c,b,a)}
function Ub(a){var b=Eb(a,{parent:!0}).node,c=jb(a),d=wb(b,c);a:{try{var e=wb(b,c)}catch(k){e=k.jf;break a}var f=Ib(b,"wx");e=f?f:16384===(e.mode&61440)?31:0}if(e)throw new I(e);if(!b.df.unlink)throw new I(63);if(d.yf)throw new I(10);try{Db.willDeletePath&&Db.willDeletePath(a)}catch(k){h("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+k.message)}b.df.unlink(b,c);b=Hb(d.parent.id,d.name);if(Bb[b]===d)Bb[b]=d.uf;else for(b=Bb[b];b;){if(b.uf===d){b.uf=d.uf;break}b=b.uf}try{if(Db.onDeletePath)Db.onDeletePath(a)}catch(k){h("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+k.message)}}function Fb(a){a=Eb(a).node;if(!a)throw new I(44);if(!a.df.readlink)throw new I(28);return lb(Gb(a.parent),a.df.readlink(a))}function Vb(a,b){a="string"===typeof a?Eb(a,{Uf:!0}).node:a;if(!a.df.kf)throw new I(63);a.df.kf(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Wb(a,b,c,d){if(""===a)throw new I(44);if("string"===typeof b){var e=Kb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=hb(a);try{f=Eb(a,{Uf:!(b&131072)}).node}catch(k){}}e=!1;if(b&64)if(f){if(b&128)throw new I(20);}else f=Rb(a,c,0),e=!0;if(!f)throw new I(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new I(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==Lb(b)||b&512)?31:Ib(f,Lb(b)):44))throw new I(c);if(b&512){c=f;c="string"===typeof c?Eb(c,{Uf:!0}).node:c;if(!c.df.kf)throw new I(63);if(16384===(c.mode&61440))throw new I(31);if(32768!==(c.mode&61440))throw new I(28);if(e=Ib(c,"w"))throw new I(e);c.df.kf(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Ob({node:f,path:Gb(f),flags:b,seekable:!0,position:0,cf:f.cf,Rg:[],error:!1},d);d.cf.open&&d.cf.open(d);!g.logReadFiles||b&1||(Xb||(Xb={}),a in Xb||(Xb[a]=1,h("FS.trackingDelegate error on read file: "+
a)));try{Db.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Db.onOpenFile(a,f))}catch(k){h("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}return d}function Yb(a){if(null===a.fd)throw new I(8);a.Wf&&(a.Wf=null);try{a.cf.close&&a.cf.close(a)}catch(b){throw b;}finally{zb[a.fd]=null}a.fd=null}
function Zb(a,b,c){if(null===a.fd)throw new I(8);if(!a.seekable||!a.cf.rf)throw new I(70);if(0!=c&&1!=c&&2!=c)throw new I(28);a.position=a.cf.rf(a,b,c);a.Rg=[]}
function $b(a,b,c,d,e,f){if(0>d||0>e)throw new I(28);if(null===a.fd)throw new I(8);if(0===(a.flags&2097155))throw new I(8);if(16384===(a.node.mode&61440))throw new I(31);if(!a.cf.write)throw new I(28);a.seekable&&a.flags&1024&&Zb(a,0,2);var k="undefined"!==typeof e;if(!k)e=a.position;else if(!a.seekable)throw new I(70);b=a.cf.write(a,b,c,d,e,f);k||(a.position+=b);try{if(a.path&&Db.onWriteToFile)Db.onWriteToFile(a.path)}catch(l){h("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
l.message)}return b}function ac(){I||(I=function(a,b){this.node=b;this.Qg=function(c){this.jf=c};this.Qg(a);this.message="FS error"},I.prototype=Error(),I.prototype.constructor=I,[44].forEach(function(a){vb[a]=new I(a);vb[a].stack="<generic error, no stack>"}))}var bc;function cc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function dc(a,b){a="string"===typeof a?a:Gb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=hb(a+"/"+c);try{K(d)}catch(e){}a=d}}return d}
function ec(a,b,c,d){a=hb(("string"===typeof a?a:Gb(a))+"/"+b);c=cc(c,d);return Rb(a,(void 0!==c?c:438)&4095|32768,0)}function fc(a,b,c,d,e,f){a=b?hb(("string"===typeof a?a:Gb(a))+"/"+b):a;d=cc(d,e);e=Rb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}Vb(e,d|146);a=Wb(e,577);$b(a,c,0,c.length,0,f);Yb(a);Vb(e,d)}return e}
function L(a,b,c,d){a=hb(("string"===typeof a?a:Gb(a))+"/"+b);b=cc(!!c,!!d);L.kg||(L.kg=64);var e=L.kg++<<8|0;ob(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,k,l,m){for(var r=0,t=0;t<m;t++){try{var u=c()}catch(w){throw new I(29);}if(void 0===u&&0===r)throw new I(6);if(null===u||void 0===u)break;r++;k[l+t]=u}r&&(f.node.timestamp=Date.now());return r},write:function(f,k,l,m){for(var r=0;r<m;r++)try{d(k[l+r])}catch(t){throw new I(29);}m&&(f.node.timestamp=
Date.now());return r}});return Sb(a,b,e)}function hc(a){if(!(a.Hg||a.Ig||a.link||a.bf)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ka)try{a.bf=qb(ka(a.url),!0),a.ef=a.bf.length}catch(b){throw new I(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function ic(a,b,c,d,e){function f(){this.Xf=!1;this.hf=[]}f.prototype.get=function(t){if(!(t>this.length-1||0>t)){var u=t%this.chunkSize;return this.jg(t/this.chunkSize|0)[u]}};f.prototype.Of=function(t){this.jg=t};f.prototype.bg=function(){var t=new XMLHttpRequest;t.open("HEAD",c,!1);t.send(null);if(!(200<=t.status&&300>t.status||304===t.status))throw Error("Couldn't load "+c+". Status: "+t.status);var u=Number(t.getResponseHeader("Content-length")),w,y=(w=t.getResponseHeader("Accept-Ranges"))&&
"bytes"===w;t=(w=t.getResponseHeader("Content-Encoding"))&&"gzip"===w;var B=1048576;y||(B=u);var D=this;D.Of(function(H){var eb=H*B,Da=(H+1)*B-1;Da=Math.min(Da,u-1);if("undefined"===typeof D.hf[H]){var oe=D.hf;if(eb>Da)throw Error("invalid range ("+eb+", "+Da+") or no bytes requested!");if(Da>u-1)throw Error("only "+u+" bytes available! programmer error!");var O=new XMLHttpRequest;O.open("GET",c,!1);u!==B&&O.setRequestHeader("Range","bytes="+eb+"-"+Da);"undefined"!=typeof Uint8Array&&(O.responseType=
"arraybuffer");O.overrideMimeType&&O.overrideMimeType("text/plain; charset=x-user-defined");O.send(null);if(!(200<=O.status&&300>O.status||304===O.status))throw Error("Couldn't load "+c+". Status: "+O.status);eb=void 0!==O.response?new Uint8Array(O.response||[]):qb(O.responseText||"",!0);oe[H]=eb}if("undefined"===typeof D.hf[H])throw Error("doXHR failed!");return D.hf[H]});if(t||!u)B=u=1,B=u=this.jg(0).length,qa("LazyFiles on gzip forces download of the whole file when length is accessed");this.xg=
u;this.wg=B;this.Xf=!0};if("undefined"!==typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new f;Object.defineProperties(k,{length:{get:function(){this.Xf||this.bg();return this.xg}},chunkSize:{get:function(){this.Xf||this.bg();return this.wg}}});var l=void 0}else l=c,k=void 0;var m=ec(a,b,d,e);k?m.bf=k:l&&(m.bf=null,m.url=l);Object.defineProperties(m,{ef:{get:function(){return this.bf.length}}});
var r={};Object.keys(m.cf).forEach(function(t){var u=m.cf[t];r[t]=function(){hc(m);return u.apply(null,arguments)}});r.read=function(t,u,w,y,B){hc(m);t=t.node.bf;if(B>=t.length)return 0;y=Math.min(t.length-B,y);if(t.slice)for(var D=0;D<y;D++)u[w+D]=t[B+D];else for(D=0;D<y;D++)u[w+D]=t.get(B+D);return y};m.cf=r;return m}
function jc(a,b,c,d,e,f,k,l,m,r){function t(y){function B(H){r&&r();l||fc(a,b,H,d,e,m);f&&f();Va(w)}var D=!1;g.preloadPlugins.forEach(function(H){!D&&H.canHandle(u)&&(H.handle(y,u,B,function(){k&&k();Va(w)}),D=!0)});D||B(y)}kc();var u=b?lb(hb(a+"/"+b)):a,w="cp "+u;Ua(w);"string"==typeof c?lc(c,function(y){t(y)},k):t(c)}var M={},Pb,Xb,mc={},nc=void 0;function oc(){nc+=4;return v[nc-4>>2]}function pc(a){a=zb[a];if(!a)throw new I(8);return a}var qc;
ia?qc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?qc=dateNow:qc=function(){return performance.now()};function rc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,k){b.drawElementsInstancedANGLE(c,d,e,f,k)})}
function sc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function tc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var uc=1,vc=[],N=[],wc=[],xc=[],yc=[],P=[],Q=[],R=[],zc=[],S=[],Ac=[],T=[],Bc=[],Cc=[],Dc={},Ec={},Fc={},Gc=4;function U(a){Hc||(Hc=a)}function Ic(a){for(var b=uc++,c=a.length;c<b;c++)a[c]=null;return b}function Jc(a,b){a.hg||(a.hg=a.getContext,a.getContext=function(d,e){e=a.hg(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.lg?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Kc(c,b):0}
function Kc(a,b){var c=Ic(zc),d={ah:c,attributes:b,version:b.lg,Mf:a};a.canvas&&(a.canvas.Tg=d);zc[c]=d;("undefined"===typeof b.Cg||b.Cg)&&Lc(d);return c}
function Lc(a){a||(a=V);if(!a.Fg){a.Fg=!0;var b=a.Mf;rc(b);sc(b);tc(b);b.Xg=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.bh=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");b.lf=b.getExtension("EXT_disjoint_timer_query");b.fh=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}var Mc={},Hc,V,Nc=[];
function Oc(a,b,c,d){for(var e=0;e<a;e++){var f=W[c](),k=f&&Ic(d);f?(f.name=k,d[k]=f):U(1282);v[b+4*e>>2]=k}}function Pc(a,b,c,d,e,f,k,l){b=N[b];if(a=W[a](b,c))d=l&&E(a.name,A,l,d),e&&(v[e>>2]=d),f&&(v[f>>2]=a.size),k&&(v[k>>2]=a.type)}function Qc(a,b){F[a>>2]=b;F[a+4>>2]=(b-F[a>>2])/4294967296}
function Rc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&U(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=W.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>V.version){U(1282);return}d=2*(W.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>V.version){U(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=W.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":U(1280);return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:U(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:v[b+4*a>>2]=e[a];break;case 2:z[b+4*a>>2]=e[a];break;case 4:q[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){U(1280);
h("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:U(1280);h("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Qc(b,d);break;case 0:v[b>>2]=d;break;case 2:z[b>>2]=d;break;case 4:q[b>>0]=d?1:0}}else U(1281)}
function Sc(a,b,c,d){if(c){b=W.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:U(1280);return}else if(b instanceof WebGLBuffer)a=b.name|0;else{U(1280);return}break;default:U(1280);return}switch(d){case 1:Qc(c,a);break;case 0:v[c>>2]=a;break;case 2:z[c>>2]=a;break;case 4:q[c>>0]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else U(1281)}
function Tc(a){var b=Ga(a)+1,c=Ca(b);E(a,A,c,b);return c}function Uc(a,b,c,d){if(c)if(a=W.getUniform(N[a],P[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:z[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b]}else U(1281)}
function Vc(a,b,c,d){if(c)if(a=W.getVertexAttrib(a,b),34975==b)v[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:z[c>>2]=a;break;case 5:v[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b];break;case 5:v[c+4*b>>2]=Math.fround(a[b])}else U(1281)}function Wc(a){a-=5120;return 0==a?q:1==a?A:2==a?va:4==a?v:6==a?z:5==a||28922==a||28520==a||30779==a||30782==a?F:Ka}
function Xc(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function Yc(a,b,c,d,e){a=Wc(a);var f=Xc(a),k=Gc;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<f)+k-1&-k)>>f)}var Zc=[],$c=[];function ad(a){try{a()}catch(b){if(!(b instanceof pa)&&"unwind"!==b)throw b&&"object"===typeof b&&b.stack&&h("exception thrown: "+[b,b.stack]),b;}}var bd=!1,cd=null,dd=0,ed=null,fd=0,gd=0,hd=0,id=0,jd=[],kd={},ld,md,nd,od=!1,pd=!1,qd=[];
function kc(){function a(){pd=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!rd){rd=!0;try{sd=!0}catch(c){sd=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}td="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:sd?null:console.log("warning: no BlobBuilder");
ud="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;g.ng||"undefined"!==typeof ud||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.ng=!0);g.preloadPlugins.push({canHandle:function(c){return!g.ng&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var k=null;if(sd)try{k=new Blob([c],{type:vd(d)}),k.size!==c.length&&(k=new Blob([(new Uint8Array(c)).buffer],{type:vd(d)}))}catch(r){ra("Blob constructor present but fails: "+
r+"; falling back to blob builder")}k||(k=new td,k.append((new Uint8Array(c)).buffer),k=k.getBlob());var l=ud.createObjectURL(k),m=new Image;m.onload=function(){assert(m.complete,"Image "+d+" could not be decoded");var r=document.createElement("canvas");r.width=m.width;r.height=m.height;r.getContext("2d").drawImage(m,0,0);g.preloadedImages[d]=r;ud.revokeObjectURL(l);e&&e(c)};m.onerror=function(){console.log("Image "+l+" could not be decoded");f&&f()};m.src=l}});g.preloadPlugins.push({canHandle:function(c){return!g.gh&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function k(u){m||(m=!0,g.preloadedAudios[d]=u,e&&e(c))}function l(){m||(m=!0,g.preloadedAudios[d]=new Audio,f&&f())}var m=!1;if(sd){try{var r=new Blob([c],{type:vd(d)})}catch(u){return l()}r=ud.createObjectURL(r);var t=new Audio;t.addEventListener("canplaythrough",function(){k(t)},!1);t.onerror=function(){if(!m){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var u="",w=0,y=0,
B=0;B<c.length;B++)for(w=w<<8|c[B],y+=8;6<=y;){var D=w>>y-6&63;y-=6;u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[D]}2==y?(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&3)<<4],u+="=="):4==y&&(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&15)<<2],u+="=");t.src="data:audio/x-"+d.substr(-3)+";base64,"+u;k(t)}};t.src=r;wd(function(){k(t)})}else return l()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&
b.addEventListener("click",function(c){!pd&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function xd(a,b,c,d){if(b&&g.sf&&a==g.canvas)return g.sf;var e;if(b){var f={antialias:!1,alpha:!1,lg:"undefined"!==typeof WebGL2RenderingContext?2:1};if(d)for(var k in d)f[k]=d[k];if("undefined"!==typeof Mc&&(e=Jc(a,f)))var l=zc[e].Mf}else l=a.getContext("2d");if(!l)return null;c&&(b||assert("undefined"===typeof W,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.sf=l,b&&(V=zc[e],g.sf=W=V&&V.Mf),g.ih=b,qd.forEach(function(m){m()}),kc());return l}
var yd=!1,zd=void 0,Ad=void 0;
function Bd(a,b){function c(){od=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Cd,zd&&d.requestPointerLock(),od=!0,Ad?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=F[SDL.screen>>2]|8388608),Dd(g.canvas),Ed()):Dd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Ad?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=F[SDL.screen>>2]&
-8388609),Dd(g.canvas),Ed()):Dd(d));if(g.onFullScreen)g.onFullScreen(od);if(g.onFullscreen)g.onFullscreen(od)}zd=a;Ad=b;"undefined"===typeof zd&&(zd=!0);"undefined"===typeof Ad&&(Ad=!1);var d=g.canvas;yd||(yd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Cd(){if(!od)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Fd=0;function Gd(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Fd)Fd=b+1E3/60;else for(;b+2>=Fd;)Fd+=1E3/60;setTimeout(a,Math.max(Fd-b,0))}}function wd(a){setTimeout(function(){ad(a)},1E4)}
function vd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Hd=0,Id=0,Jd=0,Kd=0;
function Ld(a){if(pd)"mousemove"!=a.type&&"mozMovementX"in a?Jd=Kd=0:(Jd=a.movementX||a.mozMovementX||a.webkitMovementX||0,Kd=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Hd=SDL.dh+Jd,Id=SDL.eh+Kd):(Hd+=Jd,Id+=Kd);else{var b=g.canvas.getBoundingClientRect(),c=g.canvas.width,d=g.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(f+b.top),e*=c/b.width,a*=d/b.height,Jd=e-Hd,Kd=a-Id,Hd=e,Id=a)}}function lc(a,b,c){var d="al "+a;la(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Va(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ua(d)}var Md=[];function Ed(){var a=g.canvas;Md.forEach(function(b){b(a.width,a.height)})}function Nd(a,b,c){Dd(g.canvas,a,b);c||Ed()}
function Dd(a,b,c){b&&c?(a.Sg=b,a.Eg=c):(b=a.Sg,c=a.Eg);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Ad?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var rd,sd,td,ud;
function Od(a,b){gd=a;hd=b;if(ed)if(bd||(bd=!0),0==a)cd=function(){var d=Math.max(0,md+b-qc())|0;setTimeout(nd,d)};else if(1==a)cd=function(){Gd(nd)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}cd=function(){setImmediate(nd)}}}
function Pd(a,b,c,d,e){function f(){if(k<dd){if(!noExitRuntime)try{Qd(Aa)}catch(l){if(!(l instanceof pa))throw l;}return!1}return!0}assert(!ed,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");ed=a;fd=d;var k=dd;bd=!1;nd=function(){if(!za)if(0<jd.length){var l=Date.now(),m=jd.shift();m.Dg(m.Af);if(ld){var r=ld,t=0==r%1?r-1:Math.floor(r);ld=m.Wg?t:(8*r+(t+.5))/
9}console.log('main loop blocker "'+m.name+'" took '+(Date.now()-l)+" ms");g.setStatus&&(l=g.statusMessage||"Please wait...",m=ld,r=kd.Yg,m?m<r?g.setStatus(l+" ("+(r-m)+"/"+r+")"):g.setStatus(l):g.setStatus(""));f()&&setTimeout(nd,0)}else f()&&(id=id+1|0,1==gd&&1<hd&&0!=id%hd?cd():(0==gd&&(md=qc()),za||g.preMainLoop&&!1===g.preMainLoop()||(ad(a),g.postMainLoop&&g.postMainLoop()),f()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.Og&&SDL.audio.Og(),cd())))};e||(b&&0<b?Od(0,1E3/b):Od(1,1),cd());if(c)throw"unwind";
}var Rd={};function Sd(){if(!Td){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Rd)a[b]=Rd[b];var c=[];for(b in a)c.push(b+"="+a[b]);Td=c}return Td}var Td;
function Ud(a,b,c,d){this.id=a;this.y=this.x=0;this.Vf=!1;this.sg=this.rg=0;this.width=b;this.height=c;this.qg=b;this.pg=c;this.title=d;this.attributes=Vd;this.buttons=0;this.keys=[];this.Rf=[];this.cg=this.Ef=this.Sf=this.Kf=this.Bf=this.Cf=this.If=this.Df=this.ug=this.vg=this.title=null}function Wd(a){return 0>=a||!X?null:X[a-1]}
var Xd=null,Y=null,X=null,Vd=null,Yd={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function Zd(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function $d(){var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function ae(a){Y&&Y.cg&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||G.get(Y.cg)(Y.id,a))}
function be(a,b){if(Y){var c=Zd(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.Rf[a]=b;Y.Ef&&(d&&(b=2),G.get(Y.Ef)(Y.id,c,a,b,$d()))}}}function ce(){de()}function ee(){de()}function fe(a){be(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function ge(a){be(a.keyCode,0)}function he(){if(Y)for(var a=0;a<Y.Rf.length;++a)Y.Rf[a]&&be(a,0)}function ie(a){Y&&(Ld(a),a.target==g.canvas&&Y.Cf&&G.get(Y.Cf)(Y.id,Hd,Id))}function je(a){Y&&a.target==g.canvas&&Y.Bf&&G.get(Y.Bf)(Y.id,1)}
function ke(a){Y&&a.target==g.canvas&&Y.Bf&&G.get(Y.Bf)(Y.id,0)}function le(a,b){if(Y&&(Ld(a),a.target==g.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Y.buttons&=~(1<<c);Y.If&&G.get(Y.If)(Y.id,c,b,$d())}}function me(a){Y&&le(a,1)}function ne(a){Y&&le(a,0)}
function pe(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":switch(a.deltaMode){case 0:break;case 1:break;case 2:break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}if(Y&&Y.Kf&&a.target==g.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;G.get(Y.Kf)(Y.id,b,c);a.preventDefault()}}var qe={},re=null,se=null;
function de(){if(id!==se||!id){re=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;se=id;for(var a=0;a<re.length;++a){var b=re[a];if(b){qe[a]||(console.log("glfw joystick connected:",a),qe[a]={id:Ba(qb(b.id)),Vg:b.buttons.length,Ug:b.axes.length,buttons:Ba(Array(b.buttons.length)),axes:Ba(Array(4*b.axes.length))});for(var c=qe[a],d=0;d<b.buttons.length;++d)ua(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)ua(c.axes+4*d,
b.axes[d],"float")}else qe[a]&&(console.log("glfw joystick disconnected",a),te(qe[a].id),te(qe[a].buttons),te(qe[a].axes),delete qe[a])}}}
function ue(a){function b(l){var m="/.glfw_dropped_files/"+l.name.replace(/\//g,"_"),r=new FileReader;r.onloadend=function(u){if(2!=r.readyState)++f,console.log("failed to read dropped file: "+l.name+": "+r.error);else{var w=new Uint8Array(u.target.result);var y=y||{};y.flags=y.flags||577;u=Wb(m,y.flags,y.mode);if("string"===typeof w){var B=new Uint8Array(Ga(w)+1);w=E(w,B,0,B.length);$b(u,B,0,w,void 0,y.zg)}else if(ArrayBuffer.isView(w))$b(u,w,0,w.byteLength,void 0,y.zg);else throw Error("Unsupported data type");
Yb(u);if(++f===e){G.get(Y.Sf)(Y.id,e,c);for(y=0;y<d.length;++y)te(d[y]);te(c)}}};r.readAsArrayBuffer(l);var t=Ba(qb(m));d.push(t);ua(c+4*k,t,"i8*")}if(Y&&Y.Sf&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Ba(Array(4*a.dataTransfer.files.length)),d=[],e=a.dataTransfer.files.length,f=0;dc("/",".glfw_dropped_files");for(var k=0;k<e;++k)b(a.dataTransfer.files[k]);return!1}}function ve(a){if(Y&&Y.Sf)return a.preventDefault(),!1}var we=[];
function Jb(a,b,c,d){a||(a=this);this.parent=a;this.pf=a.pf;this.yf=null;this.id=Ab++;this.name=b;this.mode=c;this.df={};this.cf={};this.rdev=d}Object.defineProperties(Jb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Ig:{get:function(){return 16384===(this.mode&61440)}},Hg:{get:function(){return 8192===(this.mode&61440)}}});ac();
Bb=Array(4096);Qb(J,"/");K("/tmp");K("/home");K("/home/web_user");(function(){K("/dev");ob(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Sb("/dev/null",259);nb(1280,rb);nb(1536,sb);Sb("/dev/tty",1280);Sb("/dev/tty1",1536);var a=kb();L("/dev","random",a);L("/dev","urandom",a);K("/dev/shm");K("/dev/shm/tmp")})();
(function(){K("/proc");var a=K("/proc/self");K("/proc/self/fd");Qb({pf:function(){var b=ub(a,"fd",16895,73);b.df={lookup:function(c,d){var e=zb[+d];if(!e)throw new I(8);c={parent:null,pf:{mg:"fake"},df:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();g.FS_createPath=dc;g.FS_createDataFile=fc;g.FS_createPreloadedFile=jc;g.FS_createLazyFile=ic;g.FS_createDevice=L;g.FS_unlink=Ub;for(var W,Z=0;32>Z;++Z)Nc.push(Array(Z));var xe=new Float32Array(288);
for(Z=0;288>Z;++Z)Zc[Z]=xe.subarray(0,Z+1);var ye=new Int32Array(288);for(Z=0;288>Z;++Z)$c[Z]=ye.subarray(0,Z+1);g.requestFullscreen=function(a,b){Bd(a,b)};g.requestAnimationFrame=function(a){Gd(a)};g.setCanvasSize=function(a,b,c){Nd(a,b,c)};g.pauseMainLoop=function(){cd=null;dd++};g.resumeMainLoop=function(){dd++;var a=gd,b=hd,c=ed;ed=null;Pd(c,0,!1,fd,!0);Od(a,b);cd()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};
g.createContext=function(a,b,c,d){return xd(a,b,c,d)};function qb(a,b){var c=Array(Ga(a)+1);a=E(a,c,0,c.length);b&&(c.length=a);return c}
var Ce={a:function(a,b,c,d){p("Assertion failed: "+C(a)+", at: "+[b?C(b):"unknown filename",c,d?C(d):"unknown function"])},l:function(a,b,c){nc=c;try{var d=pc(a);switch(b){case 0:var e=oc();return 0>e?-28:Wb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=oc(),d.flags|=e,0;case 12:return e=oc(),va[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return v[ze()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof M&&f instanceof I||
p(f),-f.jf}},Pa:function(a,b,c){nc=c;try{var d=pc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=oc();return v[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=oc();if(!d.cf.Gg)throw new I(59);return d.cf.Gg(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:p("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof M&&f instanceof I||p(f),
-f.jf}},Ua:function(a,b,c,d,e,f){try{a:{f<<=12;var k=!1;if(0!==(d&16)&&0!==a%16384)var l=-28;else{if(0!==(d&32)){var m=Ae(16384,b);if(!m){l=-48;break a}Be(m,0,b);k=!0}else{var r=zb[e];if(!r){l=-8;break a}var t=f;if(0!==(c&2)&&0===(d&2)&&2!==(r.flags&2097155))throw new I(2);if(1===(r.flags&2097155))throw new I(2);if(!r.cf.Hf)throw new I(43);var u=r.cf.Hf(r,a,b,t,c,d);m=u.Ng;k=u.Nf}mc[m]={Kg:m,Jg:b,Nf:k,fd:e,Mg:c,flags:d,offset:f};l=m}}return l}catch(w){return"undefined"!==typeof M&&w instanceof I||
p(w),-w.jf}},Ta:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=mc[a];if(d&&b===d.Jg){var e=zb[d.fd];if(e&&d.Mg&2){var f=d.flags,k=d.offset,l=A.slice(a,a+b);e&&e.cf.Jf&&e.cf.Jf(e,l,k,b,f)}mc[a]=null;d.Nf&&te(d.Kg)}c=0}return c}catch(m){return"undefined"!==typeof M&&m instanceof I||p(m),-m.jf}},Qa:function(a,b,c){nc=c;try{var d=C(a),e=c?oc():0;return Wb(d,b,e).fd}catch(f){return"undefined"!==typeof M&&f instanceof I||p(f),-f.jf}},Ka:function(){p()},h:function(a,b){if(0===a)a=Date.now();
else if(1===a||4===a)a=qc();else return v[ze()>>2]=28,-1;v[b>>2]=a/1E3|0;v[b+4>>2]=a%1E3*1E6|0;return 0},b:function(a,b,c){we.length=0;var d;for(c>>=2;d=A[b++];)(d=105>d)&&c&1&&c++,we.push(d?xa[c++>>1]:v[c]),++c;return cb[a].apply(null,we)},sa:function(a){W.activeTexture(a)},ra:function(a,b){W.attachShader(N[a],Q[b])},Jc:function(a,b){W.beginQuery(a,Ac[b])},ab:function(a,b){W.lf.beginQueryEXT(a,S[b])},pc:function(a){W.beginTransformFeedback(a)},qa:function(a,b,c){W.bindAttribLocation(N[a],b,C(c))},
pa:function(a,b){35051==a?W.Qf=b:35052==a&&(W.mf=b);W.bindBuffer(a,vc[b])},mc:function(a,b,c){W.bindBufferBase(a,b,vc[c])},nc:function(a,b,c,d,e){W.bindBufferRange(a,b,vc[c],d,e)},oa:function(a,b){W.bindFramebuffer(a,wc[b])},ma:function(a,b){W.bindRenderbuffer(a,xc[b])},sb:function(a,b){W.bindSampler(a,T[b])},la:function(a,b){W.bindTexture(a,yc[b])},jb:function(a,b){W.bindTransformFeedback(a,Bc[b])},uc:function(a){W.bindVertexArray(R[a])},Ba:function(a){W.bindVertexArray(R[a])},ka:function(a,b,c,
d){W.blendColor(a,b,c,d)},ja:function(a){W.blendEquation(a)},ia:function(a,b){W.blendEquationSeparate(a,b)},ha:function(a,b){W.blendFunc(a,b)},ga:function(a,b,c,d){W.blendFuncSeparate(a,b,c,d)},xc:function(a,b,c,d,e,f,k,l,m,r){W.blitFramebuffer(a,b,c,d,e,f,k,l,m,r)},fa:function(a,b,c,d){2<=V.version?c?W.bufferData(a,A,d,c,b):W.bufferData(a,b,d):W.bufferData(a,c?A.subarray(c,c+b):b,d)},ea:function(a,b,c,d){2<=V.version?W.bufferSubData(a,b,A,d,c):W.bufferSubData(a,b,A.subarray(d,d+c))},da:function(a){return W.checkFramebufferStatus(a)},
ba:function(a){W.clear(a)},Rb:function(a,b,c,d){W.clearBufferfi(a,b,c,d)},Sb:function(a,b,c){W.clearBufferfv(a,b,z,c>>2)},Ub:function(a,b,c){W.clearBufferiv(a,b,v,c>>2)},Tb:function(a,b,c){W.clearBufferuiv(a,b,F,c>>2)},aa:function(a,b,c,d){W.clearColor(a,b,c,d)},$:function(a){W.clearDepth(a)},_:function(a){W.clearStencil(a)},Cb:function(a,b,c,d){return W.clientWaitSync(Cc[a],b,(c>>>0)+4294967296*d)},Z:function(a,b,c,d){W.colorMask(!!a,!!b,!!c,!!d)},Y:function(a){W.compileShader(Q[a])},X:function(a,
b,c,d,e,f,k,l){2<=V.version?W.mf?W.compressedTexImage2D(a,b,c,d,e,f,k,l):W.compressedTexImage2D(a,b,c,d,e,f,A,l,k):W.compressedTexImage2D(a,b,c,d,e,f,l?A.subarray(l,l+k):null)},Oc:function(a,b,c,d,e,f,k,l,m){W.mf?W.compressedTexImage3D(a,b,c,d,e,f,k,l,m):W.compressedTexImage3D(a,b,c,d,e,f,k,A,m,l)},W:function(a,b,c,d,e,f,k,l,m){2<=V.version?W.mf?W.compressedTexSubImage2D(a,b,c,d,e,f,k,l,m):W.compressedTexSubImage2D(a,b,c,d,e,f,k,A,m,l):W.compressedTexSubImage2D(a,b,c,d,e,f,k,m?A.subarray(m,m+l):null)},
Nc:function(a,b,c,d,e,f,k,l,m,r,t){W.mf?W.compressedTexSubImage3D(a,b,c,d,e,f,k,l,m,r,t):W.compressedTexSubImage3D(a,b,c,d,e,f,k,l,m,A,t,r)},Pb:function(a,b,c,d,e){W.copyBufferSubData(a,b,c,d,e)},V:function(a,b,c,d,e,f,k,l){W.copyTexImage2D(a,b,c,d,e,f,k,l)},U:function(a,b,c,d,e,f,k,l){W.copyTexSubImage2D(a,b,c,d,e,f,k,l)},Qc:function(a,b,c,d,e,f,k,l,m){W.copyTexSubImage3D(a,b,c,d,e,f,k,l,m)},S:function(){var a=Ic(N),b=W.createProgram();b.name=a;N[a]=b;return a},R:function(a){var b=Ic(Q);Q[b]=W.createShader(a);
return b},Q:function(a){W.cullFace(a)},P:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=vc[d];e&&(W.deleteBuffer(e),e.name=0,vc[d]=null,d==W.Qf&&(W.Qf=0),d==W.mf&&(W.mf=0))}},O:function(a,b){for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=wc[d];e&&(W.deleteFramebuffer(e),e.name=0,wc[d]=null)}},N:function(a){if(a){var b=N[a];b?(W.deleteProgram(b),b.name=0,N[a]=null,Dc[a]=null):U(1281)}},Lc:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Ac[d];e&&(W.deleteQuery(e),Ac[d]=null)}},wb:function(a,
b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=S[d];e&&(W.lf.deleteQueryEXT(e),S[d]=null)}},M:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=xc[d];e&&(W.deleteRenderbuffer(e),e.name=0,xc[d]=null)}},ub:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=T[d];e&&(W.deleteSampler(e),e.name=0,T[d]=null)}},L:function(a){if(a){var b=Q[a];b?(W.deleteShader(b),Q[a]=null):U(1281)}},Db:function(a){if(a){var b=Cc[a];b?(W.deleteSync(b),b.name=0,Cc[a]=null):U(1281)}},K:function(a,b){for(var c=0;c<a;c++){var d=
v[b+4*c>>2],e=yc[d];e&&(W.deleteTexture(e),e.name=0,yc[d]=null)}},ib:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Bc[d];e&&(W.deleteTransformFeedback(e),e.name=0,Bc[d]=null)}},tc:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2];W.deleteVertexArray(R[d]);R[d]=null}},Aa:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2];W.deleteVertexArray(R[d]);R[d]=null}},J:function(a){W.depthFunc(a)},H:function(a){W.depthMask(!!a)},G:function(a,b){W.depthRange(a,b)},F:function(a,b){W.detachShader(N[a],
Q[b])},E:function(a){W.disable(a)},D:function(a){W.disableVertexAttribArray(a)},C:function(a,b,c){W.drawArrays(a,b,c)},Ib:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},va:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},Zc:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},$c:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},Va:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},Fc:function(a,b){for(var c=Nc[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];W.drawBuffers(c)},Vc:function(a,b){for(var c=Nc[a],d=0;d<
a;d++)c[d]=v[b+4*d>>2];W.drawBuffers(c)},wa:function(a,b){for(var c=Nc[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];W.drawBuffers(c)},B:function(a,b,c,d){W.drawElements(a,b,c,d)},Gb:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},ua:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},Wc:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},Xc:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},Yc:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},Tc:function(a,b,c,d,e,f){W.drawElements(a,
d,e,f)},A:function(a){W.enable(a)},z:function(a){W.enableVertexAttribArray(a)},Ic:function(a){W.endQuery(a)},Ra:function(a){W.lf.endQueryEXT(a)},oc:function(){W.endTransformFeedback()},Fb:function(a,b){return(a=W.fenceSync(a,b))?(b=Ic(Cc),a.name=b,Cc[b]=a,b):0},y:function(){W.finish()},w:function(){W.flush()},v:function(a,b,c,d){W.framebufferRenderbuffer(a,b,c,xc[d])},u:function(a,b,c,d,e){W.framebufferTexture2D(a,b,c,yc[d],e)},vc:function(a,b,c,d,e){W.framebufferTextureLayer(a,b,yc[c],d,e)},t:function(a){W.frontFace(a)},
s:function(a,b){Oc(a,b,"createBuffer",vc)},q:function(a,b){Oc(a,b,"createFramebuffer",wc)},Mc:function(a,b){Oc(a,b,"createQuery",Ac)},Hb:function(a,b){for(var c=0;c<a;c++){var d=W.lf.createQueryEXT();if(!d){for(U(1282);c<a;)v[b+4*c++>>2]=0;break}var e=Ic(S);d.name=e;S[e]=d;v[b+4*c>>2]=e}},p:function(a,b){Oc(a,b,"createRenderbuffer",xc)},vb:function(a,b){Oc(a,b,"createSampler",T)},o:function(a,b){Oc(a,b,"createTexture",yc)},hb:function(a,b){Oc(a,b,"createTransformFeedback",Bc)},sc:function(a,b){Oc(a,
b,"createVertexArray",R)},za:function(a,b){Oc(a,b,"createVertexArray",R)},r:function(a){W.generateMipmap(a)},n:function(a,b,c,d,e,f,k){Pc("getActiveAttrib",a,b,c,d,e,f,k)},Qe:function(a,b,c,d,e,f,k){Pc("getActiveUniform",a,b,c,d,e,f,k)},Kb:function(a,b,c,d,e){a=N[a];if(a=W.getActiveUniformBlockName(a,b))e&&0<c?(c=E(a,A,e,c),d&&(v[d>>2]=c)):d&&(v[d>>2]=0)},Lb:function(a,b,c,d){if(d)if(a=N[a],35393==c)c=W.getActiveUniformBlockName(a,b),v[d>>2]=c.length+1;else{if(a=W.getActiveUniformBlockParameter(a,
b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)v[d+4*c>>2]=a[c];else v[d>>2]=a}else U(1281)},Nb:function(a,b,c,d,e){if(e)if(0<b&&0==c)U(1281);else{a=N[a];for(var f=[],k=0;k<b;k++)f.push(v[c+4*k>>2]);if(a=W.getActiveUniforms(a,f,d))for(b=a.length,k=0;k<b;k++)v[e+4*k>>2]=a[k]}else U(1281)},Pe:function(a,b,c,d){a=W.getAttachedShaders(N[a]);var e=a.length;e>b&&(e=b);v[c>>2]=e;for(b=0;b<e;++b)v[d+4*b>>2]=Q.indexOf(a[b])},Oe:function(a,b){return W.getAttribLocation(N[a],C(b))},Ne:function(a,b){Rc(a,b,
4)},xb:function(a,b,c){c?Qc(c,W.getBufferParameter(a,b)):U(1281)},Me:function(a,b,c){c?v[c>>2]=W.getBufferParameter(a,b):U(1281)},Le:function(){var a=W.getError()||Hc;Hc=0;return a},Ke:function(a,b){Rc(a,b,2)},bc:function(a,b){return W.getFragDataLocation(N[a],C(b))},Je:function(a,b,c,d){a=W.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;v[d>>2]=a},yb:function(a,b,c){Sc(a,b,c,1)},Ab:function(a,b){Rc(a,b,1)},qc:function(a,b,c){Sc(a,
b,c,0)},Ie:function(a,b){Rc(a,b,0)},Xa:function(a,b,c,d,e){if(0>d)U(1281);else if(e){if(a=W.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)v[e+b>>2]=a[b]}else U(1281)},db:function(){U(1282)},Fe:function(a,b,c,d){a=W.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,A,d,b):0;c&&(v[c>>2]=b)},He:function(a,b,c){if(c)if(a>=uc)U(1281);else{var d=Dc[a];if(d)if(35716==b)a=W.getProgramInfoLog(N[a]),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==
b)v[c>>2]=d.Yf;else if(35722==b){if(-1==d.wf){a=N[a];var e=W.getProgramParameter(a,35721);for(b=d.wf=0;b<e;++b)d.wf=Math.max(d.wf,W.getActiveAttrib(a,b).name.length+1)}v[c>>2]=d.wf}else if(35381==b){if(-1==d.xf)for(a=N[a],e=W.getProgramParameter(a,35382),b=d.xf=0;b<e;++b)d.xf=Math.max(d.xf,W.getActiveUniformBlockName(a,b).length+1);v[c>>2]=d.xf}else v[c>>2]=W.getProgramParameter(N[a],b);else U(1282)}else U(1281)},Da:function(a,b,c){if(c){a=W.lf.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?
d=a?1:0:d=a;Qc(c,d)}else U(1281)},Fa:function(a,b,c){if(c){a=W.lf.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else U(1281)},Ca:function(a,b,c){if(c){a=W.lf.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Qc(c,d)}else U(1281)},Gc:function(a,b,c){if(c){a=W.getQueryParameter(Ac[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else U(1281)},Ea:function(a,b,c){if(c){a=W.lf.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else U(1281)},
Hc:function(a,b,c){c?v[c>>2]=W.getQuery(a,b):U(1281)},Ga:function(a,b,c){c?v[c>>2]=W.lf.getQueryEXT(a,b):U(1281)},Ee:function(a,b,c){c?v[c>>2]=W.getRenderbufferParameter(a,b):U(1281)},mb:function(a,b,c){c?(a=T[a],z[c>>2]=W.getSamplerParameter(a,b)):U(1281)},nb:function(a,b,c){c?(a=T[a],v[c>>2]=W.getSamplerParameter(a,b)):U(1281)},Ce:function(a,b,c,d){a=W.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,A,d,b):0;c&&(v[c>>2]=b)},Be:function(a,b,c,d){a=W.getShaderPrecisionFormat(a,
b);v[c>>2]=a.rangeMin;v[c+4>>2]=a.rangeMax;v[d>>2]=a.precision},Ae:function(a,b,c,d){if(a=W.getShaderSource(Q[a]))b=0<b&&d?E(a,A,d,b):0,c&&(v[c>>2]=b)},De:function(a,b,c){c?35716==b?(a=W.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=W.getShaderSource(Q[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=W.getShaderParameter(Q[a],b):U(1281)},ze:function(a){if(Ec[a])return Ec[a];switch(a){case 7939:var b=W.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+
d}));b=Tc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=W.getParameter(a))||U(1280);b=Tc(b);break;case 7938:b=W.getParameter(7938);b=2<=V.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Tc(b);break;case 35724:b=W.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Tc(b);break;default:return U(1280),0}return Ec[a]=b},Qb:function(a,b){if(2>V.version)return U(1282),
0;var c=Fc[a];if(c)return 0>b||b>=c.length?(U(1281),0):c[b];switch(a){case 7939:return c=W.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return Tc(d)}),c=Fc[a]=c,0>b||b>=c.length?(U(1281),0):c[b];default:return U(1280),0}},zb:function(a,b,c,d,e){0>c?U(1281):e?(a=W.getSyncParameter(Cc[a],b),null!==a&&(v[e>>2]=a,d&&(v[d>>2]=1))):U(1281)},ye:function(a,b,c){c?z[c>>2]=W.getTexParameter(a,b):U(1281)},xe:function(a,b,c){c?v[c>>2]=W.getTexParameter(a,b):U(1281)},
kc:function(a,b,c,d,e,f,k){a=N[a];if(a=W.getTransformFeedbackVarying(a,b))k&&0<c?(c=E(a.name,A,k,c),d&&(v[d>>2]=c)):d&&(v[d>>2]=0),e&&(v[e>>2]=a.size),f&&(v[f>>2]=a.type)},Mb:function(a,b){return W.getUniformBlockIndex(N[a],C(b))},Ob:function(a,b,c,d){if(d)if(0<b&&(0==c||0==d))U(1281);else{a=N[a];for(var e=[],f=0;f<b;f++)e.push(C(v[c+4*f>>2]));if(a=W.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)v[d+4*f>>2]=a[f]}else U(1281)},te:function(a,b){b=C(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");
c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Dc[a]&&Dc[a].tg[b])&&0<=c&&c<a[0]?a[1]+c:-1},we:function(a,b,c){Uc(a,b,c,2)},ue:function(a,b,c){Uc(a,b,c,0)},cc:function(a,b,c){Uc(a,b,c,0)},ic:function(a,b,c){Vc(a,b,c,0)},hc:function(a,b,c){Vc(a,b,c,0)},qe:function(a,b,c){c?v[c>>2]=W.getVertexAttribOffset(a,b):U(1281)},se:function(a,b,c){Vc(a,b,c,2)},re:function(a,b,c){Vc(a,b,c,5)},pe:function(a,b){W.hint(a,b)},$a:function(a,b,c){for(var d=Nc[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];W.invalidateFramebuffer(a,
d)},_a:function(a,b,c,d,e,f,k){for(var l=Nc[b],m=0;m<b;m++)l[m]=v[c+4*m>>2];W.invalidateSubFramebuffer(a,l,d,e,f,k)},oe:function(a){return(a=vc[a])?W.isBuffer(a):0},ne:function(a){return W.isEnabled(a)},me:function(a){return(a=wc[a])?W.isFramebuffer(a):0},le:function(a){return(a=N[a])?W.isProgram(a):0},Kc:function(a){return(a=Ac[a])?W.isQuery(a):0},lb:function(a){return(a=S[a])?W.lf.isQueryEXT(a):0},je:function(a){return(a=xc[a])?W.isRenderbuffer(a):0},tb:function(a){return(a=T[a])?W.isSampler(a):
0},ie:function(a){return(a=Q[a])?W.isShader(a):0},Eb:function(a){return W.isSync(Cc[a])},he:function(a){return(a=yc[a])?W.isTexture(a):0},gb:function(a){return W.isTransformFeedback(Bc[a])},rc:function(a){return(a=R[a])?W.isVertexArray(a):0},xa:function(a){return(a=R[a])?W.isVertexArray(a):0},ge:function(a){W.lineWidth(a)},fe:function(a){W.linkProgram(N[a]);var b=N[a];a=Dc[a]={tg:{},Yf:0,wf:-1,xf:-1};for(var c=a.tg,d=W.getProgramParameter(b,35718),e=0;e<d;++e){var f=W.getActiveUniform(b,e),k=f.name;
a.Yf=Math.max(a.Yf,k.length+1);"]"==k.slice(-1)&&(k=k.slice(0,k.lastIndexOf("[")));var l=W.getUniformLocation(b,k);if(l){var m=Ic(P);c[k]=[f.size,m];P[m]=l;for(var r=1;r<f.size;++r)l=W.getUniformLocation(b,k+"["+r+"]"),m=Ic(P),P[m]=l}}},fb:function(){W.pauseTransformFeedback()},ee:function(a,b){3317==a&&(Gc=b);W.pixelStorei(a,b)},de:function(a,b){W.polygonOffset(a,b)},cb:function(){U(1280)},bb:function(){U(1280)},Ja:function(a,b){W.lf.queryCounterEXT(S[a],b)},Uc:function(a){W.readBuffer(a)},ce:function(a,
b,c,d,e,f,k){if(2<=V.version)if(W.Qf)W.readPixels(a,b,c,d,e,f,k);else{var l=Wc(f);W.readPixels(a,b,c,d,e,f,l,k>>Xc(l))}else(k=Yc(f,e,c,d,k))?W.readPixels(a,b,c,d,e,f,k):U(1280)},be:function(){},ae:function(a,b,c,d){W.renderbufferStorage(a,b,c,d)},wc:function(a,b,c,d,e){W.renderbufferStorageMultisample(a,b,c,d,e)},eb:function(){W.resumeTransformFeedback()},_d:function(a,b){W.sampleCoverage(a,!!b)},pb:function(a,b,c){W.samplerParameterf(T[a],b,c)},ob:function(a,b,c){W.samplerParameterf(T[a],b,z[c>>
2])},rb:function(a,b,c){W.samplerParameteri(T[a],b,c)},qb:function(a,b,c){W.samplerParameteri(T[a],b,v[c>>2])},Zd:function(a,b,c,d){W.scissor(a,b,c,d)},Yd:function(){U(1280)},Xd:function(a,b,c,d){for(var e="",f=0;f<b;++f){var k=d?v[d+4*f>>2]:-1;e+=C(v[c+4*f>>2],0>k?void 0:k)}W.shaderSource(Q[a],e)},Wd:function(a,b,c){W.stencilFunc(a,b,c)},Vd:function(a,b,c,d){W.stencilFuncSeparate(a,b,c,d)},Ud:function(a){W.stencilMask(a)},Td:function(a,b){W.stencilMaskSeparate(a,b)},Sd:function(a,b,c){W.stencilOp(a,
b,c)},Rd:function(a,b,c,d){W.stencilOpSeparate(a,b,c,d)},Pd:function(a,b,c,d,e,f,k,l,m){if(2<=V.version)if(W.mf)W.texImage2D(a,b,c,d,e,f,k,l,m);else if(m){var r=Wc(l);W.texImage2D(a,b,c,d,e,f,k,l,r,m>>Xc(r))}else W.texImage2D(a,b,c,d,e,f,k,l,null);else W.texImage2D(a,b,c,d,e,f,k,l,m?Yc(l,k,d,e,m):null)},Sc:function(a,b,c,d,e,f,k,l,m,r){if(W.mf)W.texImage3D(a,b,c,d,e,f,k,l,m,r);else if(r){var t=Wc(m);W.texImage3D(a,b,c,d,e,f,k,l,m,t,r>>Xc(t))}else W.texImage3D(a,b,c,d,e,f,k,l,m,null)},Od:function(a,
b,c){W.texParameterf(a,b,c)},Nd:function(a,b,c){W.texParameterf(a,b,z[c>>2])},Md:function(a,b,c){W.texParameteri(a,b,c)},Ld:function(a,b,c){W.texParameteri(a,b,v[c>>2])},Za:function(a,b,c,d,e){W.texStorage2D(a,b,c,d,e)},Ya:function(a,b,c,d,e,f){W.texStorage3D(a,b,c,d,e,f)},Kd:function(a,b,c,d,e,f,k,l,m){if(2<=V.version)if(W.mf)W.texSubImage2D(a,b,c,d,e,f,k,l,m);else if(m){var r=Wc(l);W.texSubImage2D(a,b,c,d,e,f,k,l,r,m>>Xc(r))}else W.texSubImage2D(a,b,c,d,e,f,k,l,null);else r=null,m&&(r=Yc(l,k,e,
f,m)),W.texSubImage2D(a,b,c,d,e,f,k,l,r)},Rc:function(a,b,c,d,e,f,k,l,m,r,t){if(W.mf)W.texSubImage3D(a,b,c,d,e,f,k,l,m,r,t);else if(t){var u=Wc(r);W.texSubImage3D(a,b,c,d,e,f,k,l,m,r,u,t>>Xc(u))}else W.texSubImage3D(a,b,c,d,e,f,k,l,m,r,null)},lc:function(a,b,c,d){a=N[a];for(var e=[],f=0;f<b;f++)e.push(C(v[c+4*f>>2]));W.transformFeedbackVaryings(a,e,d)},Jd:function(a,b){W.uniform1f(P[a],b)},Id:function(a,b,c){if(2<=V.version)W.uniform1fv(P[a],z,c>>2,b);else{if(288>=b)for(var d=Zc[b-1],e=0;e<b;++e)d[e]=
z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);W.uniform1fv(P[a],d)}},Hd:function(a,b){W.uniform1i(P[a],b)},Gd:function(a,b,c){if(2<=V.version)W.uniform1iv(P[a],v,c>>2,b);else{if(288>=b)for(var d=$c[b-1],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);W.uniform1iv(P[a],d)}},ac:function(a,b){W.uniform1ui(P[a],b)},Yb:function(a,b,c){W.uniform1uiv(P[a],F,c>>2,b)},Ed:function(a,b,c){W.uniform2f(P[a],b,c)},Dd:function(a,b,c){if(2<=V.version)W.uniform2fv(P[a],z,c>>2,2*b);else{if(144>=b)for(var d=
Zc[2*b-1],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);W.uniform2fv(P[a],d)}},Cd:function(a,b,c){W.uniform2i(P[a],b,c)},Bd:function(a,b,c){if(2<=V.version)W.uniform2iv(P[a],v,c>>2,2*b);else{if(144>=b)for(var d=$c[2*b-1],e=0;e<2*b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2];else d=v.subarray(c>>2,c+8*b>>2);W.uniform2iv(P[a],d)}},$b:function(a,b,c){W.uniform2ui(P[a],b,c)},Xb:function(a,b,c){W.uniform2uiv(P[a],F,c>>2,2*b)},Ad:function(a,b,c,d){W.uniform3f(P[a],
b,c,d)},zd:function(a,b,c){if(2<=V.version)W.uniform3fv(P[a],z,c>>2,3*b);else{if(96>=b)for(var d=Zc[3*b-1],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);W.uniform3fv(P[a],d)}},yd:function(a,b,c,d){W.uniform3i(P[a],b,c,d)},xd:function(a,b,c){if(2<=V.version)W.uniform3iv(P[a],v,c>>2,3*b);else{if(96>=b)for(var d=$c[3*b-1],e=0;e<3*b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2];else d=v.subarray(c>>2,c+12*b>>2);W.uniform3iv(P[a],
d)}},_b:function(a,b,c,d){W.uniform3ui(P[a],b,c,d)},Wb:function(a,b,c){W.uniform3uiv(P[a],F,c>>2,3*b)},wd:function(a,b,c,d,e){W.uniform4f(P[a],b,c,d,e)},vd:function(a,b,c){if(2<=V.version)W.uniform4fv(P[a],z,c>>2,4*b);else{if(72>=b){var d=Zc[4*b-1],e=z;c>>=2;for(var f=0;f<4*b;f+=4){var k=c+f;d[f]=e[k];d[f+1]=e[k+1];d[f+2]=e[k+2];d[f+3]=e[k+3]}}else d=z.subarray(c>>2,c+16*b>>2);W.uniform4fv(P[a],d)}},td:function(a,b,c,d,e){W.uniform4i(P[a],b,c,d,e)},sd:function(a,b,c){if(2<=V.version)W.uniform4iv(P[a],
v,c>>2,4*b);else{if(72>=b)for(var d=$c[4*b-1],e=0;e<4*b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2];else d=v.subarray(c>>2,c+16*b>>2);W.uniform4iv(P[a],d)}},Zb:function(a,b,c,d,e){W.uniform4ui(P[a],b,c,d,e)},Vb:function(a,b,c){W.uniform4uiv(P[a],F,c>>2,4*b)},Jb:function(a,b,c){a=N[a];W.uniformBlockBinding(a,b,c)},rd:function(a,b,c,d){if(2<=V.version)W.uniformMatrix2fv(P[a],!!c,z,d>>2,4*b);else{if(72>=b)for(var e=Zc[4*b-1],f=0;f<4*b;f+=4)e[f]=z[d+4*f>>
2],e[f+1]=z[d+(4*f+4)>>2],e[f+2]=z[d+(4*f+8)>>2],e[f+3]=z[d+(4*f+12)>>2];else e=z.subarray(d>>2,d+16*b>>2);W.uniformMatrix2fv(P[a],!!c,e)}},Dc:function(a,b,c,d){W.uniformMatrix2x3fv(P[a],!!c,z,d>>2,6*b)},Bc:function(a,b,c,d){W.uniformMatrix2x4fv(P[a],!!c,z,d>>2,8*b)},qd:function(a,b,c,d){if(2<=V.version)W.uniformMatrix3fv(P[a],!!c,z,d>>2,9*b);else{if(32>=b)for(var e=Zc[9*b-1],f=0;f<9*b;f+=9)e[f]=z[d+4*f>>2],e[f+1]=z[d+(4*f+4)>>2],e[f+2]=z[d+(4*f+8)>>2],e[f+3]=z[d+(4*f+12)>>2],e[f+4]=z[d+(4*f+16)>>
2],e[f+5]=z[d+(4*f+20)>>2],e[f+6]=z[d+(4*f+24)>>2],e[f+7]=z[d+(4*f+28)>>2],e[f+8]=z[d+(4*f+32)>>2];else e=z.subarray(d>>2,d+36*b>>2);W.uniformMatrix3fv(P[a],!!c,e)}},Cc:function(a,b,c,d){W.uniformMatrix3x2fv(P[a],!!c,z,d>>2,6*b)},zc:function(a,b,c,d){W.uniformMatrix3x4fv(P[a],!!c,z,d>>2,12*b)},pd:function(a,b,c,d){if(2<=V.version)W.uniformMatrix4fv(P[a],!!c,z,d>>2,16*b);else{if(18>=b){var e=Zc[16*b-1],f=z;d>>=2;for(var k=0;k<16*b;k+=16){var l=d+k;e[k]=f[l];e[k+1]=f[l+1];e[k+2]=f[l+2];e[k+3]=f[l+3];
e[k+4]=f[l+4];e[k+5]=f[l+5];e[k+6]=f[l+6];e[k+7]=f[l+7];e[k+8]=f[l+8];e[k+9]=f[l+9];e[k+10]=f[l+10];e[k+11]=f[l+11];e[k+12]=f[l+12];e[k+13]=f[l+13];e[k+14]=f[l+14];e[k+15]=f[l+15]}}else e=z.subarray(d>>2,d+64*b>>2);W.uniformMatrix4fv(P[a],!!c,e)}},Ac:function(a,b,c,d){W.uniformMatrix4x2fv(P[a],!!c,z,d>>2,8*b)},yc:function(a,b,c,d){W.uniformMatrix4x3fv(P[a],!!c,z,d>>2,12*b)},od:function(a){W.useProgram(N[a])},nd:function(a){W.validateProgram(N[a])},md:function(a,b){W.vertexAttrib1f(a,b)},ld:function(a,
b){W.vertexAttrib1f(a,z[b>>2])},kd:function(a,b,c){W.vertexAttrib2f(a,b,c)},id:function(a,b){W.vertexAttrib2f(a,z[b>>2],z[b+4>>2])},hd:function(a,b,c,d){W.vertexAttrib3f(a,b,c,d)},gd:function(a,b){W.vertexAttrib3f(a,z[b>>2],z[b+4>>2],z[b+8>>2])},fd:function(a,b,c,d,e){W.vertexAttrib4f(a,b,c,d,e)},ed:function(a,b){W.vertexAttrib4f(a,z[b>>2],z[b+4>>2],z[b+8>>2],z[b+12>>2])},kb:function(a,b){W.vertexAttribDivisor(a,b)},ta:function(a,b){W.vertexAttribDivisor(a,b)},ad:function(a,b){W.vertexAttribDivisor(a,
b)},bd:function(a,b){W.vertexAttribDivisor(a,b)},Wa:function(a,b){W.vertexAttribDivisor(a,b)},gc:function(a,b,c,d,e){W.vertexAttribI4i(a,b,c,d,e)},ec:function(a,b){W.vertexAttribI4i(a,v[b>>2],v[b+4>>2],v[b+8>>2],v[b+12>>2])},fc:function(a,b,c,d,e){W.vertexAttribI4ui(a,b,c,d,e)},dc:function(a,b){W.vertexAttribI4ui(a,F[b>>2],F[b+4>>2],F[b+8>>2],F[b+12>>2])},jc:function(a,b,c,d,e){W.vertexAttribIPointer(a,b,c,d,e)},dd:function(a,b,c,d,e,f){W.vertexAttribPointer(a,b,c,!!d,e,f)},cd:function(a,b,c,d){W.viewport(a,
b,c,d)},Bb:function(a,b,c,d){W.waitSync(Cc[a],b,(c>>>0)+4294967296*d)},e:function(){return 0},Ia:function(a,b,c){A.copyWithin(a,b,b+c)},c:function(a){var b=A.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ya.grow(Math.min(2147483648,d)-Ja.byteLength+65535>>>16);La();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},ya:function(a,b,c){a=G.get(a);Pd(a,b,c)},d:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";
},Na:function(a){for(var b=qc();qc()-b<a;);},La:function(a,b){try{var c=0;Sd().forEach(function(d,e){var f=b+c;e=v[a+4*e>>2]=f;for(f=0;f<d.length;++f)q[e++>>0]=d.charCodeAt(f);q[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof M&&d instanceof I||p(d),d.jf}},Ma:function(a,b){try{var c=Sd();v[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});v[b>>2]=d;return 0}catch(e){return"undefined"!==typeof M&&e instanceof I||p(e),e.jf}},j:function(a){Qd(a)},m:function(a){try{var b=
pc(a);Yb(b);return 0}catch(c){return"undefined"!==typeof M&&c instanceof I||p(c),c.jf}},Oa:function(a,b,c,d){try{a:{for(var e=pc(a),f=a=0;f<c;f++){var k=v[b+(8*f+4)>>2],l=e,m=v[b+8*f>>2],r=k,t=void 0,u=q;if(0>r||0>t)throw new I(28);if(null===l.fd)throw new I(8);if(1===(l.flags&2097155))throw new I(8);if(16384===(l.node.mode&61440))throw new I(31);if(!l.cf.read)throw new I(28);var w="undefined"!==typeof t;if(!w)t=l.position;else if(!l.seekable)throw new I(70);var y=l.cf.read(l,u,m,r,t);w||(l.position+=
y);var B=y;if(0>B){var D=-1;break a}a+=B;if(B<k)break}D=a}v[d>>2]=D;return 0}catch(H){return"undefined"!==typeof M&&H instanceof I||p(H),H.jf}},Ha:function(a,b,c,d,e){try{var f=pc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Zb(f,a,d);wa=[f.position>>>0,(x=f.position,1<=+Math.abs(x)?0<x?(Math.min(+Math.floor(x/4294967296),4294967295)|0)>>>0:~~+Math.ceil((x-+(~~x>>>0))/4294967296)>>>0:0)];v[e>>2]=wa[0];v[e+4>>2]=wa[1];f.Wf&&0===a&&0===d&&(f.Wf=null);return 0}catch(k){return"undefined"!==
typeof M&&k instanceof I||p(k),k.jf}},Sa:function(a,b,c,d){try{a:{for(var e=pc(a),f=a=0;f<c;f++){var k=$b(e,q,v[b+8*f>>2],v[b+(8*f+4)>>2],void 0);if(0>k){var l=-1;break a}a+=k}l=a}v[d>>2]=l;return 0}catch(m){return"undefined"!==typeof M&&m instanceof I||p(m),m.jf}},i:function(a){var b=Date.now();v[a>>2]=b/1E3|0;v[a+4>>2]=b%1E3*1E3|0;return 0},Ge:function(a,b,c,d){var e;for(e=0;e<X.length&&null!==X[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var f=e+1;if(0>=a||
0>=b)f=0;else{d?Bd():Nd(a,b);for(e=0;e<X.length&&null==X[e];e++);d=0<Vd[139265];e==X.length&&(d?g.sf=xd(g.canvas,!0,!0,{antialias:1<Vd[135181],depth:0<Vd[135173],stencil:0<Vd[135174],alpha:0<Vd[135172]}):kc());!g.sf&&d?f=0:(a=new Ud(f,a,b,c),f-1==X.length?X.push(a):X[f-1]=a,Y=a,f=a.id)}return f},x:function(){Vd=Yd},Pc:function(a){a:{if(a=Wd(a)){a.ug&&G.get(a.ug)(a.id);X[a.id-1]=null;Y.id==a.id&&(Y=null);for(a=0;a<X.length;a++)if(null!==X[a]){a=void 0;break a}g.sf=void 0}a=void 0}return a},jd:function(a,
b,c){ua(b,Hd,"double");ua(c,Id,"double")},_c:function(a,b,c){var d=0,e=0;if(a=Wd(a))d=a.width,e=a.height;b&&ua(b,d,"i32");c&&ua(c,e,"i32")},I:function(){if(X)return 1;qc();Vd=Yd;X=[];Y=null;window.addEventListener("gamepadconnected",ce,!0);window.addEventListener("gamepaddisconnected",ee,!0);window.addEventListener("keydown",fe,!0);window.addEventListener("keypress",ae,!0);window.addEventListener("keyup",ge,!0);window.addEventListener("blur",he,!0);g.canvas.addEventListener("touchmove",ie,!0);g.canvas.addEventListener("touchstart",
me,!0);g.canvas.addEventListener("touchcancel",ne,!0);g.canvas.addEventListener("touchend",ne,!0);g.canvas.addEventListener("mousemove",ie,!0);g.canvas.addEventListener("mousedown",me,!0);g.canvas.addEventListener("mouseup",ne,!0);g.canvas.addEventListener("wheel",pe,!0);g.canvas.addEventListener("mousewheel",pe,!0);g.canvas.addEventListener("mouseenter",je,!0);g.canvas.addEventListener("mouseleave",ke,!0);g.canvas.addEventListener("drop",ue,!0);g.canvas.addEventListener("dragover",ve,!0);Md.push(function(a,
b){if(Y){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Y.rg=Y.x,Y.sg=Y.y,Y.qg=Y.width,Y.pg=Y.height,Y.x=Y.y=0,Y.width=screen.width,Y.height=screen.height,Y.Vf=!0):1==Y.Vf?(Y.x=Y.rg,Y.y=Y.sg,Y.width=Y.qg,Y.height=Y.pg,Y.Vf=!1):Y.width!=a||Y.height!=b?(Y.width=a,Y.height=b):c=!1;c&&(Nd(Y.width,Y.height,!0),Y&&Y.vg&&G.get(Y.vg)(Y.id,Y.width,Y.height),Y&&Y.Df&&G.get(Y.Df)(Y.id,Y.width,Y.height))}});return 1},ve:function(){},na:function(){},$d:function(a,
b){if(a=Wd(a)){var c=a.Cf;a.Cf=b;b=c}else b=null;return b},T:function(a){var b=Xd;Xd=a;return b},ke:function(a,b){a=Wd(a);if(!a)return null;var c=a.Df;a.Df=b;return c},Qd:function(a,b){if(a=Wd(a)){var c=a.Ef;a.Ef=b;b=c}else b=null;return b},ud:function(a,b){if(a=Wd(a)){var c=a.If;a.If=b;b=c}else b=null;return b},Fd:function(a,b){if(a=Wd(a)){var c=a.Kf;a.Kf=b;b=c}else b=null;return b},ca:function(){},Ec:function(){window.removeEventListener("gamepadconnected",ce,!0);window.removeEventListener("gamepaddisconnected",
ee,!0);window.removeEventListener("keydown",fe,!0);window.removeEventListener("keypress",ae,!0);window.removeEventListener("keyup",ge,!0);window.removeEventListener("blur",he,!0);g.canvas.removeEventListener("touchmove",ie,!0);g.canvas.removeEventListener("touchstart",me,!0);g.canvas.removeEventListener("touchcancel",ne,!0);g.canvas.removeEventListener("touchend",ne,!0);g.canvas.removeEventListener("mousemove",ie,!0);g.canvas.removeEventListener("mousedown",me,!0);g.canvas.removeEventListener("mouseup",
ne,!0);g.canvas.removeEventListener("wheel",pe,!0);g.canvas.removeEventListener("mousewheel",pe,!0);g.canvas.removeEventListener("mouseenter",je,!0);g.canvas.removeEventListener("mouseleave",ke,!0);g.canvas.removeEventListener("drop",ue,!0);g.canvas.removeEventListener("dragover",ve,!0);g.canvas.width=g.canvas.height=1;Y=X=null},g:function(a,b){Vd[a]=b},k:function(){},f:function(){return 0}};
(function(){function a(e){g.asm=e.exports;ya=g.asm.Re;La();G=g.asm._e;Na.unshift(g.asm.Se);Va("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return ab().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){h("failed to asynchronously prepare wasm: "+f);p(f)})}var d={a:Ce};Ua("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return h("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ta||"function"!==
typeof WebAssembly.instantiateStreaming||Ya()||Wa("file://")||"function"!==typeof fetch?c(b):fetch(Xa,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){h("wasm streaming compile failed: "+f);h("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.Se).apply(null,arguments)};
var te=g._free=function(){return(te=g._free=g.asm.Te).apply(null,arguments)},Ca=g._malloc=function(){return(Ca=g._malloc=g.asm.Ue).apply(null,arguments)};g._main=function(){return(g._main=g.asm.Ve).apply(null,arguments)};
var ze=g.___errno_location=function(){return(ze=g.___errno_location=g.asm.We).apply(null,arguments)},Be=g._memset=function(){return(Be=g._memset=g.asm.Xe).apply(null,arguments)},Ia=g.stackAlloc=function(){return(Ia=g.stackAlloc=g.asm.Ye).apply(null,arguments)},Ae=g._memalign=function(){return(Ae=g._memalign=g.asm.Ze).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.$e).apply(null,arguments)};g.dynCall_ji=function(){return(g.dynCall_ji=g.asm.af).apply(null,arguments)};
g.addRunDependency=Ua;g.removeRunDependency=Va;g.FS_createPath=dc;g.FS_createDataFile=fc;g.FS_createPreloadedFile=jc;g.FS_createLazyFile=ic;g.FS_createDevice=L;g.FS_unlink=Ub;var De;function pa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ta=function Ee(){De||Fe();De||(Ta=Ee)};
function Fe(a){function b(){if(!De&&(De=!0,g.calledRun=!0,!za)){g.noFSInit||bc||(bc=!0,ac(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?L("/dev","stdin",g.stdin):Tb("/dev/tty","/dev/stdin"),g.stdout?L("/dev","stdout",null,g.stdout):Tb("/dev/tty","/dev/stdout"),g.stderr?L("/dev","stderr",null,g.stderr):Tb("/dev/tty1","/dev/stderr"),Wb("/dev/stdin",0),Wb("/dev/stdout",1),Wb("/dev/stderr",1));fb(Na);Cb=!1;fb(Oa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(Ge){var c=a,d=g._main;
c=c||[];var e=c.length+1,f=Ia(4*(e+1));v[f>>2]=Ha(da);for(var k=1;k<e;k++)v[(f>>2)+k]=Ha(c[k-1]);v[(f>>2)+e]=0;try{var l=d(e,f);Qd(l,!0)}catch(m){m instanceof pa||"unwind"==m||((c=m)&&"object"===typeof m&&m.stack&&(c=[m,m.stack]),h("exception thrown: "+c),ea(1,m))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=g.postRun.shift(),Pa.unshift(c);fb(Pa)}}a=a||ca;if(!(0<Ra)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Qa();
fb(Ma);0<Ra||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=Fe;function Qd(a,b){Aa=a;if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(g.onExit)g.onExit(a);za=!0}ea(a,new pa(a))}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Ge=!0;g.noInitialRun&&(Ge=!1);Fe();
