
var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa={},ba;for(ba in g)g.hasOwnProperty(ba)&&(aa[ba]=g[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;ha="function"===typeof importScripts;ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ja=!fa&&!ia&&!ha;var k="",ka,la,ma,na,oa;
if(ia)k=ha?require("path").dirname(k)+"/":__dirname+"/",ka=function(a,b){na||(na=require("fs"));oa||(oa=require("path"));a=oa.normalize(a);return na.readFileSync(a,b?null:"utf8")},ma=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof pa))throw a;}),process.on("unhandledRejection",
m),ea=function(a){process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ja)"undefined"!=typeof read&&(ka=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||ha)ha?k=self.location.href:"undefined"!==typeof document&&document.currentScript&&(k=document.currentScript.src),k=0!==k.indexOf("blob:")?k.substr(0,k.lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
la=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var qa=g.print||console.log.bind(console),p=g.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(g[ba]=aa[ba]);aa=null;g.arguments&&(ca=g.arguments);g.thisProgram&&(da=g.thisProgram);g.quit&&(ea=g.quit);function ra(a){sa||(sa={});sa[a]||(sa[a]=1,p(a))}var sa,ta;g.wasmBinary&&(ta=g.wasmBinary);
var noExitRuntime;g.noExitRuntime&&(noExitRuntime=g.noExitRuntime);"object"!==typeof WebAssembly&&m("no native wasm support detected");
function q(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":r[a>>0]=b;break;case "i8":r[a>>0]=b;break;case "i16":ua[a>>1]=b;break;case "i32":u[a>>2]=b;break;case "i64":va=[b>>>0,(v=b,1<=+Math.abs(v)?0<v?(Math.min(+Math.floor(v/4294967296),4294967295)|0)>>>0:~~+Math.ceil((v-+(~~v>>>0))/4294967296)>>>0:0)];u[a>>2]=va[0];u[a+4>>2]=va[1];break;case "float":w[a>>2]=b;break;case "double":wa[a>>3]=b;break;default:m("invalid type for setValue: "+c)}}var xa,ya=!1;
function assert(a,b){a||m("Assertion failed: "+b)}function za(a){var b=Aa(a.length);a.subarray||a.slice?y.set(a,b):y.set(new Uint8Array(a),b);return b}var Ba="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ca(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ba)return Ba.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function A(a,b){return a?Ca(y,a,b):""}
function B(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function Da(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ea(a){var b=Da(a)+1,c=Fa(b);B(a,r,c,b);return c}var Ga,r,y,ua,Ha,u,D,w,wa;
function Ia(){var a=xa.buffer;Ga=a;g.HEAP8=r=new Int8Array(a);g.HEAP16=ua=new Int16Array(a);g.HEAP32=u=new Int32Array(a);g.HEAPU8=y=new Uint8Array(a);g.HEAPU16=Ha=new Uint16Array(a);g.HEAPU32=D=new Uint32Array(a);g.HEAPF32=w=new Float32Array(a);g.HEAPF64=wa=new Float64Array(a)}var F,Ja=[],Ka=[],La=[],Ma=[];Ka.push({cg:function(){Na()}});function Oa(){var a=g.preRun.shift();Ja.unshift(a)}var Pa=0,Qa=null,Ra=null;g.preloadedImages={};g.preloadedAudios={};
function m(a){if(g.onAbort)g.onAbort(a);p(a);ya=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Sa(a){var b=G;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ta(){return Sa("data:application/octet-stream;base64,")}var G="index.wasm";if(!Ta()){var Ua=G;G=g.locateFile?g.locateFile(Ua,k):k+Ua}
function Va(){var a=G;try{if(a==G&&ta)return new Uint8Array(ta);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}catch(b){m(b)}}
function Wa(){if(!ta&&(fa||ha)){if("function"===typeof fetch&&!Sa("file://"))return fetch(G,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+G+"'";return a.arrayBuffer()}).catch(function(){return Va()});if(la)return new Promise(function(a,b){la(G,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Va()})}
var v,va,Ya={17767:function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?1:0},17933:function(){return"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?1:0},18159:function(a){var b=g.SDL2;if(a){void 0!==b.capture.xf&&clearTimeout(b.capture.xf);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.jf&&(b.capture.jf.onaudioprocess=function(){},b.capture.jf.disconnect(),b.capture.jf=void 0);void 0!==b.capture.Df&&(b.capture.Df.disconnect(),b.capture.Df=void 0);void 0!==b.capture.Kf&&(b.capture.Kf=void 0);b.capture=void 0}else void 0!=b.audio.jf&&(b.audio.jf.disconnect(),b.audio.jf=void 0),b.audio=void 0;void 0!==b.hf&&void 0===b.audio&&void 0===b.capture&&(b.hf.close(),b.hf=void 0)},19331:function(a){"undefined"===typeof g.SDL2&&(g.SDL2={});var b=g.SDL2;
a?b.capture={}:b.audio={};b.hf||("undefined"!==typeof AudioContext?b.hf=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.hf=new webkitAudioContext),b.hf&&Xa(b.hf));return void 0===b.hf?-1:0},19884:function(){return g.SDL2.hf.sampleRate},19954:function(a,b,c,d){function e(){}function f(l){void 0!==h.capture.xf&&(clearTimeout(h.capture.xf),h.capture.xf=void 0);h.capture.Df=h.hf.createMediaStreamSource(l);h.capture.jf=h.hf.createScriptProcessor(b,a,1);h.capture.jf.onaudioprocess=function(n){void 0!==
h&&void 0!==h.capture&&(n.outputBuffer.getChannelData(0).fill(0),h.capture.Nf=n.inputBuffer,n=[d],F.get(c).apply(null,n))};h.capture.Df.connect(h.capture.jf);h.capture.jf.connect(h.hf.destination);h.capture.stream=l}var h=g.SDL2;h.capture.Kf=h.hf.createBuffer(a,b,h.hf.sampleRate);h.capture.Kf.getChannelData(0).fill(0);h.capture.xf=setTimeout(function(){h.capture.Nf=h.capture.Kf;var l=[d];F.get(c).apply(null,l)},b/h.hf.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?
navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},21606:function(a,b,c,d){var e=g.SDL2;e.audio.jf=e.hf.createScriptProcessor(b,0,a);e.audio.jf.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Zf=f.outputBuffer,f=[d],F.get(c).apply(null,f))};e.audio.jf.connect(e.hf.destination)},22016:function(a,b){for(var c=g.SDL2,d=c.audio.Zf.numberOfChannels,e=0;e<d;++e){var f=c.audio.Zf.getChannelData(e);
if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var h=0;h<b;++h)f[h]=w[a+(h*d+e<<2)>>2]}},22496:function(a,b){for(var c=g.SDL2,d=c.capture.Nf.numberOfChannels,e=0;e<d;++e){var f=c.capture.Nf.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var h=0;h<b;++h)q(a+4*h,f[h],"float");else for(h=0;h<b;++h)q(a+4*
(h*d+e),f[h],"float")}}};function Za(a,b,c){a.addEventListener(b,c,{once:!0})}function Xa(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&Za(d,c,function(){"suspended"===a.state&&a.resume()})})})}function $a(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.cg;"number"===typeof c?void 0===b.yf?F.get(c)():F.get(c)(b.yf):c(void 0===b.yf?null:b.yf)}}}
function ab(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function bb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=ab(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function cb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function db(a){if("/"===a)return"/";a=bb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function eb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){m("randomDevice")}}
function fb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=ab(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var gb=[];function hb(a,b){gb[a]={input:[],output:[],uf:b};ib(a,jb)}
var jb={open:function(a){var b=gb[a.node.rdev];if(!b)throw new H(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.uf.flush(a.tty)},flush:function(a){a.tty.uf.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.uf.dg)throw new H(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.uf.dg(a.tty)}catch(l){throw new H(29);}if(void 0===h&&0===e)throw new H(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.uf.Uf)throw new H(60);
try{for(var e=0;e<d;e++)a.tty.uf.Uf(a.tty,b[c+e])}catch(f){throw new H(29);}d&&(a.node.timestamp=Date.now());return e}},lb={dg:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.qg?Buffer.qg(256):new Buffer(256),d=0;try{d=na.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=kb(b,!0)}return a.input.shift()},Uf:function(a,b){null===b||10===b?(qa(Ca(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(qa(Ca(a.output,0)),a.output=[])}},mb={Uf:function(a,b){null===b||10===b?(p(Ca(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(p(Ca(a.output,0)),a.output=[])}},I={nf:null,qf:function(){return I.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(63);I.nf||(I.nf={dir:{node:{rf:I.ff.rf,pf:I.ff.pf,lookup:I.ff.lookup,Ef:I.ff.Ef,rename:I.ff.rename,unlink:I.ff.unlink,rmdir:I.ff.rmdir,readdir:I.ff.readdir,symlink:I.ff.symlink},stream:{sf:I.ef.sf}},file:{node:{rf:I.ff.rf,pf:I.ff.pf},stream:{sf:I.ef.sf,read:I.ef.read,write:I.ef.write,Wf:I.ef.Wf,Ff:I.ef.Ff,If:I.ef.If}},link:{node:{rf:I.ff.rf,pf:I.ff.pf,readlink:I.ff.readlink},stream:{}},Yf:{node:{rf:I.ff.rf,
pf:I.ff.pf},stream:nb}});c=ob(a,b,c,d);16384===(c.mode&61440)?(c.ff=I.nf.dir.node,c.ef=I.nf.dir.stream,c.df={}):32768===(c.mode&61440)?(c.ff=I.nf.file.node,c.ef=I.nf.file.stream,c.gf=0,c.df=null):40960===(c.mode&61440)?(c.ff=I.nf.link.node,c.ef=I.nf.link.stream):8192===(c.mode&61440)&&(c.ff=I.nf.Yf.node,c.ef=I.nf.Yf.stream);c.timestamp=Date.now();a&&(a.df[b]=c,a.timestamp=c.timestamp);return c},Mg:function(a){if(a.df&&a.df.subarray){for(var b=[],c=0;c<a.gf;++c)b.push(a.df[c]);return b}return a.df},
Ng:function(a){return a.df?a.df.subarray?a.df.subarray(0,a.gf):new Uint8Array(a.df):new Uint8Array(0)},$f:function(a,b){var c=a.df?a.df.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.df,a.df=new Uint8Array(b),0<a.gf&&a.df.set(c.subarray(0,a.gf),0))},Cg:function(a,b){if(a.gf!=b)if(0==b)a.df=null,a.gf=0;else{if(!a.df||a.df.subarray){var c=a.df;a.df=new Uint8Array(b);c&&a.df.set(c.subarray(0,Math.min(b,a.gf)))}else if(a.df||(a.df=[]),a.df.length>b)a.df.length=b;
else for(;a.df.length<b;)a.df.push(0);a.gf=b}},ff:{rf:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.gf:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.og=4096;b.blocks=Math.ceil(b.size/b.og);return b},pf:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&
(a.timestamp=b.timestamp);void 0!==b.size&&I.Cg(a,b.size)},lookup:function(){throw pb[44];},Ef:function(a,b,c,d){return I.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=qb(b,c)}catch(f){}if(d)for(var e in d.df)throw new H(55);}delete a.parent.df[a.name];a.parent.timestamp=Date.now();a.name=c;b.df[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.df[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=qb(a,b),d;for(d in c.df)throw new H(55);
delete a.df[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.df)a.df.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new H(28);return a.link}},ef:{read:function(a,b,c,d,e){var f=a.node.df;if(e>=a.node.gf)return 0;a=Math.min(a.node.gf-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===
r.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.df||a.df.subarray)){if(f)return a.df=b.subarray(c,c+d),a.gf=d;if(0===a.gf&&0===e)return a.df=b.slice(c,c+d),a.gf=d;if(e+d<=a.gf)return a.df.set(b.subarray(c,c+d),e),d}I.$f(a,e+d);if(a.df.subarray&&b.subarray)a.df.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.df[e+f]=b[c+f];a.gf=Math.max(a.gf,e+d);return d},sf:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.gf);if(0>b)throw new H(28);
return b},Wf:function(a,b,c){I.$f(a.node,b+c);a.node.gf=Math.max(a.node.gf,b+c)},Ff:function(a,b,c,d,e,f){if(0!==b)throw new H(28);if(32768!==(a.node.mode&61440))throw new H(43);a=a.node.df;if(f&2||a.buffer!==Ga){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=Aa(f);c<f;)r[b+c++]=0;c=b;if(!c)throw new H(48);r.set(a,c)}else d=!1,c=a.byteOffset;return{Ag:c,Mf:d}},If:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(43);
if(e&2)return 0;I.ef.write(a,b,0,d,c,!1);return 0}}},rb=null,sb={},tb=[],ub=1,vb=null,wb=!0,xb={},H=null,pb={};
function yb(a,b){a=fb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={bg:!0,Vf:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Vf)throw new H(32);a=ab(a.split("/").filter(function(h){return!!h}),!1);var e=rb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=qb(e,a[d]);c=bb(c+"/"+a[d]);e.Gf&&(!f||f&&b.bg)&&(e=e.Gf.root);if(!f||b.ag)for(f=0;40960===(e.mode&61440);)if(e=zb(c),c=fb(cb(c),e),e=yb(c,{Vf:b.Vf}).node,40<f++)throw new H(32);}return{path:c,node:e}}
function Ab(a){for(var b;;){if(a===a.parent)return a=a.qf.fg,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Bb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%vb.length}function qb(a,b){var c;if(c=(c=Cb(a,"x"))?c:a.ff.lookup?0:2)throw new H(c,a);for(c=vb[Bb(a.id,b)];c;c=c.yg){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ff.lookup(a,b)}
function ob(a,b,c,d){a=new Db(a,b,c,d);b=Bb(a.parent.id,a.name);a.yg=vb[b];return vb[b]=a}var Eb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Gb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Cb(a,b){if(wb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Hb(a,b){try{return qb(a,b),20}catch(c){}return Cb(a,"wx")}
function Ib(a){var b=4096;for(a=a||0;a<=b;a++)if(!tb[a])return a;throw new H(33);}function Jb(a,b){Kb||(Kb=function(){},Kb.prototype={});var c=new Kb,d;for(d in a)c[d]=a[d];a=c;b=Ib(b);a.fd=b;return tb[b]=a}var nb={open:function(a){a.ef=sb[a.node.rdev].ef;a.ef.open&&a.ef.open(a)},sf:function(){throw new H(70);}};function ib(a,b){sb[a]={ef:b}}
function Lb(a,b){var c="/"===b,d=!b;if(c&&rb)throw new H(10);if(!c&&!d){var e=yb(b,{bg:!1});b=e.path;e=e.node;if(e.Gf)throw new H(10);if(16384!==(e.mode&61440))throw new H(54);}b={type:a,Ug:{},fg:b,xg:[]};a=a.qf(b);a.qf=b;b.root=a;c?rb=a:e&&(e.Gf=b,e.qf&&e.qf.xg.push(b))}function Mb(a,b,c){var d=yb(a,{parent:!0}).node;a=db(a);if(!a||"."===a||".."===a)throw new H(28);var e=Hb(d,a);if(e)throw new H(e);if(!d.ff.Ef)throw new H(63);return d.ff.Ef(d,a,b,c)}function J(a){return Mb(a,16895,0)}
function Nb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Mb(a,b|8192,c)}function Ob(a,b){if(!fb(a))throw new H(44);var c=yb(b,{parent:!0}).node;if(!c)throw new H(44);b=db(b);var d=Hb(c,b);if(d)throw new H(d);if(!c.ff.symlink)throw new H(63);c.ff.symlink(c,b,a)}function zb(a){a=yb(a).node;if(!a)throw new H(44);if(!a.ff.readlink)throw new H(28);return fb(Ab(a.parent),a.ff.readlink(a))}
function Pb(a,b,c,d){if(""===a)throw new H(44);if("string"===typeof b){var e=Eb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=bb(a);try{f=yb(a,{ag:!(b&131072)}).node}catch(l){}}e=!1;if(b&64)if(f){if(b&128)throw new H(20);}else f=Mb(a,c,0),e=!0;if(!f)throw new H(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new H(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==Gb(b)||b&512)?31:Cb(f,Gb(b)):44))throw new H(c);if(b&512){c=f;var h;"string"===typeof c?h=yb(c,{ag:!0}).node:h=c;if(!h.ff.pf)throw new H(63);if(16384===(h.mode&61440))throw new H(31);if(32768!==(h.mode&61440))throw new H(28);if(c=Cb(h,"w"))throw new H(c);h.ff.pf(h,{size:0,timestamp:Date.now()})}b&=-131713;d=Jb({node:f,path:Ab(f),flags:b,seekable:!0,position:0,ef:f.ef,Eg:[],error:!1},d);d.ef.open&&d.ef.open(d);!g.logReadFiles||b&1||(Qb||(Qb={}),a in Qb||(Qb[a]=1,p("FS.trackingDelegate error on read file: "+
a)));try{xb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),xb.onOpenFile(a,f))}catch(l){p("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+l.message)}return d}function Rb(a){if(null===a.fd)throw new H(8);a.Sf&&(a.Sf=null);try{a.ef.close&&a.ef.close(a)}catch(b){throw b;}finally{tb[a.fd]=null}a.fd=null}
function Sb(a,b,c){if(null===a.fd)throw new H(8);if(!a.seekable||!a.ef.sf)throw new H(70);if(0!=c&&1!=c&&2!=c)throw new H(28);a.position=a.ef.sf(a,b,c);a.Eg=[]}
function Tb(a,b,c,d,e){var f=void 0;if(0>d||0>f)throw new H(28);if(null===a.fd)throw new H(8);if(0===(a.flags&2097155))throw new H(8);if(16384===(a.node.mode&61440))throw new H(31);if(!a.ef.write)throw new H(28);a.seekable&&a.flags&1024&&Sb(a,0,2);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new H(70);b=a.ef.write(a,b,c,d,f,e);h||(a.position+=b);try{if(a.path&&xb.onWriteToFile)xb.onWriteToFile(a.path)}catch(l){p("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
l.message)}return b}function Ub(){H||(H=function(a,b){this.node=b;this.Dg=function(c){this.lf=c};this.Dg(a);this.message="FS error"},H.prototype=Error(),H.prototype.constructor=H,[44].forEach(function(a){pb[a]=new H(a);pb[a].stack="<generic error, no stack>"}))}var Vb;function Wb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function Xb(){var a="/";a="string"===typeof a?a:Ab(a);for(var b=[".glfw_dropped_files"].reverse();b.length;){var c=b.pop();if(c){a=bb(a+"/"+c);try{J(a)}catch(d){}}}}
function Yb(a,b,c){a=bb("/dev/"+a);var d=Wb(!!b,!!c);Zb||(Zb=64);var e=Zb++<<8|0;ib(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,h,l,n){for(var t=0,x=0;x<n;x++){try{var z=b()}catch(C){throw new H(29);}if(void 0===z&&0===t)throw new H(6);if(null===z||void 0===z)break;t++;h[l+x]=z}t&&(f.node.timestamp=Date.now());return t},write:function(f,h,l,n){for(var t=0;t<n;t++)try{c(h[l+t])}catch(x){throw new H(29);}n&&(f.node.timestamp=Date.now());return t}});
Nb(a,d,e)}var Zb,K={},Kb,Qb,$b={},ac=void 0;function bc(){ac+=4;return u[ac-4>>2]}function cc(a){a=tb[a];if(!a)throw new H(8);return a}var L;ia?L=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?L=dateNow:L=function(){return performance.now()};
function dc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function ec(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function fc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var hc=1,ic=[],M=[],jc=[],kc=[],lc=[],N=[],O=[],P=[],mc=[],Q=[],nc=[],S=[],oc=[],pc=[],qc={},sc={},tc={},uc=4;function T(a){vc||(vc=a)}function wc(a){for(var b=hc++,c=a.length;c<b;c++)a[c]=null;return b}function xc(a,b){if(a=1<b.eg?a.getContext("webgl2",b):a.getContext("webgl",b)){var c=wc(mc),d={Og:c,attributes:b,version:b.eg,Lf:a};a.canvas&&(a.canvas.Gg=d);mc[c]=d;("undefined"===typeof b.rg||b.rg)&&yc(d);b=c}else b=0;return b}
function yc(a){a||(a=U);if(!a.tg){a.tg=!0;var b=a.Lf;dc(b);ec(b);fc(b);b.Kg=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Pg=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");b.kf=b.getExtension("EXT_disjoint_timer_query");b.Sg=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}var zc={},vc,U,Ac=[];
function V(a,b,c,d){for(var e=0;e<a;e++){var f=W[c](),h=f&&wc(d);f?(f.name=h,d[h]=f):T(1282);u[b+4*e>>2]=h}}function Bc(a,b,c,d,e,f,h,l){b=M[b];if(a=W[a](b,c))d=l&&B(a.name,y,l,d),e&&(u[e>>2]=d),f&&(u[f>>2]=a.size),h&&(u[h>>2]=a.type)}function Cc(a,b){D[a>>2]=b;D[a+4>>2]=(b-D[a>>2])/4294967296}
function Dc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&T(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=W.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>U.version){T(1282);return}d=2*(W.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>U.version){T(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=W.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":T(1280);return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:T(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:u[b+4*a>>2]=e[a];break;case 2:w[b+4*a>>2]=e[a];break;case 4:r[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){T(1280);
p("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:T(1280);p("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Cc(b,d);break;case 0:u[b>>2]=d;break;case 2:w[b>>2]=d;break;case 4:r[b>>0]=d?1:0}}else T(1281)}
function Ec(a,b,c,d){if(c){b=W.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:T(1280);return}else if(b instanceof WebGLBuffer)a=b.name|0;else{T(1280);return}break;default:T(1280);return}switch(d){case 1:Cc(c,a);break;case 0:u[c>>2]=a;break;case 2:w[c>>2]=a;break;case 4:r[c>>0]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else T(1281)}
function Fc(a){var b=Da(a)+1,c=Aa(b);B(a,y,c,b);return c}function Gc(a,b,c,d){if(c)if(a=W.getUniform(M[a],N[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b]}else T(1281)}
function Hc(a,b,c,d){if(c)if(a=W.getVertexAttrib(a,b),34975==b)u[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:u[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b];break;case 5:u[c+4*b>>2]=Math.fround(a[b])}else T(1281)}function Ic(a){a-=5120;return 0==a?r:1==a?y:2==a?ua:4==a?u:6==a?w:5==a||28922==a||28520==a||30779==a||30782==a?D:Ha}
function Jc(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function Kc(a,b,c,d,e){a=Ic(a);var f=Jc(a),h=uc;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<f)+h-1&-h)>>f)}var Lc=[],Mc=[],Nc=null,Oc=0,Pc=null,Qc=0,Rc=0,Sc=0,Tc=0,Uc=[],Vc={},Wc,Xc,Yc,Zc=!1,$c=!1,ad=[];
function bd(){function a(){$c=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!cd){cd=!0;try{dd=!0}catch(c){dd=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}ed="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:dd?null:console.log("warning: no BlobBuilder");
fd="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;g.gg||"undefined"!==typeof fd||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.gg=!0);g.preloadPlugins.push({canHandle:function(c){return!g.gg&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var h=null;if(dd)try{h=new Blob([c],{type:gd(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:gd(d)}))}catch(t){ra("Blob constructor present but fails: "+
t+"; falling back to blob builder")}h||(h=new ed,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var l=fd.createObjectURL(h),n=new Image;n.onload=function(){assert(n.complete,"Image "+d+" could not be decoded");var t=document.createElement("canvas");t.width=n.width;t.height=n.height;t.getContext("2d").drawImage(n,0,0);g.preloadedImages[d]=t;fd.revokeObjectURL(l);e&&e(c)};n.onerror=function(){console.log("Image "+l+" could not be decoded");f&&f()};n.src=l}});g.preloadPlugins.push({canHandle:function(c){return!g.Tg&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function h(z){n||(n=!0,g.preloadedAudios[d]=z,e&&e(c))}function l(){n||(n=!0,g.preloadedAudios[d]=new Audio,f&&f())}var n=!1;if(dd){try{var t=new Blob([c],{type:gd(d)})}catch(z){return l()}t=fd.createObjectURL(t);var x=new Audio;x.addEventListener("canplaythrough",function(){h(x)},!1);x.onerror=function(){if(!n){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var z="",C=0,E=0,
R=0;R<c.length;R++)for(C=C<<8|c[R],E+=8;6<=E;){var Fb=C>>E-6&63;E-=6;z+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[Fb]}2==E?(z+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(C&3)<<4],z+="=="):4==E&&(z+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(C&15)<<2],z+="=");x.src="data:audio/x-"+d.substr(-3)+";base64,"+z;h(x)}};x.src=t;hd(function(){h(x)})}else return l()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&
b.addEventListener("click",function(c){!$c&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function id(a,b,c,d){if(b&&g.tf&&a==g.canvas)return g.tf;var e;if(b){var f={antialias:!1,alpha:!1,eg:"undefined"!==typeof WebGL2RenderingContext?2:1};if(d)for(var h in d)f[h]=d[h];if("undefined"!==typeof zc&&(e=xc(a,f)))var l=mc[e].Lf}else l=a.getContext("2d");if(!l)return null;c&&(b||assert("undefined"===typeof W,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.tf=l,b&&(U=mc[e],g.tf=W=U&&U.Lf),g.Vg=b,ad.forEach(function(n){n()}),bd());return l}
var jd=!1,kd=void 0,ld=void 0;
function md(a,b){function c(){Zc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=nd,kd&&d.requestPointerLock(),Zc=!0,ld?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=D[SDL.screen>>2]|8388608),od(g.canvas),pd()):od(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),ld?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=D[SDL.screen>>2]&
-8388609),od(g.canvas),pd()):od(d));if(g.onFullScreen)g.onFullScreen(Zc);if(g.onFullscreen)g.onFullscreen(Zc)}kd=a;ld=b;"undefined"===typeof kd&&(kd=!0);"undefined"===typeof ld&&(ld=!1);var d=g.canvas;jd||(jd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function nd(){if(!Zc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var qd=0;function rd(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===qd)qd=b+1E3/60;else for(;b+2>=qd;)qd+=1E3/60;setTimeout(a,Math.max(qd-b,0))}}function hd(a){noExitRuntime=!0;setTimeout(function(){ya||a()},1E4)}
function gd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var sd=0,td=0,ud=0,vd=0;
function wd(a){if($c)"mousemove"!=a.type&&"mozMovementX"in a?ud=vd=0:(ud=a.movementX||a.mozMovementX||a.webkitMovementX||0,vd=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(sd=SDL.Qg+ud,td=SDL.Rg+vd):(sd+=ud,td+=vd);else{var b=g.canvas.getBoundingClientRect(),c=g.canvas.width,d=g.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(f+b.top),e*=c/b.width,a*=d/b.height,ud=e-sd,vd=a-td,sd=e,td=a)}}var xd=[];function pd(){var a=g.canvas;xd.forEach(function(b){b(a.width,a.height)})}function yd(a,b,c){od(g.canvas,a,b);c||pd()}
function od(a,b,c){b&&c?(a.Fg=b,a.sg=c):(b=a.Fg,c=a.sg);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}ld?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var cd,dd,ed,fd;
function zd(a,b){Rc=a;Sc=b;if(Pc)if(0==a)Nc=function(){var d=Math.max(0,Xc+b-L())|0;setTimeout(Yc,d)};else if(1==a)Nc=function(){rd(Yc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}Nc=function(){setImmediate(Yc)}}}
function Ad(a,b,c,d,e){noExitRuntime=!0;assert(!Pc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Pc=a;Qc=d;var f=Oc;Yc=function(){if(!ya)if(0<Uc.length){var h=Date.now(),l=Uc.shift();l.cg(l.yf);if(Wc){var n=Wc,t=0==n%1?n-1:Math.floor(n);Wc=l.Jg?t:(8*n+(t+.5))/9}console.log('main loop blocker "'+l.name+'" took '+(Date.now()-h)+" ms");g.setStatus&&(h=g.statusMessage||
"Please wait...",l=Wc,n=Vc.Lg,l?l<n?g.setStatus(h+" ("+(n-l)+"/"+n+")"):g.setStatus(h):g.setStatus(""));f<Oc||setTimeout(Yc,0)}else if(!(f<Oc))if(Tc=Tc+1|0,1==Rc&&1<Sc&&0!=Tc%Sc)Nc();else{0==Rc&&(Xc=L());a:if(!(ya||g.preMainLoop&&!1===g.preMainLoop())){try{a()}catch(x){if(x instanceof pa||"unwind"==x)break a;x&&"object"===typeof x&&x.stack&&p("exception thrown: "+[x,x.stack]);throw x;}g.postMainLoop&&g.postMainLoop()}f<Oc||("object"===typeof SDL&&SDL.audio&&SDL.audio.Bg&&SDL.audio.Bg(),Nc())}};e||
(b&&0<b?zd(0,1E3/b):zd(1,1),Nc());if(c)throw"unwind";}var Bd={};function Cd(){if(!Dd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Bd)a[b]=Bd[b];var c=[];for(b in a)c.push(b+"="+a[b]);Dd=c}return Dd}var Dd;
function Ed(a,b,c,d){this.id=a;this.y=this.x=0;this.Rf=!1;this.kg=this.jg=0;this.width=b;this.height=c;this.ig=b;this.hg=c;this.title=d;this.attributes=Fd;this.buttons=0;this.keys=[];this.Pf=[];this.Xf=this.Cf=this.Qf=this.Jf=this.zf=this.Af=this.Hf=this.Bf=this.mg=this.ng=this.title=null}function Gd(a){return 0>=a||!X?null:X[a-1]}
var Hd=null,Y=null,X=null,Fd=null,Id={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function Jd(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Kd(){var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Ld(a){Y&&Y.Xf&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||F.get(Y.Xf)(Y.id,a))}
function Md(a,b){if(Y){var c=Jd(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.Pf[a]=b;Y.Cf&&(d&&(b=2),F.get(Y.Cf)(Y.id,c,a,b,Kd()))}}}function Nd(){Od()}function Pd(){Od()}function Qd(a){Md(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function Rd(a){Md(a.keyCode,0)}function Sd(){if(Y)for(var a=0;a<Y.Pf.length;++a)Y.Pf[a]&&Md(a,0)}function Td(a){Y&&(wd(a),a.target==g.canvas&&Y.Af&&F.get(Y.Af)(Y.id,sd,td))}function Ud(a){Y&&a.target==g.canvas&&Y.zf&&F.get(Y.zf)(Y.id,1)}
function Vd(a){Y&&a.target==g.canvas&&Y.zf&&F.get(Y.zf)(Y.id,0)}function Wd(a,b){if(Y&&(wd(a),a.target==g.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Y.buttons&=~(1<<c);Y.Hf&&F.get(Y.Hf)(Y.id,c,b,Kd())}}function Xd(a){Y&&Wd(a,1)}function Yd(a){Y&&Wd(a,0)}
function Zd(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":switch(a.deltaMode){case 0:break;case 1:break;case 2:break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}if(Y&&Y.Jf&&a.target==g.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;F.get(Y.Jf)(Y.id,b,c);a.preventDefault()}}var $d={},ae=null,be=null;
function Od(){if(Tc!==be||!Tc){ae=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;be=Tc;for(var a=0;a<ae.length;++a){var b=ae[a];if(b){$d[a]||(console.log("glfw joystick connected:",a),$d[a]={id:za(kb(b.id)),Ig:b.buttons.length,Hg:b.axes.length,buttons:za(Array(b.buttons.length)),axes:za(Array(4*b.axes.length))});for(var c=$d[a],d=0;d<b.buttons.length;++d)q(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)q(c.axes+4*d,b.axes[d],
"float")}else $d[a]&&(console.log("glfw joystick disconnected",a),ce($d[a].id),ce($d[a].buttons),ce($d[a].axes),delete $d[a])}}}
function de(a){function b(l){var n="/.glfw_dropped_files/"+l.name.replace(/\//g,"_"),t=new FileReader;t.onloadend=function(z){if(2!=t.readyState)++f,console.log("failed to read dropped file: "+l.name+": "+t.error);else{var C=new Uint8Array(z.target.result);var E=E||{};E.flags=E.flags||577;z=Pb(n,E.flags,E.mode);if("string"===typeof C){var R=new Uint8Array(Da(C)+1);C=B(C,R,0,R.length);Tb(z,R,0,C,E.pg)}else if(ArrayBuffer.isView(C))Tb(z,C,0,C.byteLength,E.pg);else throw Error("Unsupported data type");
Rb(z);if(++f===e){F.get(Y.Qf)(Y.id,e,c);for(E=0;E<d.length;++E)ce(d[E]);ce(c)}}};t.readAsArrayBuffer(l);var x=za(kb(n));d.push(x);q(c+4*h,x,"i8*")}if(Y&&Y.Qf&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=za(Array(4*a.dataTransfer.files.length)),d=[],e=a.dataTransfer.files.length,f=0;Xb();for(var h=0;h<e;++h)b(a.dataTransfer.files[h]);return!1}}function ee(a){if(Y&&Y.Qf)return a.preventDefault(),!1}var fe=[];
function Db(a,b,c,d){a||(a=this);this.parent=a;this.qf=a.qf;this.Gf=null;this.id=ub++;this.name=b;this.mode=c;this.ff={};this.ef={};this.rdev=d}Object.defineProperties(Db.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Ub();vb=Array(4096);Lb(I,"/");J("/tmp");J("/home");J("/home/web_user");
(function(){J("/dev");ib(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Nb("/dev/null",259);hb(1280,lb);hb(1536,mb);Nb("/dev/tty",1280);Nb("/dev/tty1",1536);var a=eb();Yb("random",a);Yb("urandom",a);J("/dev/shm");J("/dev/shm/tmp")})();
(function(){J("/proc");var a=J("/proc/self");J("/proc/self/fd");Lb({qf:function(){var b=ob(a,"fd",16895,73);b.ff={lookup:function(c,d){var e=tb[+d];if(!e)throw new H(8);c={parent:null,qf:{fg:"fake"},ff:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();for(var W,Z=0;32>Z;++Z)Ac.push(Array(Z));var ge=new Float32Array(288);for(Z=0;288>Z;++Z)Lc[Z]=ge.subarray(0,Z+1);var he=new Int32Array(288);for(Z=0;288>Z;++Z)Mc[Z]=he.subarray(0,Z+1);
g.requestFullscreen=function(a,b){md(a,b)};g.requestAnimationFrame=function(a){rd(a)};g.setCanvasSize=function(a,b,c){yd(a,b,c)};g.pauseMainLoop=function(){Nc=null;Oc++};g.resumeMainLoop=function(){Oc++;var a=Rc,b=Sc,c=Pc;Pc=null;Ad(c,0,!1,Qc,!0);zd(a,b);Nc()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=function(a,b,c,d){return id(a,b,c,d)};
function kb(a,b){var c=Array(Da(a)+1);a=B(a,c,0,c.length);b&&(c.length=a);return c}
var ne={b:function(a,b,c,d){m("Assertion failed: "+A(a)+", at: "+[b?A(b):"unknown filename",c,d?A(d):"unknown function"])},l:function(a,b,c){ac=c;try{var d=cc(a);switch(b){case 0:var e=bc();return 0>e?-28:Pb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=bc(),d.flags|=e,0;case 12:return e=bc(),ua[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return u[ie()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof K&&f instanceof H||
m(f),-f.lf}},Ga:function(a,b,c){ac=c;try{var d=cc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=bc();return u[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=bc();if(!d.ef.ug)throw new H(59);return d.ef.ug(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:m("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof K&&f instanceof H||m(f),
-f.lf}},nb:function(a,b,c,d,e,f){try{a:{f<<=12;var h=!1;if(0!==(d&16)&&0!==a%16384)var l=-28;else{if(0!==(d&32)){var n=je(16384,b);if(!n){l=-48;break a}ke(n,0,b);h=!0}else{var t=tb[e];if(!t){l=-8;break a}var x=f;if(0!==(c&2)&&0===(d&2)&&2!==(t.flags&2097155))throw new H(2);if(1===(t.flags&2097155))throw new H(2);if(!t.ef.Ff)throw new H(43);var z=t.ef.Ff(t,a,b,x,c,d);n=z.Ag;h=z.Mf}$b[n]={wg:n,vg:b,Mf:h,fd:e,zg:c,flags:d,offset:f};l=n}}return l}catch(C){return"undefined"!==typeof K&&C instanceof H||
m(C),-C.lf}},yb:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=$b[a];if(d&&b===d.vg){var e=tb[d.fd];if(e&&d.zg&2){var f=d.flags,h=d.offset,l=y.slice(a,a+b);e&&e.ef.If&&e.ef.If(e,l,h,b,f)}$b[a]=null;d.Mf&&ce(d.wg)}c=0}return c}catch(n){return"undefined"!==typeof K&&n instanceof H||m(n),-n.lf}},Ka:function(a,b,c){ac=c;try{var d=A(a),e=c?bc():0;return Pb(d,b,e).fd}catch(f){return"undefined"!==typeof K&&f instanceof H||m(f),-f.lf}},Ba:function(){m()},i:function(a,b){if(0===a)a=Date.now();
else if(1===a||4===a)a=L();else return u[ie()>>2]=28,-1;u[b>>2]=a/1E3|0;u[b+4>>2]=a%1E3*1E6|0;return 0},c:function(a,b,c){fe.length=0;var d;for(c>>=2;d=y[b++];)(d=105>d)&&c&1&&c++,fe.push(d?wa[c++>>1]:u[c]),++c;return Ya[a].apply(null,fe)},da:function(a){W.activeTexture(a)},ca:function(a,b){W.attachShader(M[a],O[b])},uc:function(a,b){W.beginQuery(a,nc[b])},va:function(a,b){W.kf.beginQueryEXT(a,Q[b])},bc:function(a){W.beginTransformFeedback(a)},ba:function(a,b,c){W.bindAttribLocation(M[a],b,A(c))},
aa:function(a,b){35051==a?W.Of=b:35052==a&&(W.mf=b);W.bindBuffer(a,ic[b])},_b:function(a,b,c){W.bindBufferBase(a,b,ic[c])},$b:function(a,b,c,d,e){W.bindBufferRange(a,b,ic[c],d,e)},$:function(a,b){W.bindFramebuffer(a,jc[b])},_:function(a,b){W.bindRenderbuffer(a,kc[b])},eb:function(a,b){W.bindSampler(a,S[b])},Z:function(a,b){W.bindTexture(a,lc[b])},Ya:function(a,b){W.bindTransformFeedback(a,oc[b])},gc:function(a){W.bindVertexArray(P[a])},ma:function(a){W.bindVertexArray(P[a])},Y:function(a,b,c,d){W.blendColor(a,
b,c,d)},X:function(a){W.blendEquation(a)},W:function(a,b){W.blendEquationSeparate(a,b)},U:function(a,b){W.blendFunc(a,b)},T:function(a,b,c,d){W.blendFuncSeparate(a,b,c,d)},jc:function(a,b,c,d,e,f,h,l,n,t){W.blitFramebuffer(a,b,c,d,e,f,h,l,n,t)},S:function(a,b,c,d){2<=U.version?c?W.bufferData(a,y,d,c,b):W.bufferData(a,b,d):W.bufferData(a,c?y.subarray(c,c+b):b,d)},R:function(a,b,c,d){2<=U.version?W.bufferSubData(a,b,y,d,c):W.bufferSubData(a,b,y.subarray(d,d+c))},Q:function(a){return W.checkFramebufferStatus(a)},
P:function(a){W.clear(a)},Db:function(a,b,c,d){W.clearBufferfi(a,b,c,d)},Eb:function(a,b,c){W.clearBufferfv(a,b,w,c>>2)},Gb:function(a,b,c){W.clearBufferiv(a,b,u,c>>2)},Fb:function(a,b,c){W.clearBufferuiv(a,b,D,c>>2)},O:function(a,b,c,d){W.clearColor(a,b,c,d)},N:function(a){W.clearDepth(a)},M:function(a){W.clearStencil(a)},ob:function(a,b,c,d){return W.clientWaitSync(pc[a],b,(c>>>0)+4294967296*d)},L:function(a,b,c,d){W.colorMask(!!a,!!b,!!c,!!d)},J:function(a){W.compileShader(O[a])},I:function(a,
b,c,d,e,f,h,l){2<=U.version?W.mf?W.compressedTexImage2D(a,b,c,d,e,f,h,l):W.compressedTexImage2D(a,b,c,d,e,f,y,l,h):W.compressedTexImage2D(a,b,c,d,e,f,l?y.subarray(l,l+h):null)},Ac:function(a,b,c,d,e,f,h,l,n){W.mf?W.compressedTexImage3D(a,b,c,d,e,f,h,l,n):W.compressedTexImage3D(a,b,c,d,e,f,h,y,n,l)},H:function(a,b,c,d,e,f,h,l,n){2<=U.version?W.mf?W.compressedTexSubImage2D(a,b,c,d,e,f,h,l,n):W.compressedTexSubImage2D(a,b,c,d,e,f,h,y,n,l):W.compressedTexSubImage2D(a,b,c,d,e,f,h,n?y.subarray(n,n+l):null)},
zc:function(a,b,c,d,e,f,h,l,n,t,x){W.mf?W.compressedTexSubImage3D(a,b,c,d,e,f,h,l,n,t,x):W.compressedTexSubImage3D(a,b,c,d,e,f,h,l,n,y,x,t)},Bb:function(a,b,c,d,e){W.copyBufferSubData(a,b,c,d,e)},G:function(a,b,c,d,e,f,h,l){W.copyTexImage2D(a,b,c,d,e,f,h,l)},F:function(a,b,c,d,e,f,h,l){W.copyTexSubImage2D(a,b,c,d,e,f,h,l)},Bc:function(a,b,c,d,e,f,h,l,n){W.copyTexSubImage3D(a,b,c,d,e,f,h,l,n)},E:function(){var a=wc(M),b=W.createProgram();b.name=a;M[a]=b;return a},D:function(a){var b=wc(O);O[b]=W.createShader(a);
return b},C:function(a){W.cullFace(a)},B:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=ic[d];e&&(W.deleteBuffer(e),e.name=0,ic[d]=null,d==W.Of&&(W.Of=0),d==W.mf&&(W.mf=0))}},A:function(a,b){for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=jc[d];e&&(W.deleteFramebuffer(e),e.name=0,jc[d]=null)}},y:function(a){if(a){var b=M[a];b?(W.deleteProgram(b),b.name=0,M[a]=null,qc[a]=null):T(1281)}},xc:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=nc[d];e&&(W.deleteQuery(e),nc[d]=null)}},xa:function(a,
b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Q[d];e&&(W.kf.deleteQueryEXT(e),Q[d]=null)}},x:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=kc[d];e&&(W.deleteRenderbuffer(e),e.name=0,kc[d]=null)}},gb:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=S[d];e&&(W.deleteSampler(e),e.name=0,S[d]=null)}},w:function(a){if(a){var b=O[a];b?(W.deleteShader(b),O[a]=null):T(1281)}},pb:function(a){if(a){var b=pc[a];b?(W.deleteSync(b),b.name=0,pc[a]=null):T(1281)}},v:function(a,b){for(var c=0;c<a;c++){var d=
u[b+4*c>>2],e=lc[d];e&&(W.deleteTexture(e),e.name=0,lc[d]=null)}},Xa:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=oc[d];e&&(W.deleteTransformFeedback(e),e.name=0,oc[d]=null)}},fc:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2];W.deleteVertexArray(P[d]);P[d]=null}},la:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2];W.deleteVertexArray(P[d]);P[d]=null}},u:function(a){W.depthFunc(a)},t:function(a){W.depthMask(!!a)},s:function(a,b){W.depthRange(a,b)},r:function(a,b){W.detachShader(M[a],
O[b])},q:function(a){W.disable(a)},p:function(a){W.disableVertexAttribArray(a)},Re:function(a,b,c){W.drawArrays(a,b,c)},tb:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},ha:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},Lc:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},Mc:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},Ia:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},qc:function(a,b){for(var c=Ac[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];W.drawBuffers(c)},Hc:function(a,b){for(var c=Ac[a],d=0;d<
a;d++)c[d]=u[b+4*d>>2];W.drawBuffers(c)},ia:function(a,b){for(var c=Ac[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];W.drawBuffers(c)},Qe:function(a,b,c,d){W.drawElements(a,b,c,d)},sb:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},ga:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},Ic:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},Jc:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},Kc:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},Ec:function(a,b,c,d,e,f){W.drawElements(a,
d,e,f)},Pe:function(a){W.enable(a)},Oe:function(a){W.enableVertexAttribArray(a)},tc:function(a){W.endQuery(a)},ua:function(a){W.kf.endQueryEXT(a)},ac:function(){W.endTransformFeedback()},rb:function(a,b){return(a=W.fenceSync(a,b))?(b=wc(pc),a.name=b,pc[b]=a,b):0},Ne:function(){W.finish()},Me:function(){W.flush()},Le:function(a,b,c,d){W.framebufferRenderbuffer(a,b,c,kc[d])},Ke:function(a,b,c,d,e){W.framebufferTexture2D(a,b,c,lc[d],e)},hc:function(a,b,c,d,e){W.framebufferTextureLayer(a,b,lc[c],d,e)},
Je:function(a){W.frontFace(a)},Ie:function(a,b){V(a,b,"createBuffer",ic)},Fe:function(a,b){V(a,b,"createFramebuffer",jc)},yc:function(a,b){V(a,b,"createQuery",nc)},ya:function(a,b){for(var c=0;c<a;c++){var d=W.kf.createQueryEXT();if(!d){for(T(1282);c<a;)u[b+4*c++>>2]=0;break}var e=wc(Q);d.name=e;Q[e]=d;u[b+4*c>>2]=e}},Ee:function(a,b){V(a,b,"createRenderbuffer",kc)},hb:function(a,b){V(a,b,"createSampler",S)},De:function(a,b){V(a,b,"createTexture",lc)},Wa:function(a,b){V(a,b,"createTransformFeedback",
oc)},ec:function(a,b){V(a,b,"createVertexArray",P)},ka:function(a,b){V(a,b,"createVertexArray",P)},Ge:function(a){W.generateMipmap(a)},Ce:function(a,b,c,d,e,f,h){Bc("getActiveAttrib",a,b,c,d,e,f,h)},Be:function(a,b,c,d,e,f,h){Bc("getActiveUniform",a,b,c,d,e,f,h)},vb:function(a,b,c,d,e){a=M[a];if(a=W.getActiveUniformBlockName(a,b))e&&0<c?(c=B(a,y,e,c),d&&(u[d>>2]=c)):d&&(u[d>>2]=0)},wb:function(a,b,c,d){if(d)switch(a=M[a],c){case 35393:a=W.getActiveUniformBlockName(a,b);u[d>>2]=a.length+1;break;default:if(a=
W.getActiveUniformBlockParameter(a,b,c))if("number"==typeof a)u[d>>2]=a;else for(b=0;b<a.length;b++)u[d+4*b>>2]=a[b]}else T(1281)},zb:function(a,b,c,d,e){if(e)if(0<b&&0==c)T(1281);else{a=M[a];for(var f=[],h=0;h<b;h++)f.push(u[c+4*h>>2]);if(a=W.getActiveUniforms(a,f,d))for(b=a.length,h=0;h<b;h++)u[e+4*h>>2]=a[h]}else T(1281)},Ae:function(a,b,c,d){a=W.getAttachedShaders(M[a]);var e=a.length;e>b&&(e=b);u[c>>2]=e;for(b=0;b<e;++b)u[d+4*b>>2]=O.indexOf(a[b])},ze:function(a,b){return W.getAttribLocation(M[a],
A(b))},ye:function(a,b){Dc(a,b,4)},ib:function(a,b,c){c?Cc(c,W.getBufferParameter(a,b)):T(1281)},xe:function(a,b,c){c?u[c>>2]=W.getBufferParameter(a,b):T(1281)},ve:function(){var a=W.getError()||vc;vc=0;return a},ue:function(a,b){Dc(a,b,2)},Pb:function(a,b){return W.getFragDataLocation(M[a],A(b))},te:function(a,b,c,d){a=W.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u[d>>2]=a},jb:function(a,b,c){Ec(a,b,c,1)},lb:function(a,b){Dc(a,
b,1)},cc:function(a,b,c){Ec(a,b,c,0)},se:function(a,b){Dc(a,b,0)},La:function(a,b,c,d,e){if(0>d)T(1281);else if(e){if(a=W.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)u[e+b>>2]=a[b]}else T(1281)},Sa:function(){T(1282)},qe:function(a,b,c,d){a=W.getProgramInfoLog(M[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,y,d,b):0;c&&(u[c>>2]=b)},re:function(a,b,c){if(c)if(a>=hc)T(1281);else{var d=qc[a];if(d)if(35716==b)a=W.getProgramInfoLog(M[a]),null===a&&(a="(unknown error)"),u[c>>
2]=a.length+1;else if(35719==b)u[c>>2]=d.Tf;else if(35722==b){if(-1==d.vf){a=M[a];var e=W.getProgramParameter(a,35721);for(b=d.vf=0;b<e;++b)d.vf=Math.max(d.vf,W.getActiveAttrib(a,b).name.length+1)}u[c>>2]=d.vf}else if(35381==b){if(-1==d.wf)for(a=M[a],e=W.getProgramParameter(a,35382),b=d.wf=0;b<e;++b)d.wf=Math.max(d.wf,W.getActiveUniformBlockName(a,b).length+1);u[c>>2]=d.wf}else u[c>>2]=W.getProgramParameter(M[a],b);else T(1282)}else T(1281)},oa:function(a,b,c){if(c){a=W.kf.getQueryObjectEXT(Q[a],
b);var d;"boolean"==typeof a?d=a?1:0:d=a;Cc(c,d)}else T(1281)},ra:function(a,b,c){if(c){a=W.kf.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else T(1281)},na:function(a,b,c){if(c){a=W.kf.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Cc(c,d)}else T(1281)},rc:function(a,b,c){if(c){a=W.getQueryParameter(nc[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else T(1281)},qa:function(a,b,c){if(c){a=W.kf.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?
d=a?1:0:d=a;u[c>>2]=d}else T(1281)},sc:function(a,b,c){c?u[c>>2]=W.getQuery(a,b):T(1281)},sa:function(a,b,c){c?u[c>>2]=W.kf.getQueryEXT(a,b):T(1281)},pe:function(a,b,c){c?u[c>>2]=W.getRenderbufferParameter(a,b):T(1281)},_a:function(a,b,c){c?(a=S[a],w[c>>2]=W.getSamplerParameter(a,b)):T(1281)},$a:function(a,b,c){c?(a=S[a],u[c>>2]=W.getSamplerParameter(a,b)):T(1281)},ne:function(a,b,c,d){a=W.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,y,d,b):0;c&&(u[c>>2]=b)},me:function(a,b,
c,d){a=W.getShaderPrecisionFormat(a,b);u[c>>2]=a.rangeMin;u[c+4>>2]=a.rangeMax;u[d>>2]=a.precision},le:function(a,b,c,d){if(a=W.getShaderSource(O[a]))b=0<b&&d?B(a,y,d,b):0,c&&(u[c>>2]=b)},oe:function(a,b,c){c?35716==b?(a=W.getShaderInfoLog(O[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=W.getShaderSource(O[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=W.getShaderParameter(O[a],b):T(1281)},ke:function(a){if(sc[a])return sc[a];switch(a){case 7939:var b=W.getSupportedExtensions()||[];
b=b.concat(b.map(function(d){return"GL_"+d}));b=Fc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=W.getParameter(a))||T(1280);b=Fc(b);break;case 7938:b=W.getParameter(7938);b=2<=U.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Fc(b);break;case 35724:b=W.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Fc(b);break;default:return T(1280),0}return sc[a]=b},Cb:function(a,
b){if(2>U.version)return T(1282),0;var c=tc[a];if(c)return 0>b||b>=c.length?(T(1281),0):c[b];switch(a){case 7939:return c=W.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return Fc(d)}),c=tc[a]=c,0>b||b>=c.length?(T(1281),0):c[b];default:return T(1280),0}},kb:function(a,b,c,d,e){0>c?T(1281):e?(a=W.getSyncParameter(pc[a],b),u[d>>2]=a,null!==a&&d&&(u[d>>2]=1)):T(1281)},je:function(a,b,c){c?w[c>>2]=W.getTexParameter(a,b):T(1281)},ie:function(a,b,c){c?u[c>>
2]=W.getTexParameter(a,b):T(1281)},Yb:function(a,b,c,d,e,f,h){a=M[a];if(a=W.getTransformFeedbackVarying(a,b))h&&0<c?(c=B(a.name,y,h,c),d&&(u[d>>2]=c)):d&&(u[d>>2]=0),e&&(u[e>>2]=a.size),f&&(u[f>>2]=a.type)},xb:function(a,b){return W.getUniformBlockIndex(M[a],A(b))},Ab:function(a,b,c,d){if(d)if(0<b&&(0==c||0==d))T(1281);else{a=M[a];for(var e=[],f=0;f<b;f++)e.push(A(u[c+4*f>>2]));if(a=W.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)u[d+4*f>>2]=a[f]}else T(1281)},fe:function(a,b){b=A(b);var c=0;
if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=qc[a]&&qc[a].lg[b])&&0<=c&&c<a[0]?a[1]+c:-1},he:function(a,b,c){Gc(a,b,c,2)},ge:function(a,b,c){Gc(a,b,c,0)},Qb:function(a,b,c){Gc(a,b,c,0)},Wb:function(a,b,c){Hc(a,b,c,0)},Vb:function(a,b,c){Hc(a,b,c,0)},ce:function(a,b,c){c?u[c>>2]=W.getVertexAttribOffset(a,b):T(1281)},ee:function(a,b,c){Hc(a,b,c,2)},de:function(a,b,c){Hc(a,b,c,5)},ae:function(a,b){W.hint(a,b)},Pa:function(a,b,c){for(var d=
Ac[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];W.invalidateFramebuffer(a,d)},Oa:function(a,b,c,d,e,f,h){for(var l=Ac[b],n=0;n<b;n++)l[n]=u[c+4*n>>2];W.invalidateSubFramebuffer(a,l,d,e,f,h)},$d:function(a){return(a=ic[a])?W.isBuffer(a):0},_d:function(a){return W.isEnabled(a)},Zd:function(a){return(a=jc[a])?W.isFramebuffer(a):0},Yd:function(a){return(a=M[a])?W.isProgram(a):0},wc:function(a){return(a=nc[a])?W.isQuery(a):0},wa:function(a){return(a=Q[a])?W.kf.isQueryEXT(a):0},Xd:function(a){return(a=kc[a])?W.isRenderbuffer(a):
0},fb:function(a){return(a=S[a])?W.isSampler(a):0},Wd:function(a){return(a=O[a])?W.isShader(a):0},qb:function(a){return W.isSync(pc[a])},Vd:function(a){return(a=lc[a])?W.isTexture(a):0},Va:function(a){return W.isTransformFeedback(oc[a])},dc:function(a){return(a=P[a])?W.isVertexArray(a):0},ja:function(a){return(a=P[a])?W.isVertexArray(a):0},Ud:function(a){W.lineWidth(a)},Td:function(a){W.linkProgram(M[a]);var b=M[a];a=qc[a]={lg:{},Tf:0,vf:-1,wf:-1};for(var c=a.lg,d=W.getProgramParameter(b,35718),e=
0;e<d;++e){var f=W.getActiveUniform(b,e),h=f.name;a.Tf=Math.max(a.Tf,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var l=W.getUniformLocation(b,h);if(l){var n=wc(N);c[h]=[f.size,n];N[n]=l;for(var t=1;t<f.size;++t)l=W.getUniformLocation(b,h+"["+t+"]"),n=wc(N),N[n]=l}}},Ua:function(){W.pauseTransformFeedback()},Rd:function(a,b){3317==a&&(uc=b);W.pixelStorei(a,b)},Qd:function(a,b){W.polygonOffset(a,b)},Ra:function(){T(1280)},Qa:function(){T(1280)},ta:function(a,b){W.kf.queryCounterEXT(Q[a],
b)},Fc:function(a){W.readBuffer(a)},Pd:function(a,b,c,d,e,f,h){if(2<=U.version)if(W.Of)W.readPixels(a,b,c,d,e,f,h);else{var l=Ic(f);W.readPixels(a,b,c,d,e,f,l,h>>Jc(l))}else(h=Kc(f,e,c,d,h))?W.readPixels(a,b,c,d,e,f,h):T(1280)},Od:function(){},Nd:function(a,b,c,d){W.renderbufferStorage(a,b,c,d)},ic:function(a,b,c,d,e){W.renderbufferStorageMultisample(a,b,c,d,e)},Ta:function(){W.resumeTransformFeedback()},Md:function(a,b){W.sampleCoverage(a,!!b)},bb:function(a,b,c){W.samplerParameterf(S[a],b,c)},ab:function(a,
b,c){W.samplerParameterf(S[a],b,w[c>>2])},db:function(a,b,c){W.samplerParameteri(S[a],b,c)},cb:function(a,b,c){W.samplerParameteri(S[a],b,u[c>>2])},Ld:function(a,b,c,d){W.scissor(a,b,c,d)},Kd:function(){T(1280)},Jd:function(a,b,c,d){for(var e="",f=0;f<b;++f){var h=d?u[d+4*f>>2]:-1;e+=A(u[c+4*f>>2],0>h?void 0:h)}W.shaderSource(O[a],e)},Id:function(a,b,c){W.stencilFunc(a,b,c)},Gd:function(a,b,c,d){W.stencilFuncSeparate(a,b,c,d)},Fd:function(a){W.stencilMask(a)},Ed:function(a,b){W.stencilMaskSeparate(a,
b)},Dd:function(a,b,c){W.stencilOp(a,b,c)},Cd:function(a,b,c,d){W.stencilOpSeparate(a,b,c,d)},Bd:function(a,b,c,d,e,f,h,l,n){if(2<=U.version)if(W.mf)W.texImage2D(a,b,c,d,e,f,h,l,n);else if(n){var t=Ic(l);W.texImage2D(a,b,c,d,e,f,h,l,t,n>>Jc(t))}else W.texImage2D(a,b,c,d,e,f,h,l,null);else W.texImage2D(a,b,c,d,e,f,h,l,n?Kc(l,h,d,e,n):null)},Dc:function(a,b,c,d,e,f,h,l,n,t){if(W.mf)W.texImage3D(a,b,c,d,e,f,h,l,n,t);else if(t){var x=Ic(n);W.texImage3D(a,b,c,d,e,f,h,l,n,x,t>>Jc(x))}else W.texImage3D(a,
b,c,d,e,f,h,l,n,null)},Ad:function(a,b,c){W.texParameterf(a,b,c)},zd:function(a,b,c){W.texParameterf(a,b,w[c>>2])},yd:function(a,b,c){W.texParameteri(a,b,c)},xd:function(a,b,c){W.texParameteri(a,b,u[c>>2])},Na:function(a,b,c,d,e){W.texStorage2D(a,b,c,d,e)},Ma:function(a,b,c,d,e,f){W.texStorage3D(a,b,c,d,e,f)},vd:function(a,b,c,d,e,f,h,l,n){if(2<=U.version)if(W.mf)W.texSubImage2D(a,b,c,d,e,f,h,l,n);else if(n){var t=Ic(l);W.texSubImage2D(a,b,c,d,e,f,h,l,t,n>>Jc(t))}else W.texSubImage2D(a,b,c,d,e,f,
h,l,null);else t=null,n&&(t=Kc(l,h,e,f,n)),W.texSubImage2D(a,b,c,d,e,f,h,l,t)},Cc:function(a,b,c,d,e,f,h,l,n,t,x){if(W.mf)W.texSubImage3D(a,b,c,d,e,f,h,l,n,t,x);else if(x){var z=Ic(t);W.texSubImage3D(a,b,c,d,e,f,h,l,n,t,z,x>>Jc(z))}else W.texSubImage3D(a,b,c,d,e,f,h,l,n,t,null)},Zb:function(a,b,c,d){a=M[a];for(var e=[],f=0;f<b;f++)e.push(A(u[c+4*f>>2]));W.transformFeedbackVaryings(a,e,d)},ud:function(a,b){W.uniform1f(N[a],b)},td:function(a,b,c){if(2<=U.version)W.uniform1fv(N[a],w,c>>2,b);else{if(288>=
b)for(var d=Lc[b-1],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);W.uniform1fv(N[a],d)}},sd:function(a,b){W.uniform1i(N[a],b)},rd:function(a,b,c){if(2<=U.version)W.uniform1iv(N[a],u,c>>2,b);else{if(288>=b)for(var d=Mc[b-1],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);W.uniform1iv(N[a],d)}},Ob:function(a,b){W.uniform1ui(N[a],b)},Kb:function(a,b,c){W.uniform1uiv(N[a],D,c>>2,b)},qd:function(a,b,c){W.uniform2f(N[a],b,c)},pd:function(a,b,c){if(2<=U.version)W.uniform2fv(N[a],
w,c>>2,2*b);else{if(144>=b)for(var d=Lc[2*b-1],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);W.uniform2fv(N[a],d)}},od:function(a,b,c){W.uniform2i(N[a],b,c)},nd:function(a,b,c){if(2<=U.version)W.uniform2iv(N[a],u,c>>2,2*b);else{if(144>=b)for(var d=Mc[2*b-1],e=0;e<2*b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2];else d=u.subarray(c>>2,c+8*b>>2);W.uniform2iv(N[a],d)}},Nb:function(a,b,c){W.uniform2ui(N[a],b,c)},Jb:function(a,b,c){W.uniform2uiv(N[a],D,c>>2,2*
b)},md:function(a,b,c,d){W.uniform3f(N[a],b,c,d)},kd:function(a,b,c){if(2<=U.version)W.uniform3fv(N[a],w,c>>2,3*b);else{if(96>=b)for(var d=Lc[3*b-1],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);W.uniform3fv(N[a],d)}},jd:function(a,b,c,d){W.uniform3i(N[a],b,c,d)},id:function(a,b,c){if(2<=U.version)W.uniform3iv(N[a],u,c>>2,3*b);else{if(96>=b)for(var d=Mc[3*b-1],e=0;e<3*b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>
2];else d=u.subarray(c>>2,c+12*b>>2);W.uniform3iv(N[a],d)}},Mb:function(a,b,c,d){W.uniform3ui(N[a],b,c,d)},Ib:function(a,b,c){W.uniform3uiv(N[a],D,c>>2,3*b)},hd:function(a,b,c,d,e){W.uniform4f(N[a],b,c,d,e)},gd:function(a,b,c){if(2<=U.version)W.uniform4fv(N[a],w,c>>2,4*b);else{if(72>=b){var d=Lc[4*b-1],e=w;c>>=2;for(var f=0;f<4*b;f+=4){var h=c+f;d[f]=e[h];d[f+1]=e[h+1];d[f+2]=e[h+2];d[f+3]=e[h+3]}}else d=w.subarray(c>>2,c+16*b>>2);W.uniform4fv(N[a],d)}},fd:function(a,b,c,d,e){W.uniform4i(N[a],b,c,
d,e)},ed:function(a,b,c){if(2<=U.version)W.uniform4iv(N[a],u,c>>2,4*b);else{if(72>=b)for(var d=Mc[4*b-1],e=0;e<4*b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2];else d=u.subarray(c>>2,c+16*b>>2);W.uniform4iv(N[a],d)}},Lb:function(a,b,c,d,e){W.uniform4ui(N[a],b,c,d,e)},Hb:function(a,b,c){W.uniform4uiv(N[a],D,c>>2,4*b)},ub:function(a,b,c){a=M[a];W.uniformBlockBinding(a,b,c)},dd:function(a,b,c,d){if(2<=U.version)W.uniformMatrix2fv(N[a],!!c,w,d>>2,4*b);else{if(72>=
b)for(var e=Lc[4*b-1],f=0;f<4*b;f+=4)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2];else e=w.subarray(d>>2,d+16*b>>2);W.uniformMatrix2fv(N[a],!!c,e)}},pc:function(a,b,c,d){W.uniformMatrix2x3fv(N[a],!!c,w,d>>2,6*b)},nc:function(a,b,c,d){W.uniformMatrix2x4fv(N[a],!!c,w,d>>2,8*b)},cd:function(a,b,c,d){if(2<=U.version)W.uniformMatrix3fv(N[a],!!c,w,d>>2,9*b);else{if(32>=b)for(var e=Lc[9*b-1],f=0;f<9*b;f+=9)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+
8)>>2],e[f+3]=w[d+(4*f+12)>>2],e[f+4]=w[d+(4*f+16)>>2],e[f+5]=w[d+(4*f+20)>>2],e[f+6]=w[d+(4*f+24)>>2],e[f+7]=w[d+(4*f+28)>>2],e[f+8]=w[d+(4*f+32)>>2];else e=w.subarray(d>>2,d+36*b>>2);W.uniformMatrix3fv(N[a],!!c,e)}},oc:function(a,b,c,d){W.uniformMatrix3x2fv(N[a],!!c,w,d>>2,6*b)},lc:function(a,b,c,d){W.uniformMatrix3x4fv(N[a],!!c,w,d>>2,12*b)},bd:function(a,b,c,d){if(2<=U.version)W.uniformMatrix4fv(N[a],!!c,w,d>>2,16*b);else{if(18>=b){var e=Lc[16*b-1],f=w;d>>=2;for(var h=0;h<16*b;h+=16){var l=d+
h;e[h]=f[l];e[h+1]=f[l+1];e[h+2]=f[l+2];e[h+3]=f[l+3];e[h+4]=f[l+4];e[h+5]=f[l+5];e[h+6]=f[l+6];e[h+7]=f[l+7];e[h+8]=f[l+8];e[h+9]=f[l+9];e[h+10]=f[l+10];e[h+11]=f[l+11];e[h+12]=f[l+12];e[h+13]=f[l+13];e[h+14]=f[l+14];e[h+15]=f[l+15]}}else e=w.subarray(d>>2,d+64*b>>2);W.uniformMatrix4fv(N[a],!!c,e)}},mc:function(a,b,c,d){W.uniformMatrix4x2fv(N[a],!!c,w,d>>2,8*b)},kc:function(a,b,c,d){W.uniformMatrix4x3fv(N[a],!!c,w,d>>2,12*b)},$c:function(a){W.useProgram(M[a])},_c:function(a){W.validateProgram(M[a])},
Zc:function(a,b){W.vertexAttrib1f(a,b)},Yc:function(a,b){W.vertexAttrib1f(a,w[b>>2])},Xc:function(a,b,c){W.vertexAttrib2f(a,b,c)},Wc:function(a,b){W.vertexAttrib2f(a,w[b>>2],w[b+4>>2])},Vc:function(a,b,c,d){W.vertexAttrib3f(a,b,c,d)},Uc:function(a,b){W.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},Tc:function(a,b,c,d,e){W.vertexAttrib4f(a,b,c,d,e)},Sc:function(a,b){W.vertexAttrib4f(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},Za:function(a,b){W.vertexAttribDivisor(a,b)},fa:function(a,b){W.vertexAttribDivisor(a,
b)},Nc:function(a,b){W.vertexAttribDivisor(a,b)},Oc:function(a,b){W.vertexAttribDivisor(a,b)},Ja:function(a,b){W.vertexAttribDivisor(a,b)},Ub:function(a,b,c,d,e){W.vertexAttribI4i(a,b,c,d,e)},Sb:function(a,b){W.vertexAttribI4i(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},Tb:function(a,b,c,d,e){W.vertexAttribI4ui(a,b,c,d,e)},Rb:function(a,b){W.vertexAttribI4ui(a,D[b>>2],D[b+4>>2],D[b+8>>2],D[b+12>>2])},Xb:function(a,b,c,d,e){W.vertexAttribIPointer(a,b,c,d,e)},Qc:function(a,b,c,d,e,f){W.vertexAttribPointer(a,
b,c,!!d,e,f)},Pc:function(a,b,c,d){W.viewport(a,b,c,d)},mb:function(a,b,c,d){W.waitSync(pc[a],b,(c>>>0)+4294967296*d)},f:function(){return 0},za:function(a,b,c){y.copyWithin(a,b,b+c)},d:function(a){a>>>=0;var b=y.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{xa.grow(Math.min(2147483648,d)-Ga.byteLength+65535>>>16);Ia();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Aa:function(a,
b,c,d,e){a=F.get(a);Ad(a,b,c,d,e)},e:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Ea:function(a){for(var b=L();L()-b<a;);},Ca:function(a,b){try{var c=0;Cd().forEach(function(d,e){var f=b+c;e=u[a+4*e>>2]=f;for(f=0;f<d.length;++f)r[e++>>0]=d.charCodeAt(f);r[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof K&&d instanceof H||m(d),d.lf}},Da:function(a,b){try{var c=Cd();u[a>>2]=c.length;var d=0;c.forEach(function(e){d+=
e.length+1});u[b>>2]=d;return 0}catch(e){return"undefined"!==typeof K&&e instanceof H||m(e),e.lf}},k:function(a){le(a)},o:function(a){try{var b=cc(a);Rb(b);return 0}catch(c){return"undefined"!==typeof K&&c instanceof H||m(c),c.lf}},Fa:function(a,b,c,d){try{a:{for(var e=cc(a),f=a=0;f<c;f++){var h=u[b+(8*f+4)>>2],l=e,n=u[b+8*f>>2],t=h,x=void 0,z=r;if(0>t||0>x)throw new H(28);if(null===l.fd)throw new H(8);if(1===(l.flags&2097155))throw new H(8);if(16384===(l.node.mode&61440))throw new H(31);if(!l.ef.read)throw new H(28);
var C="undefined"!==typeof x;if(!C)x=l.position;else if(!l.seekable)throw new H(70);var E=l.ef.read(l,z,n,t,x);C||(l.position+=E);var R=E;if(0>R){var Fb=-1;break a}a+=R;if(R<h)break}Fb=a}u[d>>2]=Fb;return 0}catch(rc){return"undefined"!==typeof K&&rc instanceof H||m(rc),rc.lf}},Ha:function(a,b,c,d,e){try{var f=cc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Sb(f,a,d);va=[f.position>>>0,(v=f.position,1<=+Math.abs(v)?0<v?(Math.min(+Math.floor(v/4294967296),4294967295)|
0)>>>0:~~+Math.ceil((v-+(~~v>>>0))/4294967296)>>>0:0)];u[e>>2]=va[0];u[e+4>>2]=va[1];f.Sf&&0===a&&0===d&&(f.Sf=null);return 0}catch(h){return"undefined"!==typeof K&&h instanceof H||m(h),h.lf}},n:function(a,b,c,d){try{a:{for(var e=cc(a),f=a=0;f<c;f++){var h=Tb(e,r,u[b+8*f>>2],u[b+(8*f+4)>>2]);if(0>h){var l=-1;break a}a+=h}l=a}u[d>>2]=l;return 0}catch(n){return"undefined"!==typeof K&&n instanceof H||m(n),n.lf}},j:function(a){var b=Date.now();u[a>>2]=b/1E3|0;u[a+4>>2]=b%1E3*1E3|0;return 0},He:function(a,
b,c,d){var e;for(e=0;e<X.length&&null!==X[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var f=e+1;if(0>=a||0>=b)f=0;else{d?md():yd(a,b);for(e=0;e<X.length&&null==X[e];e++);d=0<Fd[139265];e==X.length&&(d?g.tf=id(g.canvas,!0,!0,{antialias:1<Fd[135181],depth:0<Fd[135173],stencil:0<Fd[135174],alpha:0<Fd[135172]}):bd());!g.tf&&d?f=0:(a=new Ed(f,a,b,c),f-1==X.length?X.push(a):X[f-1]=a,Y=a,f=a.id)}return f},z:function(){Fd=Id},Gc:function(a){a:{if(a=Gd(a)){a.mg&&F.get(a.mg)(a.id);
X[a.id-1]=null;Y.id==a.id&&(Y=null);for(a=0;a<X.length;a++)if(null!==X[a]){a=void 0;break a}g.tf=void 0}a=void 0}return a},ad:function(a,b,c){q(b,sd,"double");q(c,td,"double")},Rc:function(a,b,c){var d=0,e=0;if(a=Gd(a))d=a.width,e=a.height;b&&q(b,d,"i32");c&&q(c,e,"i32")},a:function(a){return me(a)},K:function(){if(X)return 1;L();Fd=Id;X=[];Y=null;window.addEventListener("gamepadconnected",Nd,!0);window.addEventListener("gamepaddisconnected",Pd,!0);window.addEventListener("keydown",Qd,!0);window.addEventListener("keypress",
Ld,!0);window.addEventListener("keyup",Rd,!0);window.addEventListener("blur",Sd,!0);g.canvas.addEventListener("touchmove",Td,!0);g.canvas.addEventListener("touchstart",Xd,!0);g.canvas.addEventListener("touchcancel",Yd,!0);g.canvas.addEventListener("touchend",Yd,!0);g.canvas.addEventListener("mousemove",Td,!0);g.canvas.addEventListener("mousedown",Xd,!0);g.canvas.addEventListener("mouseup",Yd,!0);g.canvas.addEventListener("wheel",Zd,!0);g.canvas.addEventListener("mousewheel",Zd,!0);g.canvas.addEventListener("mouseenter",
Ud,!0);g.canvas.addEventListener("mouseleave",Vd,!0);g.canvas.addEventListener("drop",de,!0);g.canvas.addEventListener("dragover",ee,!0);xd.push(function(a,b){if(Y){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Y.jg=Y.x,Y.kg=Y.y,Y.ig=Y.width,Y.hg=Y.height,Y.x=Y.y=0,Y.width=screen.width,Y.height=screen.height,Y.Rf=!0):1==Y.Rf?(Y.x=Y.jg,Y.y=Y.kg,Y.width=Y.ig,Y.height=Y.hg,Y.Rf=!1):Y.width!=a||Y.height!=b?(Y.width=a,Y.height=b):c=!1;c&&(yd(Y.width,
Y.height,!0),Y&&Y.ng&&F.get(Y.ng)(Y.id,Y.width,Y.height),Y&&Y.Bf&&F.get(Y.Bf)(Y.id,Y.width,Y.height))}});return 1},we:function(){},pa:function(){},Sd:function(a,b){if(a=Gd(a)){var c=a.Af;a.Af=b;b=c}else b=null;return b},V:function(a){var b=Hd;Hd=a;return b},be:function(a,b){a=Gd(a);if(!a)return null;var c=a.Bf;a.Bf=b;return c},Hd:function(a,b){if(a=Gd(a)){var c=a.Cf;a.Cf=b;b=c}else b=null;return b},ld:function(a,b){if(a=Gd(a)){var c=a.Hf;a.Hf=b;b=c}else b=null;return b},wd:function(a,b){if(a=Gd(a)){var c=
a.Jf;a.Jf=b;b=c}else b=null;return b},ea:function(){},vc:function(){window.removeEventListener("gamepadconnected",Nd,!0);window.removeEventListener("gamepaddisconnected",Pd,!0);window.removeEventListener("keydown",Qd,!0);window.removeEventListener("keypress",Ld,!0);window.removeEventListener("keyup",Rd,!0);window.removeEventListener("blur",Sd,!0);g.canvas.removeEventListener("touchmove",Td,!0);g.canvas.removeEventListener("touchstart",Xd,!0);g.canvas.removeEventListener("touchcancel",Yd,!0);g.canvas.removeEventListener("touchend",
Yd,!0);g.canvas.removeEventListener("mousemove",Td,!0);g.canvas.removeEventListener("mousedown",Xd,!0);g.canvas.removeEventListener("mouseup",Yd,!0);g.canvas.removeEventListener("wheel",Zd,!0);g.canvas.removeEventListener("mousewheel",Zd,!0);g.canvas.removeEventListener("mouseenter",Ud,!0);g.canvas.removeEventListener("mouseleave",Vd,!0);g.canvas.removeEventListener("drop",de,!0);g.canvas.removeEventListener("dragover",ee,!0);g.canvas.width=g.canvas.height=1;Y=X=null},h:function(a,b){Fd[a]=b},m:function(){},
g:function(){return 0}};
(function(){function a(e){g.asm=e.exports;xa=g.asm.Se;Ia();F=g.asm.Te;Pa--;g.monitorRunDependencies&&g.monitorRunDependencies(Pa);0==Pa&&(null!==Qa&&(clearInterval(Qa),Qa=null),Ra&&(e=Ra,Ra=null,e()))}function b(e){a(e.instance)}function c(e){return Wa().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){p("failed to asynchronously prepare wasm: "+f);m(f)})}var d={a:ne};Pa++;g.monitorRunDependencies&&g.monitorRunDependencies(Pa);if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return p("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){return ta||"function"!==typeof WebAssembly.instantiateStreaming||Ta()||Sa("file://")||"function"!==typeof fetch?c(b):fetch(G,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){p("wasm streaming compile failed: "+f);p("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Na=g.___wasm_call_ctors=function(){return(Na=g.___wasm_call_ctors=g.asm.Ue).apply(null,arguments)},ce=g._free=function(){return(ce=g._free=g.asm.Ve).apply(null,arguments)},Aa=g._malloc=function(){return(Aa=g._malloc=g.asm.We).apply(null,arguments)};g._main=function(){return(g._main=g.asm.Xe).apply(null,arguments)};
var ie=g.___errno_location=function(){return(ie=g.___errno_location=g.asm.Ye).apply(null,arguments)},me=g._emscripten_GetProcAddress=function(){return(me=g._emscripten_GetProcAddress=g.asm.Ze).apply(null,arguments)},ke=g._memset=function(){return(ke=g._memset=g.asm._e).apply(null,arguments)},Fa=g.stackAlloc=function(){return(Fa=g.stackAlloc=g.asm.$e).apply(null,arguments)},je=g._memalign=function(){return(je=g._memalign=g.asm.af).apply(null,arguments)};
g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.bf).apply(null,arguments)};g.dynCall_ji=function(){return(g.dynCall_ji=g.asm.cf).apply(null,arguments)};var oe;function pa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ra=function pe(){oe||qe();oe||(Ra=pe)};
function qe(a){function b(){if(!oe&&(oe=!0,g.calledRun=!0,!ya)){g.noFSInit||Vb||(Vb=!0,Ub(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?Yb("stdin",g.stdin):Ob("/dev/tty","/dev/stdin"),g.stdout?Yb("stdout",null,g.stdout):Ob("/dev/tty","/dev/stdout"),g.stderr?Yb("stderr",null,g.stderr):Ob("/dev/tty1","/dev/stderr"),Pb("/dev/stdin",0),Pb("/dev/stdout",1),Pb("/dev/stderr",1));$a(Ka);wb=!1;$a(La);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(re){var c=a,d=g._main;c=c||[];var e=
c.length+1,f=Fa(4*(e+1));u[f>>2]=Ea(da);for(var h=1;h<e;h++)u[(f>>2)+h]=Ea(c[h-1]);u[(f>>2)+e]=0;try{var l=d(e,f);le(l,!0)}catch(n){n instanceof pa||("unwind"==n?noExitRuntime=!0:((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),p("exception thrown: "+c),ea(1,n)))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=g.postRun.shift(),Ma.unshift(c);$a(Ma)}}a=a||ca;if(!(0<Pa)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Oa();
$a(Ja);0<Pa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=qe;function le(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(g.onExit)g.onExit(a);ya=!0}ea(a,new pa(a))}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var re=!0;g.noInitialRun&&(re=!1);noExitRuntime=!0;qe();
