
var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa={},ba;for(ba in g)g.hasOwnProperty(ba)&&(aa[ba]=g[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;ha="function"===typeof importScripts;ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ja=!fa&&!ia&&!ha;var k="",ka,la,ma,na;
if(ia)k=ha?require("path").dirname(k)+"/":__dirname+"/",ka=function(a,b){ma||(ma=require("fs"));na||(na=require("path"));a=na.normalize(a);return ma.readFileSync(a,b?null:"utf8")},la=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof oa))throw a;}),process.on("unhandledRejection",
m),ea=function(a){process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ja)"undefined"!=typeof read&&(ka=function(a){return read(a)}),la=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||ha)ha?k=self.location.href:"undefined"!==typeof document&&document.currentScript&&(k=document.currentScript.src),k=0!==k.indexOf("blob:")?k.substr(0,k.lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(la=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var pa=g.print||console.log.bind(console),p=g.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(g[ba]=aa[ba]);aa=null;g.arguments&&(ca=g.arguments);g.thisProgram&&(da=g.thisProgram);g.quit&&(ea=g.quit);function qa(a){ra||(ra={});ra[a]||(ra[a]=1,p(a))}var ra,sa;g.wasmBinary&&(sa=g.wasmBinary);var noExitRuntime;g.noExitRuntime&&(noExitRuntime=g.noExitRuntime);"object"!==typeof WebAssembly&&m("no native wasm support detected");
function q(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":r[a>>0]=b;break;case "i8":r[a>>0]=b;break;case "i16":ta[a>>1]=b;break;case "i32":u[a>>2]=b;break;case "i64":ua=[b>>>0,(v=b,1<=+Math.abs(v)?0<v?(Math.min(+Math.floor(v/4294967296),4294967295)|0)>>>0:~~+Math.ceil((v-+(~~v>>>0))/4294967296)>>>0:0)];u[a>>2]=ua[0];u[a+4>>2]=ua[1];break;case "float":w[a>>2]=b;break;case "double":va[a>>3]=b;break;default:m("invalid type for setValue: "+c)}}var wa,xa=!1;
function assert(a,b){a||m("Assertion failed: "+b)}function ya(a){var b=za(a.length);a.subarray||a.slice?y.set(a,b):y.set(new Uint8Array(a),b);return b}var Aa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ba(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Aa)return Aa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function A(a,b){return a?Ba(y,a,b):""}
function B(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function Ca(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Da(a){var b=Ca(a)+1,c=Ea(b);B(a,r,c,b);return c}var Fa,r,y,ta,Ga,u,D,w,va;
function Ha(){var a=wa.buffer;Fa=a;g.HEAP8=r=new Int8Array(a);g.HEAP16=ta=new Int16Array(a);g.HEAP32=u=new Int32Array(a);g.HEAPU8=y=new Uint8Array(a);g.HEAPU16=Ga=new Uint16Array(a);g.HEAPU32=D=new Uint32Array(a);g.HEAPF32=w=new Float32Array(a);g.HEAPF64=va=new Float64Array(a)}var F,Ia=[],Ja=[],Ka=[],La=[];function Ma(){var a=g.preRun.shift();Ia.unshift(a)}var Na=0,Oa=null,Pa=null;g.preloadedImages={};g.preloadedAudios={};
function m(a){if(g.onAbort)g.onAbort(a);p(a);xa=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Qa(a){var b=Ra;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Sa(){return Qa("data:application/octet-stream;base64,")}var Ra="index.wasm";if(!Sa()){var Ta=Ra;Ra=g.locateFile?g.locateFile(Ta,k):k+Ta}
function Ua(){var a=Ra;try{if(a==Ra&&sa)return new Uint8Array(sa);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}catch(b){m(b)}}function Va(){return sa||!fa&&!ha||"function"!==typeof fetch||Qa("file://")?Promise.resolve().then(function(){return Ua()}):fetch(Ra,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Ra+"'";return a.arrayBuffer()}).catch(function(){return Ua()})}
var v,ua,Xa={16263:function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?1:0},16429:function(){return"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?1:0},16655:function(a){var b=g.SDL2;if(a){void 0!==b.capture.xf&&clearTimeout(b.capture.xf);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.jf&&(b.capture.jf.onaudioprocess=function(){},b.capture.jf.disconnect(),b.capture.jf=void 0);void 0!==b.capture.Df&&(b.capture.Df.disconnect(),b.capture.Df=void 0);void 0!==b.capture.Kf&&(b.capture.Kf=void 0);b.capture=void 0}else void 0!=b.audio.jf&&(b.audio.jf.disconnect(),b.audio.jf=void 0),b.audio=void 0;void 0!==b.hf&&void 0===b.audio&&void 0===b.capture&&(b.hf.close(),b.hf=void 0)},17827:function(a){"undefined"===typeof g.SDL2&&(g.SDL2={});var b=g.SDL2;
a?b.capture={}:b.audio={};b.hf||("undefined"!==typeof AudioContext?b.hf=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.hf=new webkitAudioContext),b.hf&&Wa(b.hf));return void 0===b.hf?-1:0},18380:function(){return g.SDL2.hf.sampleRate},18450:function(a,b,c,d){function e(){}function f(l){void 0!==h.capture.xf&&(clearTimeout(h.capture.xf),h.capture.xf=void 0);h.capture.Df=h.hf.createMediaStreamSource(l);h.capture.jf=h.hf.createScriptProcessor(b,a,1);h.capture.jf.onaudioprocess=function(n){void 0!==
h&&void 0!==h.capture&&(n.outputBuffer.getChannelData(0).fill(0),h.capture.Nf=n.inputBuffer,n=[d],F.get(c).apply(null,n))};h.capture.Df.connect(h.capture.jf);h.capture.jf.connect(h.hf.destination);h.capture.stream=l}var h=g.SDL2;h.capture.Kf=h.hf.createBuffer(a,b,h.hf.sampleRate);h.capture.Kf.getChannelData(0).fill(0);h.capture.xf=setTimeout(function(){h.capture.Nf=h.capture.Kf;var l=[d];F.get(c).apply(null,l)},b/h.hf.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?
navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},20102:function(a,b,c,d){var e=g.SDL2;e.audio.jf=e.hf.createScriptProcessor(b,0,a);e.audio.jf.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Zf=f.outputBuffer,f=[d],F.get(c).apply(null,f))};e.audio.jf.connect(e.hf.destination)},20512:function(a,b){for(var c=g.SDL2,d=c.audio.Zf.numberOfChannels,e=0;e<d;++e){var f=c.audio.Zf.getChannelData(e);
if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var h=0;h<b;++h)f[h]=w[a+(h*d+e<<2)>>2]}},20992:function(a,b){for(var c=g.SDL2,d=c.capture.Nf.numberOfChannels,e=0;e<d;++e){var f=c.capture.Nf.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var h=0;h<b;++h)q(a+4*h,f[h],"float");else for(h=0;h<b;++h)q(a+4*
(h*d+e),f[h],"float")}}};function Ya(a,b,c){a.addEventListener(b,c,{once:!0})}function Wa(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&Ya(d,c,function(){"suspended"===a.state&&a.resume()})})})}function Za(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.cg;"number"===typeof c?void 0===b.yf?F.get(c)():F.get(c)(b.yf):c(void 0===b.yf?null:b.yf)}}}
function $a(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function ab(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=$a(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function bb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function cb(a){if("/"===a)return"/";a=ab(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function db(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){m("randomDevice")}}
function eb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=$a(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var fb=[];function gb(a,b){fb[a]={input:[],output:[],uf:b};hb(a,ib)}
var ib={open:function(a){var b=fb[a.node.rdev];if(!b)throw new G(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.uf.flush(a.tty)},flush:function(a){a.tty.uf.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.uf.dg)throw new G(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.uf.dg(a.tty)}catch(l){throw new G(29);}if(void 0===h&&0===e)throw new G(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.uf.Uf)throw new G(60);
try{for(var e=0;e<d;e++)a.tty.uf.Uf(a.tty,b[c+e])}catch(f){throw new G(29);}d&&(a.node.timestamp=Date.now());return e}},kb={dg:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.qg?Buffer.qg(256):new Buffer(256),d=0;try{d=ma.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=jb(b,!0)}return a.input.shift()},Uf:function(a,b){null===b||10===b?(pa(Ba(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(pa(Ba(a.output,0)),a.output=[])}},lb={Uf:function(a,b){null===b||10===b?(p(Ba(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(p(Ba(a.output,0)),a.output=[])}},H={nf:null,qf:function(){return H.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new G(63);H.nf||(H.nf={dir:{node:{rf:H.ff.rf,pf:H.ff.pf,lookup:H.ff.lookup,Ef:H.ff.Ef,rename:H.ff.rename,unlink:H.ff.unlink,rmdir:H.ff.rmdir,readdir:H.ff.readdir,symlink:H.ff.symlink},stream:{sf:H.ef.sf}},file:{node:{rf:H.ff.rf,pf:H.ff.pf},stream:{sf:H.ef.sf,read:H.ef.read,write:H.ef.write,Wf:H.ef.Wf,Ff:H.ef.Ff,If:H.ef.If}},link:{node:{rf:H.ff.rf,pf:H.ff.pf,readlink:H.ff.readlink},stream:{}},Yf:{node:{rf:H.ff.rf,
pf:H.ff.pf},stream:mb}});c=nb(a,b,c,d);16384===(c.mode&61440)?(c.ff=H.nf.dir.node,c.ef=H.nf.dir.stream,c.df={}):32768===(c.mode&61440)?(c.ff=H.nf.file.node,c.ef=H.nf.file.stream,c.gf=0,c.df=null):40960===(c.mode&61440)?(c.ff=H.nf.link.node,c.ef=H.nf.link.stream):8192===(c.mode&61440)&&(c.ff=H.nf.Yf.node,c.ef=H.nf.Yf.stream);c.timestamp=Date.now();a&&(a.df[b]=c);return c},Mg:function(a){if(a.df&&a.df.subarray){for(var b=[],c=0;c<a.gf;++c)b.push(a.df[c]);return b}return a.df},Ng:function(a){return a.df?
a.df.subarray?a.df.subarray(0,a.gf):new Uint8Array(a.df):new Uint8Array(0)},$f:function(a,b){var c=a.df?a.df.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.df,a.df=new Uint8Array(b),0<a.gf&&a.df.set(c.subarray(0,a.gf),0))},Cg:function(a,b){if(a.gf!=b)if(0==b)a.df=null,a.gf=0;else{if(!a.df||a.df.subarray){var c=a.df;a.df=new Uint8Array(b);c&&a.df.set(c.subarray(0,Math.min(b,a.gf)))}else if(a.df||(a.df=[]),a.df.length>b)a.df.length=b;else for(;a.df.length<b;)a.df.push(0);
a.gf=b}},ff:{rf:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.gf:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.og=4096;b.blocks=Math.ceil(b.size/b.og);return b},pf:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==
b.size&&H.Cg(a,b.size)},lookup:function(){throw ob[44];},Ef:function(a,b,c,d){return H.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=pb(b,c)}catch(f){}if(d)for(var e in d.df)throw new G(55);}delete a.parent.df[a.name];a.name=c;b.df[c]=a;a.parent=b},unlink:function(a,b){delete a.df[b]},rmdir:function(a,b){var c=pb(a,b),d;for(d in c.df)throw new G(55);delete a.df[b]},readdir:function(a){var b=[".",".."],c;for(c in a.df)a.df.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,
b,c){a=H.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new G(28);return a.link}},ef:{read:function(a,b,c,d,e){var f=a.node.df;if(e>=a.node.gf)return 0;a=Math.min(a.node.gf-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===r.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.df||a.df.subarray)){if(f)return a.df=b.subarray(c,c+d),a.gf=d;
if(0===a.gf&&0===e)return a.df=b.slice(c,c+d),a.gf=d;if(e+d<=a.gf)return a.df.set(b.subarray(c,c+d),e),d}H.$f(a,e+d);if(a.df.subarray&&b.subarray)a.df.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.df[e+f]=b[c+f];a.gf=Math.max(a.gf,e+d);return d},sf:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.gf);if(0>b)throw new G(28);return b},Wf:function(a,b,c){H.$f(a.node,b+c);a.node.gf=Math.max(a.node.gf,b+c)},Ff:function(a,b,c,d,e,f){assert(0===b);if(32768!==(a.node.mode&
61440))throw new G(43);a=a.node.df;if(f&2||a.buffer!==Fa){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=za(f);c<f;)r[b+c++]=0;c=b;if(!c)throw new G(48);r.set(a,c)}else d=!1,c=a.byteOffset;return{Ag:c,Mf:d}},If:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new G(43);if(e&2)return 0;H.ef.write(a,b,0,d,c,!1);return 0}}},qb=null,rb={},sb=[],tb=1,ub=null,vb=!0,wb={},G=null,ob={};
function xb(a,b){a=eb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={bg:!0,Vf:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Vf)throw new G(32);a=$a(a.split("/").filter(function(h){return!!h}),!1);var e=qb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=pb(e,a[d]);c=ab(c+"/"+a[d]);e.Gf&&(!f||f&&b.bg)&&(e=e.Gf.root);if(!f||b.ag)for(f=0;40960===(e.mode&61440);)if(e=yb(c),c=eb(bb(c),e),e=xb(c,{Vf:b.Vf}).node,40<f++)throw new G(32);}return{path:c,node:e}}
function zb(a){for(var b;;){if(a===a.parent)return a=a.qf.fg,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Ab(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%ub.length}function pb(a,b){var c;if(c=(c=Bb(a,"x"))?c:a.ff.lookup?0:2)throw new G(c,a);for(c=ub[Ab(a.id,b)];c;c=c.yg){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ff.lookup(a,b)}
function nb(a,b,c,d){a=new Cb(a,b,c,d);b=Ab(a.parent.id,a.name);a.yg=ub[b];return ub[b]=a}var Db={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Eb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Bb(a,b){if(vb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Gb(a,b){try{return pb(a,b),20}catch(c){}return Bb(a,"wx")}
function Hb(a){var b=4096;for(a=a||0;a<=b;a++)if(!sb[a])return a;throw new G(33);}function Ib(a,b){Jb||(Jb=function(){},Jb.prototype={});var c=new Jb,d;for(d in a)c[d]=a[d];a=c;b=Hb(b);a.fd=b;return sb[b]=a}var mb={open:function(a){a.ef=rb[a.node.rdev].ef;a.ef.open&&a.ef.open(a)},sf:function(){throw new G(70);}};function hb(a,b){rb[a]={ef:b}}
function Kb(a,b){var c="/"===b,d=!b;if(c&&qb)throw new G(10);if(!c&&!d){var e=xb(b,{bg:!1});b=e.path;e=e.node;if(e.Gf)throw new G(10);if(16384!==(e.mode&61440))throw new G(54);}b={type:a,Ug:{},fg:b,xg:[]};a=a.qf(b);a.qf=b;b.root=a;c?qb=a:e&&(e.Gf=b,e.qf&&e.qf.xg.push(b))}function Lb(a,b,c){var d=xb(a,{parent:!0}).node;a=cb(a);if(!a||"."===a||".."===a)throw new G(28);var e=Gb(d,a);if(e)throw new G(e);if(!d.ff.Ef)throw new G(63);return d.ff.Ef(d,a,b,c)}function I(a){Lb(a,16895,0)}
function Mb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Lb(a,b|8192,c)}function Nb(a,b){if(!eb(a))throw new G(44);var c=xb(b,{parent:!0}).node;if(!c)throw new G(44);b=cb(b);var d=Gb(c,b);if(d)throw new G(d);if(!c.ff.symlink)throw new G(63);c.ff.symlink(c,b,a)}function yb(a){a=xb(a).node;if(!a)throw new G(44);if(!a.ff.readlink)throw new G(28);return eb(zb(a.parent),a.ff.readlink(a))}
function Ob(a,b,c,d){if(""===a)throw new G(44);if("string"===typeof b){var e=Db[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=ab(a);try{f=xb(a,{ag:!(b&131072)}).node}catch(l){}}e=!1;if(b&64)if(f){if(b&128)throw new G(20);}else f=Lb(a,c,0),e=!0;if(!f)throw new G(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new G(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==Eb(b)||b&512)?31:Bb(f,Eb(b)):44))throw new G(c);if(b&512){c=f;var h;"string"===typeof c?h=xb(c,{ag:!0}).node:h=c;if(!h.ff.pf)throw new G(63);if(16384===(h.mode&61440))throw new G(31);if(32768!==(h.mode&61440))throw new G(28);if(c=Bb(h,"w"))throw new G(c);h.ff.pf(h,{size:0,timestamp:Date.now()})}b&=-131713;d=Ib({node:f,path:zb(f),flags:b,seekable:!0,position:0,ef:f.ef,Eg:[],error:!1},d);d.ef.open&&d.ef.open(d);!g.logReadFiles||b&1||(Pb||(Pb={}),a in Pb||(Pb[a]=1,p("FS.trackingDelegate error on read file: "+
a)));try{wb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),wb.onOpenFile(a,f))}catch(l){p("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+l.message)}return d}function Qb(a){if(null===a.fd)throw new G(8);a.Sf&&(a.Sf=null);try{a.ef.close&&a.ef.close(a)}catch(b){throw b;}finally{sb[a.fd]=null}a.fd=null}
function Rb(a,b,c){if(null===a.fd)throw new G(8);if(!a.seekable||!a.ef.sf)throw new G(70);if(0!=c&&1!=c&&2!=c)throw new G(28);a.position=a.ef.sf(a,b,c);a.Eg=[]}
function Sb(a,b,c,d,e){var f=void 0;if(0>d||0>f)throw new G(28);if(null===a.fd)throw new G(8);if(0===(a.flags&2097155))throw new G(8);if(16384===(a.node.mode&61440))throw new G(31);if(!a.ef.write)throw new G(28);a.seekable&&a.flags&1024&&Rb(a,0,2);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new G(70);b=a.ef.write(a,b,c,d,f,e);h||(a.position+=b);try{if(a.path&&wb.onWriteToFile)wb.onWriteToFile(a.path)}catch(l){p("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
l.message)}return b}function Tb(){G||(G=function(a,b){this.node=b;this.Dg=function(c){this.lf=c};this.Dg(a);this.message="FS error"},G.prototype=Error(),G.prototype.constructor=G,[44].forEach(function(a){ob[a]=new G(a);ob[a].stack="<generic error, no stack>"}))}var Ub;function Vb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function Wb(){var a="/";a="string"===typeof a?a:zb(a);for(var b=[".glfw_dropped_files"].reverse();b.length;){var c=b.pop();if(c){a=ab(a+"/"+c);try{I(a)}catch(d){}}}}
function Xb(a,b,c){a=ab("/dev/"+a);var d=Vb(!!b,!!c);Yb||(Yb=64);var e=Yb++<<8|0;hb(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,h,l,n){for(var t=0,x=0;x<n;x++){try{var z=b()}catch(C){throw new G(29);}if(void 0===z&&0===t)throw new G(6);if(null===z||void 0===z)break;t++;h[l+x]=z}t&&(f.node.timestamp=Date.now());return t},write:function(f,h,l,n){for(var t=0;t<n;t++)try{c(h[l+t])}catch(x){throw new G(29);}n&&(f.node.timestamp=Date.now());return t}});
Mb(a,d,e)}var Yb,J={},Jb,Pb,Zb={},$b=void 0;function ac(){$b+=4;return u[$b-4>>2]}function bc(a){a=sb[a];if(!a)throw new G(8);return a}var K;ia?K=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?K=dateNow:K=function(){return performance.now()};
function cc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function dc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function ec(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var fc=1,hc=[],L=[],ic=[],jc=[],kc=[],M=[],N=[],O=[],lc=[],P=[],mc=[],Q=[],nc=[],oc=[],pc={},rc={},sc={},tc=4;function S(a){uc||(uc=a)}function vc(a){for(var b=fc++,c=a.length;c<b;c++)a[c]=null;return b}function wc(a,b){if(a=1<b.eg?a.getContext("webgl2",b):a.getContext("webgl",b)){var c=vc(lc),d={Og:c,attributes:b,version:b.eg,Lf:a};a.canvas&&(a.canvas.Gg=d);lc[c]=d;("undefined"===typeof b.rg||b.rg)&&xc(d);b=c}else b=0;return b}
function xc(a){a||(a=T);if(!a.tg){a.tg=!0;var b=a.Lf;cc(b);dc(b);ec(b);b.Kg=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Pg=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");b.kf=b.getExtension("EXT_disjoint_timer_query");b.Sg=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}var yc={},uc,T,zc=[];
function U(a,b,c,d){for(var e=0;e<a;e++){var f=V[c](),h=f&&vc(d);f?(f.name=h,d[h]=f):S(1282);u[b+4*e>>2]=h}}function Ac(a,b,c,d,e,f,h,l){b=L[b];if(a=V[a](b,c))d=l&&B(a.name,y,l,d),e&&(u[e>>2]=d),f&&(u[f>>2]=a.size),h&&(u[h>>2]=a.type)}function Bc(a,b){D[a>>2]=b;D[a+4>>2]=(b-D[a>>2])/4294967296}
function Cc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&S(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=V.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>T.version){S(1282);return}d=2*(V.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>T.version){S(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=V.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":S(1280);return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:S(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:u[b+4*a>>2]=e[a];break;case 2:w[b+4*a>>2]=e[a];break;case 4:r[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){S(1280);
p("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:S(1280);p("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Bc(b,d);break;case 0:u[b>>2]=d;break;case 2:w[b>>2]=d;break;case 4:r[b>>0]=d?1:0}}else S(1281)}
function Dc(a,b,c,d){if(c){b=V.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:S(1280);return}else if(b instanceof WebGLBuffer)a=b.name|0;else{S(1280);return}break;default:S(1280);return}switch(d){case 1:Bc(c,a);break;case 0:u[c>>2]=a;break;case 2:w[c>>2]=a;break;case 4:r[c>>0]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else S(1281)}
function Ec(a){var b=Ca(a)+1,c=za(b);B(a,y,c,b);return c}function Fc(a,b,c,d){if(c)if(a=V.getUniform(L[a],M[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b]}else S(1281)}
function Gc(a,b,c,d){if(c)if(a=V.getVertexAttrib(a,b),34975==b)u[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:u[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b];break;case 5:u[c+4*b>>2]=Math.fround(a[b])}else S(1281)}function Hc(a){a-=5120;return 0==a?r:1==a?y:2==a?ta:4==a?u:6==a?w:5==a||28922==a||28520==a||30779==a||30782==a?D:Ga}
function Ic(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function Jc(a,b,c,d,e){a=Hc(a);var f=Ic(a),h=tc;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<f)+h-1&-h)>>f)}var Kc=[],Lc=[],Mc=null,Nc=0,Oc=null,Pc=0,Qc=0,Rc=0,Sc=0,Tc=[],Uc={},Vc,Wc,Xc,Yc=!1,Zc=!1,$c=[];
function ad(){function a(){Zc=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!bd){bd=!0;try{cd=!0}catch(c){cd=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}dd="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:cd?null:console.log("warning: no BlobBuilder");
ed="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;g.gg||"undefined"!==typeof ed||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.gg=!0);g.preloadPlugins.push({canHandle:function(c){return!g.gg&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var h=null;if(cd)try{h=new Blob([c],{type:fd(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:fd(d)}))}catch(t){qa("Blob constructor present but fails: "+
t+"; falling back to blob builder")}h||(h=new dd,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var l=ed.createObjectURL(h),n=new Image;n.onload=function(){assert(n.complete,"Image "+d+" could not be decoded");var t=document.createElement("canvas");t.width=n.width;t.height=n.height;t.getContext("2d").drawImage(n,0,0);g.preloadedImages[d]=t;ed.revokeObjectURL(l);e&&e(c)};n.onerror=function(){console.log("Image "+l+" could not be decoded");f&&f()};n.src=l}});g.preloadPlugins.push({canHandle:function(c){return!g.Tg&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function h(z){n||(n=!0,g.preloadedAudios[d]=z,e&&e(c))}function l(){n||(n=!0,g.preloadedAudios[d]=new Audio,f&&f())}var n=!1;if(cd){try{var t=new Blob([c],{type:fd(d)})}catch(z){return l()}t=ed.createObjectURL(t);var x=new Audio;x.addEventListener("canplaythrough",function(){h(x)},!1);x.onerror=function(){if(!n){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var z="",C=0,E=0,
R=0;R<c.length;R++)for(C=C<<8|c[R],E+=8;6<=E;){var Fb=C>>E-6&63;E-=6;z+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[Fb]}2==E?(z+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(C&3)<<4],z+="=="):4==E&&(z+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(C&15)<<2],z+="=");x.src="data:audio/x-"+d.substr(-3)+";base64,"+z;h(x)}};x.src=t;gd(function(){h(x)})}else return l()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&
b.addEventListener("click",function(c){!Zc&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function hd(a,b,c,d){if(b&&g.tf&&a==g.canvas)return g.tf;var e;if(b){var f={antialias:!1,alpha:!1,eg:"undefined"!==typeof WebGL2RenderingContext?2:1};if(d)for(var h in d)f[h]=d[h];if("undefined"!==typeof yc&&(e=wc(a,f)))var l=lc[e].Lf}else l=a.getContext("2d");if(!l)return null;c&&(b||assert("undefined"===typeof V,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.tf=l,b&&(T=lc[e],g.tf=V=T&&T.Lf),g.Vg=b,$c.forEach(function(n){n()}),ad());return l}
var id=!1,jd=void 0,kd=void 0;
function ld(a,b){function c(){Yc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=md,jd&&d.requestPointerLock(),Yc=!0,kd?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=D[SDL.screen>>2]|8388608),nd(g.canvas),od()):nd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),kd?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=D[SDL.screen>>2]&
-8388609),nd(g.canvas),od()):nd(d));if(g.onFullScreen)g.onFullScreen(Yc);if(g.onFullscreen)g.onFullscreen(Yc)}jd=a;kd=b;"undefined"===typeof jd&&(jd=!0);"undefined"===typeof kd&&(kd=!1);var d=g.canvas;id||(id=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function md(){if(!Yc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var pd=0;function qd(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===pd)pd=b+1E3/60;else for(;b+2>=pd;)pd+=1E3/60;setTimeout(a,Math.max(pd-b,0))}}function gd(a){noExitRuntime=!0;setTimeout(function(){xa||a()},1E4)}
function fd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var rd=0,sd=0,td=0,ud=0;
function vd(a){if(Zc)"mousemove"!=a.type&&"mozMovementX"in a?td=ud=0:(td=a.movementX||a.mozMovementX||a.webkitMovementX||0,ud=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(rd=SDL.Qg+td,sd=SDL.Rg+ud):(rd+=td,sd+=ud);else{var b=g.canvas.getBoundingClientRect(),c=g.canvas.width,d=g.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(f+b.top),e*=c/b.width,a*=d/b.height,td=e-rd,ud=a-sd,rd=e,sd=a)}}var wd=[];function od(){var a=g.canvas;wd.forEach(function(b){b(a.width,a.height)})}function xd(a,b,c){nd(g.canvas,a,b);c||od()}
function nd(a,b,c){b&&c?(a.Fg=b,a.sg=c):(b=a.Fg,c=a.sg);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}kd?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var bd,cd,dd,ed;
function yd(a,b){Qc=a;Rc=b;if(Oc)if(0==a)Mc=function(){var d=Math.max(0,Wc+b-K())|0;setTimeout(Xc,d)};else if(1==a)Mc=function(){qd(Xc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}Mc=function(){setImmediate(Xc)}}}
function zd(a,b,c,d,e){noExitRuntime=!0;assert(!Oc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Oc=a;Pc=d;var f=Nc;Xc=function(){if(!xa)if(0<Tc.length){var h=Date.now(),l=Tc.shift();l.cg(l.yf);if(Vc){var n=Vc,t=0==n%1?n-1:Math.floor(n);Vc=l.Jg?t:(8*n+(t+.5))/9}console.log('main loop blocker "'+l.name+'" took '+(Date.now()-h)+" ms");g.setStatus&&(h=g.statusMessage||
"Please wait...",l=Vc,n=Uc.Lg,l?l<n?g.setStatus(h+" ("+(n-l)+"/"+n+")"):g.setStatus(h):g.setStatus(""));f<Nc||setTimeout(Xc,0)}else if(!(f<Nc))if(Sc=Sc+1|0,1==Qc&&1<Rc&&0!=Sc%Rc)Mc();else{0==Qc&&(Wc=K());a:if(!(xa||g.preMainLoop&&!1===g.preMainLoop())){try{a()}catch(x){if(x instanceof oa||"unwind"==x)break a;x&&"object"===typeof x&&x.stack&&p("exception thrown: "+[x,x.stack]);throw x;}g.postMainLoop&&g.postMainLoop()}f<Nc||("object"===typeof SDL&&SDL.audio&&SDL.audio.Bg&&SDL.audio.Bg(),Mc())}};e||
(b&&0<b?yd(0,1E3/b):yd(1,1),Mc());if(c)throw"unwind";}var Ad={};function Bd(){if(!Cd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Ad)a[b]=Ad[b];var c=[];for(b in a)c.push(b+"="+a[b]);Cd=c}return Cd}var Cd;
function Dd(a,b,c,d){this.id=a;this.y=this.x=0;this.Rf=!1;this.kg=this.jg=0;this.width=b;this.height=c;this.ig=b;this.hg=c;this.title=d;this.attributes=W;this.buttons=0;this.keys=[];this.Pf=[];this.Xf=this.Cf=this.Qf=this.Jf=this.zf=this.Af=this.Hf=this.Bf=this.mg=this.ng=this.title=null}function Ed(a){return 0>=a||!X?null:X[a-1]}
var Fd=null,Y=null,X=null,W=null,Gd={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function Hd(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Id(){var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Jd(a){Y&&Y.Xf&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||F.get(Y.Xf)(Y.id,a))}
function Kd(a,b){if(Y){var c=Hd(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.Pf[a]=b;Y.Cf&&(d&&(b=2),F.get(Y.Cf)(Y.id,c,a,b,Id()))}}}function Ld(){Md()}function Nd(){Md()}function Od(a){Kd(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function Pd(a){Kd(a.keyCode,0)}function Qd(){if(Y)for(var a=0;a<Y.Pf.length;++a)Y.Pf[a]&&Kd(a,0)}function Rd(a){Y&&(vd(a),a.target==g.canvas&&Y.Af&&F.get(Y.Af)(Y.id,rd,sd))}function Sd(a){Y&&a.target==g.canvas&&Y.zf&&F.get(Y.zf)(Y.id,1)}
function Td(a){Y&&a.target==g.canvas&&Y.zf&&F.get(Y.zf)(Y.id,0)}function Ud(a,b){if(Y&&(vd(a),a.target==g.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Y.buttons&=~(1<<c);Y.Hf&&F.get(Y.Hf)(Y.id,c,b,Id())}}function Vd(a){Y&&Ud(a,1)}function Wd(a){Y&&Ud(a,0)}
function Xd(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":switch(a.deltaMode){case 0:break;case 1:break;case 2:break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}if(Y&&Y.Jf&&a.target==g.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;F.get(Y.Jf)(Y.id,b,c);a.preventDefault()}}var Yd={},Zd=null,$d=null;
function Md(){if(Sc!==$d||!Sc){Zd=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;$d=Sc;for(var a=0;a<Zd.length;++a){var b=Zd[a];if(b){Yd[a]||(console.log("glfw joystick connected:",a),Yd[a]={id:ya(jb(b.id)),Ig:b.buttons.length,Hg:b.axes.length,buttons:ya(Array(b.buttons.length)),axes:ya(Array(4*b.axes.length))});for(var c=Yd[a],d=0;d<b.buttons.length;++d)q(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)q(c.axes+4*d,b.axes[d],
"float")}else Yd[a]&&(console.log("glfw joystick disconnected",a),ae(Yd[a].id),ae(Yd[a].buttons),ae(Yd[a].axes),delete Yd[a])}}}
function be(a){function b(l){var n="/.glfw_dropped_files/"+l.name.replace(/\//g,"_"),t=new FileReader;t.onloadend=function(z){if(2!=t.readyState)++f,console.log("failed to read dropped file: "+l.name+": "+t.error);else{var C=new Uint8Array(z.target.result);var E=E||{};E.flags=E.flags||577;z=Ob(n,E.flags,E.mode);if("string"===typeof C){var R=new Uint8Array(Ca(C)+1);C=B(C,R,0,R.length);Sb(z,R,0,C,E.pg)}else if(ArrayBuffer.isView(C))Sb(z,C,0,C.byteLength,E.pg);else throw Error("Unsupported data type");
Qb(z);if(++f===e){F.get(Y.Qf)(Y.id,e,c);for(E=0;E<d.length;++E)ae(d[E]);ae(c)}}};t.readAsArrayBuffer(l);var x=ya(jb(n));d.push(x);q(c+4*h,x,"i8*")}if(Y&&Y.Qf&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=ya(Array(4*a.dataTransfer.files.length)),d=[],e=a.dataTransfer.files.length,f=0;Wb();for(var h=0;h<e;++h)b(a.dataTransfer.files[h]);return!1}}function ce(a){if(Y&&Y.Qf)return a.preventDefault(),!1}var de=[];
function Cb(a,b,c,d){a||(a=this);this.parent=a;this.qf=a.qf;this.Gf=null;this.id=tb++;this.name=b;this.mode=c;this.ff={};this.ef={};this.rdev=d}Object.defineProperties(Cb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Tb();ub=Array(4096);Kb(H,"/");I("/tmp");I("/home");I("/home/web_user");
(function(){I("/dev");hb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Mb("/dev/null",259);gb(1280,kb);gb(1536,lb);Mb("/dev/tty",1280);Mb("/dev/tty1",1536);var a=db();Xb("random",a);Xb("urandom",a);I("/dev/shm");I("/dev/shm/tmp")})();I("/proc");I("/proc/self");I("/proc/self/fd");
Kb({qf:function(){var a=nb("/proc/self","fd",16895,73);a.ff={lookup:function(b,c){var d=sb[+c];if(!d)throw new G(8);b={parent:null,qf:{fg:"fake"},ff:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");for(var V,Z=0;32>Z;++Z)zc.push(Array(Z));var ee=new Float32Array(288);for(Z=0;288>Z;++Z)Kc[Z]=ee.subarray(0,Z+1);var fe=new Int32Array(288);for(Z=0;288>Z;++Z)Lc[Z]=fe.subarray(0,Z+1);g.requestFullscreen=function(a,b){ld(a,b)};g.requestAnimationFrame=function(a){qd(a)};
g.setCanvasSize=function(a,b,c){xd(a,b,c)};g.pauseMainLoop=function(){Mc=null;Nc++};g.resumeMainLoop=function(){Nc++;var a=Qc,b=Rc,c=Oc;Oc=null;zd(c,0,!1,Pc,!0);yd(a,b);Mc()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=function(a,b,c,d){return hd(a,b,c,d)};function jb(a,b){var c=Array(Ca(a)+1);a=B(a,c,0,c.length);b&&(c.length=a);return c}Ja.push({cg:function(){ge()}});
var me={b:function(a,b,c,d){m("Assertion failed: "+A(a)+", at: "+[b?A(b):"unknown filename",c,d?A(d):"unknown function"])},l:function(a,b,c){$b=c;try{var d=bc(a);switch(b){case 0:var e=ac();return 0>e?-28:Ob(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=ac(),d.flags|=e,0;case 12:return e=ac(),ta[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return u[he()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof J&&f instanceof G||
m(f),-f.lf}},Ga:function(a,b,c){$b=c;try{var d=bc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=ac();return u[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=ac();if(!d.ef.ug)throw new G(59);return d.ef.ug(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:m("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof J&&f instanceof G||m(f),
-f.lf}},nb:function(a,b,c,d,e,f){try{a:{f<<=12;var h=!1;if(0!==(d&16)&&0!==a%16384)var l=-28;else{if(0!==(d&32)){var n=ie(16384,b);if(!n){l=-48;break a}je(n,0,b);h=!0}else{var t=sb[e];if(!t){l=-8;break a}var x=f;if(0!==(c&2)&&0===(d&2)&&2!==(t.flags&2097155))throw new G(2);if(1===(t.flags&2097155))throw new G(2);if(!t.ef.Ff)throw new G(43);var z=t.ef.Ff(t,a,b,x,c,d);n=z.Ag;h=z.Mf}Zb[n]={wg:n,vg:b,Mf:h,fd:e,zg:c,flags:d,offset:f};l=n}}return l}catch(C){return"undefined"!==typeof J&&C instanceof G||
m(C),-C.lf}},yb:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=Zb[a];if(d&&b===d.vg){var e=sb[d.fd];if(d.zg&2){var f=d.flags,h=d.offset,l=y.slice(a,a+b);e&&e.ef.If&&e.ef.If(e,l,h,b,f)}Zb[a]=null;d.Mf&&ae(d.wg)}c=0}return c}catch(n){return"undefined"!==typeof J&&n instanceof G||m(n),-n.lf}},Ka:function(a,b,c){$b=c;try{var d=A(a),e=c?ac():0;return Ob(d,b,e).fd}catch(f){return"undefined"!==typeof J&&f instanceof G||m(f),-f.lf}},Ba:function(){m()},i:function(a,b){if(0===a)a=Date.now();else if(1===
a||4===a)a=K();else return u[he()>>2]=28,-1;u[b>>2]=a/1E3|0;u[b+4>>2]=a%1E3*1E6|0;return 0},c:function(a,b,c){de.length=0;var d;for(c>>=2;d=y[b++];)(d=105>d)&&c&1&&c++,de.push(d?va[c++>>1]:u[c]),++c;return Xa[a].apply(null,de)},da:function(a){V.activeTexture(a)},ca:function(a,b){V.attachShader(L[a],N[b])},uc:function(a,b){V.beginQuery(a,mc[b])},va:function(a,b){V.kf.beginQueryEXT(a,P[b])},bc:function(a){V.beginTransformFeedback(a)},ba:function(a,b,c){V.bindAttribLocation(L[a],b,A(c))},aa:function(a,
b){35051==a?V.Of=b:35052==a&&(V.mf=b);V.bindBuffer(a,hc[b])},_b:function(a,b,c){V.bindBufferBase(a,b,hc[c])},$b:function(a,b,c,d,e){V.bindBufferRange(a,b,hc[c],d,e)},$:function(a,b){V.bindFramebuffer(a,ic[b])},_:function(a,b){V.bindRenderbuffer(a,jc[b])},eb:function(a,b){V.bindSampler(a,Q[b])},Z:function(a,b){V.bindTexture(a,kc[b])},Ya:function(a,b){V.bindTransformFeedback(a,nc[b])},gc:function(a){V.bindVertexArray(O[a])},ma:function(a){V.bindVertexArray(O[a])},Y:function(a,b,c,d){V.blendColor(a,
b,c,d)},X:function(a){V.blendEquation(a)},W:function(a,b){V.blendEquationSeparate(a,b)},U:function(a,b){V.blendFunc(a,b)},T:function(a,b,c,d){V.blendFuncSeparate(a,b,c,d)},jc:function(a,b,c,d,e,f,h,l,n,t){V.blitFramebuffer(a,b,c,d,e,f,h,l,n,t)},S:function(a,b,c,d){2<=T.version?c?V.bufferData(a,y,d,c,b):V.bufferData(a,b,d):V.bufferData(a,c?y.subarray(c,c+b):b,d)},R:function(a,b,c,d){2<=T.version?V.bufferSubData(a,b,y,d,c):V.bufferSubData(a,b,y.subarray(d,d+c))},Q:function(a){return V.checkFramebufferStatus(a)},
P:function(a){V.clear(a)},Db:function(a,b,c,d){V.clearBufferfi(a,b,c,d)},Eb:function(a,b,c){V.clearBufferfv(a,b,w,c>>2)},Gb:function(a,b,c){V.clearBufferiv(a,b,u,c>>2)},Fb:function(a,b,c){V.clearBufferuiv(a,b,D,c>>2)},O:function(a,b,c,d){V.clearColor(a,b,c,d)},N:function(a){V.clearDepth(a)},M:function(a){V.clearStencil(a)},ob:function(a,b,c,d){return V.clientWaitSync(oc[a],b,(c>>>0)+4294967296*d)},L:function(a,b,c,d){V.colorMask(!!a,!!b,!!c,!!d)},J:function(a){V.compileShader(N[a])},I:function(a,
b,c,d,e,f,h,l){2<=T.version?V.mf?V.compressedTexImage2D(a,b,c,d,e,f,h,l):V.compressedTexImage2D(a,b,c,d,e,f,y,l,h):V.compressedTexImage2D(a,b,c,d,e,f,l?y.subarray(l,l+h):null)},Ac:function(a,b,c,d,e,f,h,l,n){V.mf?V.compressedTexImage3D(a,b,c,d,e,f,h,l,n):V.compressedTexImage3D(a,b,c,d,e,f,h,y,n,l)},H:function(a,b,c,d,e,f,h,l,n){2<=T.version?V.mf?V.compressedTexSubImage2D(a,b,c,d,e,f,h,l,n):V.compressedTexSubImage2D(a,b,c,d,e,f,h,y,n,l):V.compressedTexSubImage2D(a,b,c,d,e,f,h,n?y.subarray(n,n+l):null)},
zc:function(a,b,c,d,e,f,h,l,n,t,x){V.mf?V.compressedTexSubImage3D(a,b,c,d,e,f,h,l,n,t,x):V.compressedTexSubImage3D(a,b,c,d,e,f,h,l,n,y,x,t)},Bb:function(a,b,c,d,e){V.copyBufferSubData(a,b,c,d,e)},G:function(a,b,c,d,e,f,h,l){V.copyTexImage2D(a,b,c,d,e,f,h,l)},F:function(a,b,c,d,e,f,h,l){V.copyTexSubImage2D(a,b,c,d,e,f,h,l)},Bc:function(a,b,c,d,e,f,h,l,n){V.copyTexSubImage3D(a,b,c,d,e,f,h,l,n)},E:function(){var a=vc(L),b=V.createProgram();b.name=a;L[a]=b;return a},D:function(a){var b=vc(N);N[b]=V.createShader(a);
return b},C:function(a){V.cullFace(a)},B:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=hc[d];e&&(V.deleteBuffer(e),e.name=0,hc[d]=null,d==V.Of&&(V.Of=0),d==V.mf&&(V.mf=0))}},A:function(a,b){for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=ic[d];e&&(V.deleteFramebuffer(e),e.name=0,ic[d]=null)}},y:function(a){if(a){var b=L[a];b?(V.deleteProgram(b),b.name=0,L[a]=null,pc[a]=null):S(1281)}},xc:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=mc[d];e&&(V.deleteQuery(e),mc[d]=null)}},xa:function(a,
b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=P[d];e&&(V.kf.deleteQueryEXT(e),P[d]=null)}},x:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=jc[d];e&&(V.deleteRenderbuffer(e),e.name=0,jc[d]=null)}},gb:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Q[d];e&&(V.deleteSampler(e),e.name=0,Q[d]=null)}},w:function(a){if(a){var b=N[a];b?(V.deleteShader(b),N[a]=null):S(1281)}},pb:function(a){if(a){var b=oc[a];b?(V.deleteSync(b),b.name=0,oc[a]=null):S(1281)}},v:function(a,b){for(var c=0;c<a;c++){var d=
u[b+4*c>>2],e=kc[d];e&&(V.deleteTexture(e),e.name=0,kc[d]=null)}},Xa:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=nc[d];e&&(V.deleteTransformFeedback(e),e.name=0,nc[d]=null)}},fc:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2];V.deleteVertexArray(O[d]);O[d]=null}},la:function(a,b){for(var c=0;c<a;c++){var d=u[b+4*c>>2];V.deleteVertexArray(O[d]);O[d]=null}},u:function(a){V.depthFunc(a)},t:function(a){V.depthMask(!!a)},s:function(a,b){V.depthRange(a,b)},r:function(a,b){V.detachShader(L[a],
N[b])},q:function(a){V.disable(a)},p:function(a){V.disableVertexAttribArray(a)},Re:function(a,b,c){V.drawArrays(a,b,c)},tb:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},ha:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},Lc:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},Mc:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},Ia:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},qc:function(a,b){for(var c=zc[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];V.drawBuffers(c)},Hc:function(a,b){for(var c=zc[a],d=0;d<
a;d++)c[d]=u[b+4*d>>2];V.drawBuffers(c)},ia:function(a,b){for(var c=zc[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];V.drawBuffers(c)},Qe:function(a,b,c,d){V.drawElements(a,b,c,d)},sb:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},ga:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},Ic:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},Jc:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},Kc:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},Ec:function(a,b,c,d,e,f){V.drawElements(a,
d,e,f)},Pe:function(a){V.enable(a)},Oe:function(a){V.enableVertexAttribArray(a)},tc:function(a){V.endQuery(a)},ua:function(a){V.kf.endQueryEXT(a)},ac:function(){V.endTransformFeedback()},rb:function(a,b){return(a=V.fenceSync(a,b))?(b=vc(oc),a.name=b,oc[b]=a,b):0},Ne:function(){V.finish()},Me:function(){V.flush()},Le:function(a,b,c,d){V.framebufferRenderbuffer(a,b,c,jc[d])},Ke:function(a,b,c,d,e){V.framebufferTexture2D(a,b,c,kc[d],e)},hc:function(a,b,c,d,e){V.framebufferTextureLayer(a,b,kc[c],d,e)},
Je:function(a){V.frontFace(a)},Ie:function(a,b){U(a,b,"createBuffer",hc)},Fe:function(a,b){U(a,b,"createFramebuffer",ic)},yc:function(a,b){U(a,b,"createQuery",mc)},ya:function(a,b){for(var c=0;c<a;c++){var d=V.kf.createQueryEXT();if(!d){for(S(1282);c<a;)u[b+4*c++>>2]=0;break}var e=vc(P);d.name=e;P[e]=d;u[b+4*c>>2]=e}},Ee:function(a,b){U(a,b,"createRenderbuffer",jc)},hb:function(a,b){U(a,b,"createSampler",Q)},De:function(a,b){U(a,b,"createTexture",kc)},Wa:function(a,b){U(a,b,"createTransformFeedback",
nc)},ec:function(a,b){U(a,b,"createVertexArray",O)},ka:function(a,b){U(a,b,"createVertexArray",O)},Ge:function(a){V.generateMipmap(a)},Ce:function(a,b,c,d,e,f,h){Ac("getActiveAttrib",a,b,c,d,e,f,h)},Be:function(a,b,c,d,e,f,h){Ac("getActiveUniform",a,b,c,d,e,f,h)},vb:function(a,b,c,d,e){a=L[a];if(a=V.getActiveUniformBlockName(a,b))e&&0<c?(c=B(a,y,e,c),d&&(u[d>>2]=c)):d&&(u[d>>2]=0)},wb:function(a,b,c,d){if(d)switch(a=L[a],c){case 35393:a=V.getActiveUniformBlockName(a,b);u[d>>2]=a.length+1;break;default:if(a=
V.getActiveUniformBlockParameter(a,b,c))if("number"==typeof a)u[d>>2]=a;else for(b=0;b<a.length;b++)u[d+4*b>>2]=a[b]}else S(1281)},zb:function(a,b,c,d,e){if(e)if(0<b&&0==c)S(1281);else{a=L[a];for(var f=[],h=0;h<b;h++)f.push(u[c+4*h>>2]);if(a=V.getActiveUniforms(a,f,d))for(b=a.length,h=0;h<b;h++)u[e+4*h>>2]=a[h]}else S(1281)},Ae:function(a,b,c,d){a=V.getAttachedShaders(L[a]);var e=a.length;e>b&&(e=b);u[c>>2]=e;for(b=0;b<e;++b)u[d+4*b>>2]=N.indexOf(a[b])},ze:function(a,b){return V.getAttribLocation(L[a],
A(b))},ye:function(a,b){Cc(a,b,4)},ib:function(a,b,c){c?Bc(c,V.getBufferParameter(a,b)):S(1281)},xe:function(a,b,c){c?u[c>>2]=V.getBufferParameter(a,b):S(1281)},ve:function(){var a=V.getError()||uc;uc=0;return a},ue:function(a,b){Cc(a,b,2)},Pb:function(a,b){return V.getFragDataLocation(L[a],A(b))},te:function(a,b,c,d){a=V.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u[d>>2]=a},jb:function(a,b,c){Dc(a,b,c,1)},lb:function(a,b){Cc(a,
b,1)},cc:function(a,b,c){Dc(a,b,c,0)},se:function(a,b){Cc(a,b,0)},La:function(a,b,c,d,e){if(0>d)S(1281);else if(e){if(a=V.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)u[e+b>>2]=a[b]}else S(1281)},Sa:function(){S(1282)},qe:function(a,b,c,d){a=V.getProgramInfoLog(L[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,y,d,b):0;c&&(u[c>>2]=b)},re:function(a,b,c){if(c)if(a>=fc)S(1281);else{var d=pc[a];if(d)if(35716==b)a=V.getProgramInfoLog(L[a]),null===a&&(a="(unknown error)"),u[c>>
2]=a.length+1;else if(35719==b)u[c>>2]=d.Tf;else if(35722==b){if(-1==d.vf){a=L[a];var e=V.getProgramParameter(a,35721);for(b=d.vf=0;b<e;++b)d.vf=Math.max(d.vf,V.getActiveAttrib(a,b).name.length+1)}u[c>>2]=d.vf}else if(35381==b){if(-1==d.wf)for(a=L[a],e=V.getProgramParameter(a,35382),b=d.wf=0;b<e;++b)d.wf=Math.max(d.wf,V.getActiveUniformBlockName(a,b).length+1);u[c>>2]=d.wf}else u[c>>2]=V.getProgramParameter(L[a],b);else S(1282)}else S(1281)},oa:function(a,b,c){if(c){a=V.kf.getQueryObjectEXT(P[a],
b);var d;"boolean"==typeof a?d=a?1:0:d=a;Bc(c,d)}else S(1281)},ra:function(a,b,c){if(c){a=V.kf.getQueryObjectEXT(P[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else S(1281)},na:function(a,b,c){if(c){a=V.kf.getQueryObjectEXT(P[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Bc(c,d)}else S(1281)},rc:function(a,b,c){if(c){a=V.getQueryParameter(mc[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else S(1281)},qa:function(a,b,c){if(c){a=V.kf.getQueryObjectEXT(P[a],b);var d;"boolean"==typeof a?
d=a?1:0:d=a;u[c>>2]=d}else S(1281)},sc:function(a,b,c){c?u[c>>2]=V.getQuery(a,b):S(1281)},sa:function(a,b,c){c?u[c>>2]=V.kf.getQueryEXT(a,b):S(1281)},pe:function(a,b,c){c?u[c>>2]=V.getRenderbufferParameter(a,b):S(1281)},_a:function(a,b,c){c?(a=Q[a],w[c>>2]=V.getSamplerParameter(a,b)):S(1281)},$a:function(a,b,c){c?(a=Q[a],u[c>>2]=V.getSamplerParameter(a,b)):S(1281)},ne:function(a,b,c,d){a=V.getShaderInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,y,d,b):0;c&&(u[c>>2]=b)},me:function(a,b,
c,d){a=V.getShaderPrecisionFormat(a,b);u[c>>2]=a.rangeMin;u[c+4>>2]=a.rangeMax;u[d>>2]=a.precision},le:function(a,b,c,d){if(a=V.getShaderSource(N[a]))b=0<b&&d?B(a,y,d,b):0,c&&(u[c>>2]=b)},oe:function(a,b,c){c?35716==b?(a=V.getShaderInfoLog(N[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=V.getShaderSource(N[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=V.getShaderParameter(N[a],b):S(1281)},ke:function(a){if(rc[a])return rc[a];switch(a){case 7939:var b=V.getSupportedExtensions()||[];
b=b.concat(b.map(function(d){return"GL_"+d}));b=Ec(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=V.getParameter(a))||S(1280);b=Ec(b);break;case 7938:b=V.getParameter(7938);b=2<=T.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Ec(b);break;case 35724:b=V.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Ec(b);break;default:return S(1280),0}return rc[a]=b},Cb:function(a,
b){if(2>T.version)return S(1282),0;var c=sc[a];if(c)return 0>b||b>=c.length?(S(1281),0):c[b];switch(a){case 7939:return c=V.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return Ec(d)}),c=sc[a]=c,0>b||b>=c.length?(S(1281),0):c[b];default:return S(1280),0}},kb:function(a,b,c,d,e){0>c?S(1281):e?(a=V.getSyncParameter(oc[a],b),u[d>>2]=a,null!==a&&d&&(u[d>>2]=1)):S(1281)},je:function(a,b,c){c?w[c>>2]=V.getTexParameter(a,b):S(1281)},ie:function(a,b,c){c?u[c>>
2]=V.getTexParameter(a,b):S(1281)},Yb:function(a,b,c,d,e,f,h){a=L[a];if(a=V.getTransformFeedbackVarying(a,b))h&&0<c?(c=B(a.name,y,h,c),d&&(u[d>>2]=c)):d&&(u[d>>2]=0),e&&(u[e>>2]=a.size),f&&(u[f>>2]=a.type)},xb:function(a,b){return V.getUniformBlockIndex(L[a],A(b))},Ab:function(a,b,c,d){if(d)if(0<b&&(0==c||0==d))S(1281);else{a=L[a];for(var e=[],f=0;f<b;f++)e.push(A(u[c+4*f>>2]));if(a=V.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)u[d+4*f>>2]=a[f]}else S(1281)},fe:function(a,b){b=A(b);var c=0;
if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=pc[a]&&pc[a].lg[b])&&0<=c&&c<a[0]?a[1]+c:-1},he:function(a,b,c){Fc(a,b,c,2)},ge:function(a,b,c){Fc(a,b,c,0)},Qb:function(a,b,c){Fc(a,b,c,0)},Wb:function(a,b,c){Gc(a,b,c,0)},Vb:function(a,b,c){Gc(a,b,c,0)},ce:function(a,b,c){c?u[c>>2]=V.getVertexAttribOffset(a,b):S(1281)},ee:function(a,b,c){Gc(a,b,c,2)},de:function(a,b,c){Gc(a,b,c,5)},ae:function(a,b){V.hint(a,b)},Pa:function(a,b,c){for(var d=
zc[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];V.invalidateFramebuffer(a,d)},Oa:function(a,b,c,d,e,f,h){for(var l=zc[b],n=0;n<b;n++)l[n]=u[c+4*n>>2];V.invalidateSubFramebuffer(a,l,d,e,f,h)},$d:function(a){return(a=hc[a])?V.isBuffer(a):0},_d:function(a){return V.isEnabled(a)},Zd:function(a){return(a=ic[a])?V.isFramebuffer(a):0},Yd:function(a){return(a=L[a])?V.isProgram(a):0},wc:function(a){return(a=mc[a])?V.isQuery(a):0},wa:function(a){return(a=P[a])?V.kf.isQueryEXT(a):0},Xd:function(a){return(a=jc[a])?V.isRenderbuffer(a):
0},fb:function(a){return(a=Q[a])?V.isSampler(a):0},Wd:function(a){return(a=N[a])?V.isShader(a):0},qb:function(a){return V.isSync(oc[a])},Vd:function(a){return(a=kc[a])?V.isTexture(a):0},Va:function(a){return V.isTransformFeedback(nc[a])},dc:function(a){return(a=O[a])?V.isVertexArray(a):0},ja:function(a){return(a=O[a])?V.isVertexArray(a):0},Ud:function(a){V.lineWidth(a)},Td:function(a){V.linkProgram(L[a]);var b=L[a];a=pc[a]={lg:{},Tf:0,vf:-1,wf:-1};for(var c=a.lg,d=V.getProgramParameter(b,35718),e=
0;e<d;++e){var f=V.getActiveUniform(b,e),h=f.name;a.Tf=Math.max(a.Tf,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var l=V.getUniformLocation(b,h);if(l){var n=vc(M);c[h]=[f.size,n];M[n]=l;for(var t=1;t<f.size;++t)l=V.getUniformLocation(b,h+"["+t+"]"),n=vc(M),M[n]=l}}},Ua:function(){V.pauseTransformFeedback()},Rd:function(a,b){3317==a&&(tc=b);V.pixelStorei(a,b)},Qd:function(a,b){V.polygonOffset(a,b)},Ra:function(){S(1280)},Qa:function(){S(1280)},ta:function(a,b){V.kf.queryCounterEXT(P[a],
b)},Fc:function(a){V.readBuffer(a)},Pd:function(a,b,c,d,e,f,h){if(2<=T.version)if(V.Of)V.readPixels(a,b,c,d,e,f,h);else{var l=Hc(f);V.readPixels(a,b,c,d,e,f,l,h>>Ic(l))}else(h=Jc(f,e,c,d,h))?V.readPixels(a,b,c,d,e,f,h):S(1280)},Od:function(){},Nd:function(a,b,c,d){V.renderbufferStorage(a,b,c,d)},ic:function(a,b,c,d,e){V.renderbufferStorageMultisample(a,b,c,d,e)},Ta:function(){V.resumeTransformFeedback()},Md:function(a,b){V.sampleCoverage(a,!!b)},bb:function(a,b,c){V.samplerParameterf(Q[a],b,c)},ab:function(a,
b,c){V.samplerParameterf(Q[a],b,w[c>>2])},db:function(a,b,c){V.samplerParameteri(Q[a],b,c)},cb:function(a,b,c){V.samplerParameteri(Q[a],b,u[c>>2])},Ld:function(a,b,c,d){V.scissor(a,b,c,d)},Kd:function(){S(1280)},Jd:function(a,b,c,d){for(var e="",f=0;f<b;++f){var h=d?u[d+4*f>>2]:-1;e+=A(u[c+4*f>>2],0>h?void 0:h)}V.shaderSource(N[a],e)},Id:function(a,b,c){V.stencilFunc(a,b,c)},Gd:function(a,b,c,d){V.stencilFuncSeparate(a,b,c,d)},Fd:function(a){V.stencilMask(a)},Ed:function(a,b){V.stencilMaskSeparate(a,
b)},Dd:function(a,b,c){V.stencilOp(a,b,c)},Cd:function(a,b,c,d){V.stencilOpSeparate(a,b,c,d)},Bd:function(a,b,c,d,e,f,h,l,n){if(2<=T.version)if(V.mf)V.texImage2D(a,b,c,d,e,f,h,l,n);else if(n){var t=Hc(l);V.texImage2D(a,b,c,d,e,f,h,l,t,n>>Ic(t))}else V.texImage2D(a,b,c,d,e,f,h,l,null);else V.texImage2D(a,b,c,d,e,f,h,l,n?Jc(l,h,d,e,n):null)},Dc:function(a,b,c,d,e,f,h,l,n,t){if(V.mf)V.texImage3D(a,b,c,d,e,f,h,l,n,t);else if(t){var x=Hc(n);V.texImage3D(a,b,c,d,e,f,h,l,n,x,t>>Ic(x))}else V.texImage3D(a,
b,c,d,e,f,h,l,n,null)},Ad:function(a,b,c){V.texParameterf(a,b,c)},zd:function(a,b,c){V.texParameterf(a,b,w[c>>2])},yd:function(a,b,c){V.texParameteri(a,b,c)},xd:function(a,b,c){V.texParameteri(a,b,u[c>>2])},Na:function(a,b,c,d,e){V.texStorage2D(a,b,c,d,e)},Ma:function(a,b,c,d,e,f){V.texStorage3D(a,b,c,d,e,f)},vd:function(a,b,c,d,e,f,h,l,n){if(2<=T.version)if(V.mf)V.texSubImage2D(a,b,c,d,e,f,h,l,n);else if(n){var t=Hc(l);V.texSubImage2D(a,b,c,d,e,f,h,l,t,n>>Ic(t))}else V.texSubImage2D(a,b,c,d,e,f,
h,l,null);else t=null,n&&(t=Jc(l,h,e,f,n)),V.texSubImage2D(a,b,c,d,e,f,h,l,t)},Cc:function(a,b,c,d,e,f,h,l,n,t,x){if(V.mf)V.texSubImage3D(a,b,c,d,e,f,h,l,n,t,x);else if(x){var z=Hc(t);V.texSubImage3D(a,b,c,d,e,f,h,l,n,t,z,x>>Ic(z))}else V.texSubImage3D(a,b,c,d,e,f,h,l,n,t,null)},Zb:function(a,b,c,d){a=L[a];for(var e=[],f=0;f<b;f++)e.push(A(u[c+4*f>>2]));V.transformFeedbackVaryings(a,e,d)},ud:function(a,b){V.uniform1f(M[a],b)},td:function(a,b,c){if(2<=T.version)V.uniform1fv(M[a],w,c>>2,b);else{if(288>=
b)for(var d=Kc[b-1],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);V.uniform1fv(M[a],d)}},sd:function(a,b){V.uniform1i(M[a],b)},rd:function(a,b,c){if(2<=T.version)V.uniform1iv(M[a],u,c>>2,b);else{if(288>=b)for(var d=Lc[b-1],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);V.uniform1iv(M[a],d)}},Ob:function(a,b){V.uniform1ui(M[a],b)},Kb:function(a,b,c){V.uniform1uiv(M[a],D,c>>2,b)},qd:function(a,b,c){V.uniform2f(M[a],b,c)},pd:function(a,b,c){if(2<=T.version)V.uniform2fv(M[a],
w,c>>2,2*b);else{if(144>=b)for(var d=Kc[2*b-1],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);V.uniform2fv(M[a],d)}},od:function(a,b,c){V.uniform2i(M[a],b,c)},nd:function(a,b,c){if(2<=T.version)V.uniform2iv(M[a],u,c>>2,2*b);else{if(144>=b)for(var d=Lc[2*b-1],e=0;e<2*b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2];else d=u.subarray(c>>2,c+8*b>>2);V.uniform2iv(M[a],d)}},Nb:function(a,b,c){V.uniform2ui(M[a],b,c)},Jb:function(a,b,c){V.uniform2uiv(M[a],D,c>>2,2*
b)},md:function(a,b,c,d){V.uniform3f(M[a],b,c,d)},kd:function(a,b,c){if(2<=T.version)V.uniform3fv(M[a],w,c>>2,3*b);else{if(96>=b)for(var d=Kc[3*b-1],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);V.uniform3fv(M[a],d)}},jd:function(a,b,c,d){V.uniform3i(M[a],b,c,d)},id:function(a,b,c){if(2<=T.version)V.uniform3iv(M[a],u,c>>2,3*b);else{if(96>=b)for(var d=Lc[3*b-1],e=0;e<3*b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>
2];else d=u.subarray(c>>2,c+12*b>>2);V.uniform3iv(M[a],d)}},Mb:function(a,b,c,d){V.uniform3ui(M[a],b,c,d)},Ib:function(a,b,c){V.uniform3uiv(M[a],D,c>>2,3*b)},hd:function(a,b,c,d,e){V.uniform4f(M[a],b,c,d,e)},gd:function(a,b,c){if(2<=T.version)V.uniform4fv(M[a],w,c>>2,4*b);else{if(72>=b){var d=Kc[4*b-1],e=w;c>>=2;for(var f=0;f<4*b;f+=4){var h=c+f;d[f]=e[h];d[f+1]=e[h+1];d[f+2]=e[h+2];d[f+3]=e[h+3]}}else d=w.subarray(c>>2,c+16*b>>2);V.uniform4fv(M[a],d)}},fd:function(a,b,c,d,e){V.uniform4i(M[a],b,c,
d,e)},ed:function(a,b,c){if(2<=T.version)V.uniform4iv(M[a],u,c>>2,4*b);else{if(72>=b)for(var d=Lc[4*b-1],e=0;e<4*b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2];else d=u.subarray(c>>2,c+16*b>>2);V.uniform4iv(M[a],d)}},Lb:function(a,b,c,d,e){V.uniform4ui(M[a],b,c,d,e)},Hb:function(a,b,c){V.uniform4uiv(M[a],D,c>>2,4*b)},ub:function(a,b,c){a=L[a];V.uniformBlockBinding(a,b,c)},dd:function(a,b,c,d){if(2<=T.version)V.uniformMatrix2fv(M[a],!!c,w,d>>2,4*b);else{if(72>=
b)for(var e=Kc[4*b-1],f=0;f<4*b;f+=4)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2];else e=w.subarray(d>>2,d+16*b>>2);V.uniformMatrix2fv(M[a],!!c,e)}},pc:function(a,b,c,d){V.uniformMatrix2x3fv(M[a],!!c,w,d>>2,6*b)},nc:function(a,b,c,d){V.uniformMatrix2x4fv(M[a],!!c,w,d>>2,8*b)},cd:function(a,b,c,d){if(2<=T.version)V.uniformMatrix3fv(M[a],!!c,w,d>>2,9*b);else{if(32>=b)for(var e=Kc[9*b-1],f=0;f<9*b;f+=9)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+
8)>>2],e[f+3]=w[d+(4*f+12)>>2],e[f+4]=w[d+(4*f+16)>>2],e[f+5]=w[d+(4*f+20)>>2],e[f+6]=w[d+(4*f+24)>>2],e[f+7]=w[d+(4*f+28)>>2],e[f+8]=w[d+(4*f+32)>>2];else e=w.subarray(d>>2,d+36*b>>2);V.uniformMatrix3fv(M[a],!!c,e)}},oc:function(a,b,c,d){V.uniformMatrix3x2fv(M[a],!!c,w,d>>2,6*b)},lc:function(a,b,c,d){V.uniformMatrix3x4fv(M[a],!!c,w,d>>2,12*b)},bd:function(a,b,c,d){if(2<=T.version)V.uniformMatrix4fv(M[a],!!c,w,d>>2,16*b);else{if(18>=b){var e=Kc[16*b-1],f=w;d>>=2;for(var h=0;h<16*b;h+=16){var l=d+
h;e[h]=f[l];e[h+1]=f[l+1];e[h+2]=f[l+2];e[h+3]=f[l+3];e[h+4]=f[l+4];e[h+5]=f[l+5];e[h+6]=f[l+6];e[h+7]=f[l+7];e[h+8]=f[l+8];e[h+9]=f[l+9];e[h+10]=f[l+10];e[h+11]=f[l+11];e[h+12]=f[l+12];e[h+13]=f[l+13];e[h+14]=f[l+14];e[h+15]=f[l+15]}}else e=w.subarray(d>>2,d+64*b>>2);V.uniformMatrix4fv(M[a],!!c,e)}},mc:function(a,b,c,d){V.uniformMatrix4x2fv(M[a],!!c,w,d>>2,8*b)},kc:function(a,b,c,d){V.uniformMatrix4x3fv(M[a],!!c,w,d>>2,12*b)},$c:function(a){V.useProgram(L[a])},_c:function(a){V.validateProgram(L[a])},
Zc:function(a,b){V.vertexAttrib1f(a,b)},Yc:function(a,b){V.vertexAttrib1f(a,w[b>>2])},Xc:function(a,b,c){V.vertexAttrib2f(a,b,c)},Wc:function(a,b){V.vertexAttrib2f(a,w[b>>2],w[b+4>>2])},Vc:function(a,b,c,d){V.vertexAttrib3f(a,b,c,d)},Uc:function(a,b){V.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},Tc:function(a,b,c,d,e){V.vertexAttrib4f(a,b,c,d,e)},Sc:function(a,b){V.vertexAttrib4f(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},Za:function(a,b){V.vertexAttribDivisor(a,b)},fa:function(a,b){V.vertexAttribDivisor(a,
b)},Nc:function(a,b){V.vertexAttribDivisor(a,b)},Oc:function(a,b){V.vertexAttribDivisor(a,b)},Ja:function(a,b){V.vertexAttribDivisor(a,b)},Ub:function(a,b,c,d,e){V.vertexAttribI4i(a,b,c,d,e)},Sb:function(a,b){V.vertexAttribI4i(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},Tb:function(a,b,c,d,e){V.vertexAttribI4ui(a,b,c,d,e)},Rb:function(a,b){V.vertexAttribI4ui(a,D[b>>2],D[b+4>>2],D[b+8>>2],D[b+12>>2])},Xb:function(a,b,c,d,e){V.vertexAttribIPointer(a,b,c,d,e)},Qc:function(a,b,c,d,e,f){V.vertexAttribPointer(a,
b,c,!!d,e,f)},Pc:function(a,b,c,d){V.viewport(a,b,c,d)},mb:function(a,b,c,d){V.waitSync(oc[a],b,(c>>>0)+4294967296*d)},f:function(){return 0},za:function(a,b,c){y.copyWithin(a,b,b+c)},d:function(a){a>>>=0;var b=y.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{wa.grow(Math.min(2147483648,d)-Fa.byteLength+65535>>>16);Ha();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Aa:function(a,
b,c,d,e){a=F.get(a);zd(a,b,c,d,e)},e:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Ea:function(a){for(var b=K();K()-b<a;);},Ca:function(a,b){try{var c=0;Bd().forEach(function(d,e){var f=b+c;e=u[a+4*e>>2]=f;for(f=0;f<d.length;++f)r[e++>>0]=d.charCodeAt(f);r[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof J&&d instanceof G||m(d),d.lf}},Da:function(a,b){try{var c=Bd();u[a>>2]=c.length;var d=0;c.forEach(function(e){d+=
e.length+1});u[b>>2]=d;return 0}catch(e){return"undefined"!==typeof J&&e instanceof G||m(e),e.lf}},k:function(a){ke(a)},o:function(a){try{var b=bc(a);Qb(b);return 0}catch(c){return"undefined"!==typeof J&&c instanceof G||m(c),c.lf}},Fa:function(a,b,c,d){try{a:{for(var e=bc(a),f=a=0;f<c;f++){var h=u[b+(8*f+4)>>2],l=e,n=u[b+8*f>>2],t=h,x=void 0,z=r;if(0>t||0>x)throw new G(28);if(null===l.fd)throw new G(8);if(1===(l.flags&2097155))throw new G(8);if(16384===(l.node.mode&61440))throw new G(31);if(!l.ef.read)throw new G(28);
var C="undefined"!==typeof x;if(!C)x=l.position;else if(!l.seekable)throw new G(70);var E=l.ef.read(l,z,n,t,x);C||(l.position+=E);var R=E;if(0>R){var Fb=-1;break a}a+=R;if(R<h)break}Fb=a}u[d>>2]=Fb;return 0}catch(qc){return"undefined"!==typeof J&&qc instanceof G||m(qc),qc.lf}},Ha:function(a,b,c,d,e){try{var f=bc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Rb(f,a,d);ua=[f.position>>>0,(v=f.position,1<=+Math.abs(v)?0<v?(Math.min(+Math.floor(v/4294967296),4294967295)|
0)>>>0:~~+Math.ceil((v-+(~~v>>>0))/4294967296)>>>0:0)];u[e>>2]=ua[0];u[e+4>>2]=ua[1];f.Sf&&0===a&&0===d&&(f.Sf=null);return 0}catch(h){return"undefined"!==typeof J&&h instanceof G||m(h),h.lf}},n:function(a,b,c,d){try{a:{for(var e=bc(a),f=a=0;f<c;f++){var h=Sb(e,r,u[b+8*f>>2],u[b+(8*f+4)>>2]);if(0>h){var l=-1;break a}a+=h}l=a}u[d>>2]=l;return 0}catch(n){return"undefined"!==typeof J&&n instanceof G||m(n),n.lf}},j:function(a){var b=Date.now();u[a>>2]=b/1E3|0;u[a+4>>2]=b%1E3*1E3|0;return 0},He:function(a,
b,c,d){var e;for(e=0;e<X.length&&null!==X[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var f=e+1;if(0>=a||0>=b)f=0;else{d?ld():xd(a,b);for(e=0;e<X.length&&null==X[e];e++);d=0<W[139265];e==X.length&&(d?g.tf=hd(g.canvas,!0,!0,{antialias:1<W[135181],depth:0<W[135173],stencil:0<W[135174],alpha:0<W[135172]}):ad());!g.tf&&d?f=0:(a=new Dd(f,a,b,c),f-1==X.length?X.push(a):X[f-1]=a,Y=a,f=a.id)}return f},z:function(){W=Gd},Gc:function(a){a:{if(a=Ed(a)){a.mg&&F.get(a.mg)(a.id);
X[a.id-1]=null;Y.id==a.id&&(Y=null);for(a=0;a<X.length;a++)if(null!==X[a]){a=void 0;break a}g.tf=void 0}a=void 0}return a},ad:function(a,b,c){q(b,rd,"double");q(c,sd,"double")},Rc:function(a,b,c){var d=0,e=0;if(a=Ed(a))d=a.width,e=a.height;b&&q(b,d,"i32");c&&q(c,e,"i32")},a:function(a){return le(a)},K:function(){if(X)return 1;K();W=Gd;X=[];Y=null;window.addEventListener("gamepadconnected",Ld,!0);window.addEventListener("gamepaddisconnected",Nd,!0);window.addEventListener("keydown",Od,!0);window.addEventListener("keypress",
Jd,!0);window.addEventListener("keyup",Pd,!0);window.addEventListener("blur",Qd,!0);g.canvas.addEventListener("touchmove",Rd,!0);g.canvas.addEventListener("touchstart",Vd,!0);g.canvas.addEventListener("touchcancel",Wd,!0);g.canvas.addEventListener("touchend",Wd,!0);g.canvas.addEventListener("mousemove",Rd,!0);g.canvas.addEventListener("mousedown",Vd,!0);g.canvas.addEventListener("mouseup",Wd,!0);g.canvas.addEventListener("wheel",Xd,!0);g.canvas.addEventListener("mousewheel",Xd,!0);g.canvas.addEventListener("mouseenter",
Sd,!0);g.canvas.addEventListener("mouseleave",Td,!0);g.canvas.addEventListener("drop",be,!0);g.canvas.addEventListener("dragover",ce,!0);wd.push(function(a,b){if(Y){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Y.jg=Y.x,Y.kg=Y.y,Y.ig=Y.width,Y.hg=Y.height,Y.x=Y.y=0,Y.width=screen.width,Y.height=screen.height,Y.Rf=!0):1==Y.Rf?(Y.x=Y.jg,Y.y=Y.kg,Y.width=Y.ig,Y.height=Y.hg,Y.Rf=!1):Y.width!=a||Y.height!=b?(Y.width=a,Y.height=b):c=!1;c&&(xd(Y.width,
Y.height,!0),Y&&Y.ng&&F.get(Y.ng)(Y.id,Y.width,Y.height),Y&&Y.Bf&&F.get(Y.Bf)(Y.id,Y.width,Y.height))}});return 1},we:function(){},pa:function(){},Sd:function(a,b){if(a=Ed(a)){var c=a.Af;a.Af=b;b=c}else b=null;return b},V:function(a){var b=Fd;Fd=a;return b},be:function(a,b){a=Ed(a);if(!a)return null;var c=a.Bf;a.Bf=b;return c},Hd:function(a,b){if(a=Ed(a)){var c=a.Cf;a.Cf=b;b=c}else b=null;return b},ld:function(a,b){if(a=Ed(a)){var c=a.Hf;a.Hf=b;b=c}else b=null;return b},wd:function(a,b){if(a=Ed(a)){var c=
a.Jf;a.Jf=b;b=c}else b=null;return b},ea:function(){},vc:function(){window.removeEventListener("gamepadconnected",Ld,!0);window.removeEventListener("gamepaddisconnected",Nd,!0);window.removeEventListener("keydown",Od,!0);window.removeEventListener("keypress",Jd,!0);window.removeEventListener("keyup",Pd,!0);window.removeEventListener("blur",Qd,!0);g.canvas.removeEventListener("touchmove",Rd,!0);g.canvas.removeEventListener("touchstart",Vd,!0);g.canvas.removeEventListener("touchcancel",Wd,!0);g.canvas.removeEventListener("touchend",
Wd,!0);g.canvas.removeEventListener("mousemove",Rd,!0);g.canvas.removeEventListener("mousedown",Vd,!0);g.canvas.removeEventListener("mouseup",Wd,!0);g.canvas.removeEventListener("wheel",Xd,!0);g.canvas.removeEventListener("mousewheel",Xd,!0);g.canvas.removeEventListener("mouseenter",Sd,!0);g.canvas.removeEventListener("mouseleave",Td,!0);g.canvas.removeEventListener("drop",be,!0);g.canvas.removeEventListener("dragover",ce,!0);g.canvas.width=g.canvas.height=1;Y=X=null},h:function(a,b){W[a]=b},m:function(){},
g:function(){return 0}};
(function(){function a(e){g.asm=e.exports;wa=g.asm.Se;Ha();F=g.asm.Te;Na--;g.monitorRunDependencies&&g.monitorRunDependencies(Na);0==Na&&(null!==Oa&&(clearInterval(Oa),Oa=null),Pa&&(e=Pa,Pa=null,e()))}function b(e){a(e.instance)}function c(e){return Va().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){p("failed to asynchronously prepare wasm: "+f);m(f)})}var d={a:me};Na++;g.monitorRunDependencies&&g.monitorRunDependencies(Na);if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return p("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){return sa||"function"!==typeof WebAssembly.instantiateStreaming||Sa()||Qa("file://")||"function"!==typeof fetch?c(b):fetch(Ra,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){p("wasm streaming compile failed: "+f);p("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var ge=g.___wasm_call_ctors=function(){return(ge=g.___wasm_call_ctors=g.asm.Ue).apply(null,arguments)},ae=g._free=function(){return(ae=g._free=g.asm.Ve).apply(null,arguments)},za=g._malloc=function(){return(za=g._malloc=g.asm.We).apply(null,arguments)};g._main=function(){return(g._main=g.asm.Xe).apply(null,arguments)};
var he=g.___errno_location=function(){return(he=g.___errno_location=g.asm.Ye).apply(null,arguments)},le=g._emscripten_GetProcAddress=function(){return(le=g._emscripten_GetProcAddress=g.asm.Ze).apply(null,arguments)},je=g._memset=function(){return(je=g._memset=g.asm._e).apply(null,arguments)},Ea=g.stackAlloc=function(){return(Ea=g.stackAlloc=g.asm.$e).apply(null,arguments)},ie=g._memalign=function(){return(ie=g._memalign=g.asm.af).apply(null,arguments)};
g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.bf).apply(null,arguments)};g.dynCall_ji=function(){return(g.dynCall_ji=g.asm.cf).apply(null,arguments)};var ne;function oa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Pa=function oe(){ne||pe();ne||(Pa=oe)};
function pe(a){function b(){if(!ne&&(ne=!0,g.calledRun=!0,!xa)){g.noFSInit||Ub||(Ub=!0,Tb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?Xb("stdin",g.stdin):Nb("/dev/tty","/dev/stdin"),g.stdout?Xb("stdout",null,g.stdout):Nb("/dev/tty","/dev/stdout"),g.stderr?Xb("stderr",null,g.stderr):Nb("/dev/tty1","/dev/stderr"),Ob("/dev/stdin",0),Ob("/dev/stdout",1),Ob("/dev/stderr",1));Za(Ja);vb=!1;Za(Ka);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(qe){var c=a,d=g._main;c=c||[];var e=
c.length+1,f=Ea(4*(e+1));u[f>>2]=Da(da);for(var h=1;h<e;h++)u[(f>>2)+h]=Da(c[h-1]);u[(f>>2)+e]=0;try{var l=d(e,f);ke(l,!0)}catch(n){n instanceof oa||("unwind"==n?noExitRuntime=!0:((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),p("exception thrown: "+c),ea(1,n)))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=g.postRun.shift(),La.unshift(c);Za(La)}}a=a||ca;if(!(0<Na)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ma();
Za(Ia);0<Na||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=pe;function ke(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(g.onExit)g.onExit(a);xa=!0}ea(a,new oa(a))}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var qe=!0;g.noInitialRun&&(qe=!1);noExitRuntime=!0;pe();
